export const APTITUDE_CATEGORIES = {
  quant: {
    label: 'Quantitative Aptitude',
    color: '#1D9E75',
    icon: '🔢',
    description: 'Math and number-based problem solving',
    topics: [
      { slug: 'percentages', name: 'Percentages', difficulty: 'easy' },
      { slug: 'profit-loss', name: 'Profit & Loss', difficulty: 'easy' },
      { slug: 'ratio-proportion', name: 'Ratio & Proportion', difficulty: 'easy' },
      { slug: 'time-work', name: 'Time & Work', difficulty: 'medium' },
      { slug: 'time-speed-distance', name: 'Time, Speed & Distance', difficulty: 'medium' },
      { slug: 'averages', name: 'Averages', difficulty: 'easy' },
      { slug: 'simple-compound-interest', name: 'Simple & Compound Interest', difficulty: 'medium' },
      { slug: 'permutation-combination', name: 'Permutation & Combination', difficulty: 'hard' },
      { slug: 'probability', name: 'Probability', difficulty: 'hard' },
      { slug: 'number-systems', name: 'Number Systems', difficulty: 'medium' },
    ],
  },
  logical: {
    label: 'Logical Reasoning',
    color: '#ff6b4a',
    icon: '🧠',
    description: 'Pattern recognition and logical thinking',
    topics: [
      { slug: 'seating-arrangement', name: 'Seating Arrangement', difficulty: 'medium' },
      { slug: 'blood-relations', name: 'Blood Relations', difficulty: 'easy' },
      { slug: 'coding-decoding', name: 'Coding-Decoding', difficulty: 'medium' },
      { slug: 'syllogisms', name: 'Syllogisms', difficulty: 'medium' },
      { slug: 'puzzles', name: 'Puzzles', difficulty: 'hard' },
      { slug: 'number-series', name: 'Number & Letter Series', difficulty: 'easy' },
      { slug: 'data-interpretation', name: 'Data Interpretation', difficulty: 'medium' },
      { slug: 'statements-conclusions', name: 'Statements & Conclusions', difficulty: 'medium' },
      { slug: 'direction-sense', name: 'Direction Sense', difficulty: 'easy' },
      { slug: 'analogies', name: 'Analogies', difficulty: 'easy' },
    ],
  },
  verbal: {
    label: 'Verbal Ability',
    color: '#EF9F27',
    icon: '📝',
    description: 'English language and communication',
    topics: [
      { slug: 'grammar', name: 'Grammar', difficulty: 'easy' },
      { slug: 'reading-comprehension', name: 'Reading Comprehension', difficulty: 'medium' },
      { slug: 'sentence-correction', name: 'Sentence Correction', difficulty: 'medium' },
      { slug: 'synonyms-antonyms', name: 'Synonyms & Antonyms', difficulty: 'easy' },
      { slug: 'vocabulary', name: 'Vocabulary', difficulty: 'medium' },
      { slug: 'para-jumbles', name: 'Para Jumbles', difficulty: 'medium' },
      { slug: 'fill-in-blanks', name: 'Fill in the Blanks', difficulty: 'easy' },
      { slug: 'error-spotting', name: 'Error Spotting', difficulty: 'medium' },
      { slug: 'idioms-phrases', name: 'Idioms & Phrases', difficulty: 'medium' },
      { slug: 'cloze-test', name: 'Cloze Test', difficulty: 'hard' },
    ],
  },
};

export const APTITUDE_ROADMAP = [
  { week: 1, focus: 'Quant Basics', topics: ['percentages', 'profit-loss', 'averages'], category: 'quant' },
  { week: 2, focus: 'Quant Medium', topics: ['time-work', 'time-speed-distance', 'simple-compound-interest'], category: 'quant' },
  { week: 3, focus: 'Logical Basics', topics: ['blood-relations', 'number-series', 'direction-sense', 'analogies'], category: 'logical' },
  { week: 4, focus: 'Logical Medium', topics: ['seating-arrangement', 'coding-decoding', 'syllogisms'], category: 'logical' },
  { week: 5, focus: 'Verbal Basics', topics: ['grammar', 'synonyms-antonyms', 'fill-in-blanks'], category: 'verbal' },
  { week: 6, focus: 'Verbal Medium', topics: ['reading-comprehension', 'sentence-correction', 'vocabulary'], category: 'verbal' },
  { week: 7, focus: 'Mixed Hard', topics: ['permutation-combination', 'probability', 'puzzles'], category: 'mixed' },
  { week: 8, focus: 'Full Mock Tests', topics: ['all'], category: 'mixed' },
];
