export const COMPANIES = [
  {
    slug: 'tcs',
    name: 'TCS',
    fullName: 'Tata Consultancy Services',
    tier: 'service',
    logo: '🏢',
    color: '#0066B2',
    eligibility: '60% throughout 10th, 12th, UG. No backlogs.',
    package: '3.36 - 9 LPA (Digital), 7-9 LPA (NQT)',
    rounds: ['NQT Aptitude Test', 'Technical Interview', 'Managerial Round', 'HR Interview'],
    duration: '1.5 - 2 months',
    prepTime: '2-3 months',
    skills: ['C/C++/Java', 'DBMS basics', 'Data Structures', 'Aptitude', 'English Communication'],
    tips: [
      'Focus heavily on NQT - it is the main filter',
      'Brush up on basic C/Java syntax',
      'Be ready to write code on paper',
      'Project explanation matters in HR round',
      'Know your resume in and out',
    ],
    resources: [
      { label: 'TCS NQT Past Papers', url: 'https://www.indiabix.com/' },
      { label: 'PrepInsta TCS Guide', url: 'https://prepinsta.com/tcs/' },
    ],
  },
  {
    slug: 'infosys',
    name: 'Infosys',
    fullName: 'Infosys Limited',
    tier: 'service',
    logo: '💼',
    color: '#007CC3',
    eligibility: '60% throughout, no active backlogs.',
    package: '3.6 - 9 LPA (Power Programmer goes up to 11 LPA)',
    rounds: ['InfyTQ Test', 'Technical Interview', 'HR Interview'],
    duration: '1 - 1.5 months',
    prepTime: '2 months',
    skills: ['Python/Java', 'OOP concepts', 'SQL', 'Aptitude', 'Logical Reasoning'],
    tips: [
      'InfyTQ has coding round - practice Python or Java',
      'Power Programmer role pays much higher - try for it',
      'Cloud and AI questions appear frequently',
      'Show enthusiasm in HR round',
    ],
    resources: [
      { label: 'InfyTQ Practice', url: 'https://infytq.onwingspan.com/' },
      { label: 'GeeksforGeeks Infosys Prep', url: 'https://www.geeksforgeeks.org/infosys-recruitment-process/' },
    ],
  },
  {
    slug: 'wipro',
    name: 'Wipro',
    fullName: 'Wipro Limited',
    tier: 'service',
    logo: '🌐',
    color: '#341F65',
    eligibility: '60% throughout, no backlogs.',
    package: '3.5 - 6.5 LPA (Elite NLTH 6.5 LPA)',
    rounds: ['Online Aptitude', 'Coding Round', 'Technical Interview', 'Business Discussion / HR'],
    duration: '1 - 2 months',
    prepTime: '2 months',
    skills: ['C/C++/Java/Python', 'DBMS', 'OS', 'Networking basics', 'Aptitude'],
    tips: [
      'Elite NLTH gives much better package - prepare for it',
      'Coding section needs 2 problems solved completely',
      'Essay writing is part of the test - practice English',
      'Be confident in business discussion round',
    ],
    resources: [
      { label: 'Wipro Elite Prep', url: 'https://www.geeksforgeeks.org/wipro-recruitment-process/' },
    ],
  },
  {
    slug: 'amazon',
    name: 'Amazon',
    fullName: 'Amazon',
    tier: 'product',
    logo: '📦',
    color: '#FF9900',
    eligibility: '7+ CGPA preferred, strong DSA required.',
    package: '21 - 45 LPA (SDE-1)',
    rounds: ['Online Assessment', 'Coding Round', 'Technical Interview x2-3', 'Bar Raiser', 'HR'],
    duration: '2 - 3 months',
    prepTime: '6 - 8 months',
    skills: ['DSA expert', 'System Design basics', 'OOP', 'Database', 'Leadership Principles'],
    tips: [
      'Practice 300+ LeetCode problems minimum',
      'Master Amazon Leadership Principles - they ask STAR format questions',
      'Bar Raiser round is critical - prepare behavioral examples',
      'Know graphs, DP, trees, recursion deeply',
      'Bar raiser failures rejection happens often',
    ],
    resources: [
      { label: 'Amazon Leadership Principles', url: 'https://www.amazon.jobs/en/principles' },
      { label: 'LeetCode Amazon Tagged', url: 'https://leetcode.com/company/amazon/' },
    ],
  },
  {
    slug: 'google',
    name: 'Google',
    fullName: 'Google',
    tier: 'product',
    logo: '🔍',
    color: '#4285F4',
    eligibility: '8+ CGPA preferred, strong DSA + projects.',
    package: '30 - 60 LPA (SWE-1)',
    rounds: ['Online Assessment', 'Phone Screen', 'Onsite x4-5', 'Hiring Committee', 'Team Match'],
    duration: '3 - 6 months',
    prepTime: '8 - 12 months',
    skills: ['Advanced DSA', 'System Design', 'Googleyness behavioral', 'Algorithms research level'],
    tips: [
      'Practice 400+ LeetCode hard problems',
      'Read CLRS book chapters',
      'Be ready for unexpected algorithm questions',
      'System design round even for SWE-1 sometimes',
      'Googleyness round is unique - showcase curiosity',
    ],
    resources: [
      { label: 'Google Tech Dev Guide', url: 'https://techdevguide.withgoogle.com/' },
      { label: 'LeetCode Google Tagged', url: 'https://leetcode.com/company/google/' },
    ],
  },
  {
    slug: 'microsoft',
    name: 'Microsoft',
    fullName: 'Microsoft',
    tier: 'product',
    logo: '🪟',
    color: '#00A4EF',
    eligibility: '7.5+ CGPA, strong DSA.',
    package: '20 - 40 LPA (SDE-1)',
    rounds: ['Online Coding', 'Technical Interview x3', 'AS Round', 'HR'],
    duration: '2 - 3 months',
    prepTime: '6 - 8 months',
    skills: ['DSA strong', 'System Design', 'Object oriented design', 'Behavioral'],
    tips: [
      'Online coding has 2-3 problems in 90 mins',
      'AS round (As Appropriate) is the bar raiser',
      'Microsoft asks design questions even for fresher',
      'Know your projects deeply',
    ],
    resources: [
      { label: 'Microsoft Careers', url: 'https://careers.microsoft.com' },
      { label: 'LeetCode Microsoft', url: 'https://leetcode.com/company/microsoft/' },
    ],
  },
  {
    slug: 'adobe',
    name: 'Adobe',
    fullName: 'Adobe Inc',
    tier: 'product',
    logo: '🅰️',
    color: '#FA0F00',
    eligibility: '7+ CGPA, strong CS fundamentals.',
    package: '18 - 35 LPA (MTS)',
    rounds: ['Online Test', 'Technical Interview x2-3', 'Hiring Manager', 'HR'],
    duration: '2 months',
    prepTime: '5 - 6 months',
    skills: ['DSA', 'CS Core (OS, DBMS, CN)', 'Web/App tech as per role'],
    tips: [
      'CS Core is given equal weight as DSA',
      'Practice graph and tree problems',
      'Know operating system internals',
      'Behavioral focuses on creativity',
    ],
    resources: [
      { label: 'Adobe Interview Prep', url: 'https://www.geeksforgeeks.org/adobe-interview-experience/' },
    ],
  },
  {
    slug: 'flipkart',
    name: 'Flipkart',
    fullName: 'Flipkart',
    tier: 'product',
    logo: '🛒',
    color: '#FFCD00',
    eligibility: '7+ CGPA, strong DSA.',
    package: '21 - 45 LPA (SDE-1)',
    rounds: ['Online Coding', 'Machine Coding (Project)', 'Technical x2', 'Hiring Manager'],
    duration: '2 - 3 months',
    prepTime: '6 months',
    skills: ['DSA', 'OOP / LLD', 'System Design basics', 'Project building under time'],
    tips: [
      'Machine coding round is unique - 90 min to build a working project',
      'Practice LLD problems like parking lot, library system',
      'Know SOLID principles',
      'Code quality matters as much as correctness',
    ],
    resources: [
      { label: 'Flipkart Machine Coding', url: 'https://github.com/prateek27/machine-coding-problems' },
    ],
  },
  {
    slug: 'zomato',
    name: 'Zomato',
    fullName: 'Zomato',
    tier: 'startup',
    logo: '🍔',
    color: '#E23744',
    eligibility: 'No CGPA bar, skills based.',
    package: '15 - 30 LPA (SDE-1)',
    rounds: ['Online Test', 'Technical Interview x2', 'Manager Round', 'CTO/HR'],
    duration: '1 - 2 months',
    prepTime: '4 - 6 months',
    skills: ['DSA medium', 'System Design basics', 'Web stack (React/Node) or Backend (Java/Go)'],
    tips: [
      'Startup pace - rounds happen quick',
      'Real world problem solving valued',
      'Show passion for product',
      'Know basics of distributed systems',
    ],
    resources: [
      { label: 'Zomato Engineering Blog', url: 'https://blog.zomato.com/category/technology' },
    ],
  },
  {
    slug: 'swiggy',
    name: 'Swiggy',
    fullName: 'Swiggy',
    tier: 'startup',
    logo: '🛵',
    color: '#FC8019',
    eligibility: 'Skills based, projects matter.',
    package: '14 - 28 LPA (SDE-1)',
    rounds: ['Online Coding', 'Technical x2', 'System Design', 'HR'],
    duration: '1 - 2 months',
    prepTime: '4 - 6 months',
    skills: ['DSA medium-hard', 'System Design', 'Microservices basics'],
    tips: [
      'System design round even for fresher SDE-1',
      'Know event driven architectures',
      'Real projects on resume help a lot',
      'Be ready to draw architecture diagrams',
    ],
    resources: [
      { label: 'Swiggy Tech Bytes', url: 'https://bytes.swiggy.com/' },
    ],
  },
  {
    slug: 'accenture',
    name: 'Accenture',
    fullName: 'Accenture',
    tier: 'service',
    logo: '🅰️',
    color: '#A100FF',
    eligibility: '60% throughout, no backlogs.',
    package: '4.5 - 6.5 LPA (Associate Software Engineer)',
    rounds: ['Cognitive Test', 'Technical Test', 'Communication Test', 'HR Interview'],
    duration: '1 - 2 months',
    prepTime: '2 - 3 months',
    skills: ['Aptitude', 'Logical Reasoning', 'Basic Coding', 'English'],
    tips: [
      'Communication test is unique - speak clearly with confidence',
      'Cognitive section has 50+ questions',
      'Coding is basic - just C/Java/Python syntax',
      'Be friendly in HR round',
    ],
    resources: [
      { label: 'Accenture Prep', url: 'https://prepinsta.com/accenture/' },
    ],
  },
  {
    slug: 'cognizant',
    name: 'Cognizant',
    fullName: 'Cognizant Technology Solutions',
    tier: 'service',
    logo: '☁️',
    color: '#1976D2',
    eligibility: '60% throughout, max 1 year gap.',
    package: '4 - 9 LPA (GenC vs GenC Next)',
    rounds: ['Online Aptitude', 'Coding Test', 'Technical Interview', 'HR Interview'],
    duration: '1.5 - 2 months',
    prepTime: '2 - 3 months',
    skills: ['Aptitude', 'OOP', 'DBMS', 'Basic Coding'],
    tips: [
      'GenC Next pays much better - aim for it',
      'SQL queries appear in coding round',
      'Be ready to explain college projects',
      'Career goals question is asked frequently',
    ],
    resources: [
      { label: 'Cognizant Prep', url: 'https://prepinsta.com/cognizant/' },
    ],
  },
  {
    slug: 'capgemini',
    name: 'Capgemini',
    fullName: 'Capgemini',
    tier: 'service',
    logo: '🅒',
    color: '#0070AD',
    eligibility: '60% throughout, no current backlogs.',
    package: '4.25 - 7.5 LPA',
    rounds: ['Online Test', 'Game-based Round', 'Technical + HR Interview'],
    duration: '1 - 1.5 months',
    prepTime: '2 months',
    skills: ['Aptitude', 'Pseudocode', 'Communication', 'Basic Tech'],
    tips: [
      'Pseudocode section is unique - practice it',
      'Game based round tests problem solving',
      'Combined Tech+HR round - be balanced',
    ],
    resources: [
      { label: 'Capgemini Prep', url: 'https://prepinsta.com/capgemini/' },
    ],
  },
  {
    slug: 'hcl',
    name: 'HCL',
    fullName: 'HCLTech',
    tier: 'service',
    logo: '🔷',
    color: '#0F9D58',
    eligibility: '60% throughout for most roles.',
    package: '3.5 - 6 LPA (TechBee vs Direct)',
    rounds: ['Aptitude Test', 'Technical Interview', 'HR'],
    duration: '1 month',
    prepTime: '1 - 2 months',
    skills: ['Aptitude', 'Basic Coding', 'Communication'],
    tips: [
      'TechBee is for 12th pass - earn while learn',
      'Direct hiring needs strong tech basics',
      'Aptitude has decent difficulty',
    ],
    resources: [
      { label: 'HCL Hiring', url: 'https://www.hcltech.com/careers' },
    ],
  },
  {
    slug: 'tech-mahindra',
    name: 'Tech Mahindra',
    fullName: 'Tech Mahindra',
    tier: 'service',
    logo: '⛰️',
    color: '#E2231A',
    eligibility: '60% throughout, no backlogs.',
    package: '3.25 - 5.5 LPA',
    rounds: ['Aptitude', 'Technical', 'HR'],
    duration: '1 - 1.5 months',
    prepTime: '2 months',
    skills: ['Aptitude', 'Basic OOP', 'Communication'],
    tips: [
      'Easier than top service companies',
      'Focus on aptitude and English',
      'Project explanation is important',
    ],
    resources: [
      { label: 'TechM Prep', url: 'https://prepinsta.com/tech-mahindra/' },
    ],
  },
];

export const TIER_LABELS = {
  service: 'Service-Based',
  product: 'Product-Based',
  startup: 'Startup',
};
