export const ALL_DOMAINS = [
  {
    slug: 'fullstack',
    name: 'Full Stack Development',
    icon: '⬡',
    color: '#90dfab',
    hot: true,
    shortDesc: 'Build complete web apps end-to-end',
    longDesc: 'Full Stack developers build both frontend and backend. The most in-demand role in India with highest open positions.',
    stack: ['React', 'Node.js', 'MongoDB', 'Next.js', 'TypeScript'],
    careers: ['Full Stack Developer', 'MERN Developer', 'Software Engineer'],
    companies: ['Swiggy', 'Zomato', 'Flipkart', 'Razorpay', 'CRED'],
    packages: { entry: '6-12 LPA', mid: '15-28 LPA', senior: '30-60 LPA' },
    demand: 'Very High',
    difficulty: 'Medium',
    timeToJob: '4-6 months',
    whoShould: 'You love building things end-to-end. You want fastest path to a job.',
  },
  {
    slug: 'dsa',
    name: 'DSA & Problem Solving',
    icon: '◈',
    color: '#1aa255',
    hot: true,
    shortDesc: 'Crack top product company interviews',
    longDesc: 'Master Data Structures and Algorithms to crack interviews at Google, Amazon, Microsoft. The foundation of all product company hiring.',
    stack: ['C++', 'Java', 'Python', 'LeetCode', 'System Design Basics'],
    careers: ['SDE Role at Product Companies', 'Competitive Programmer'],
    companies: ['Google', 'Amazon', 'Microsoft', 'Meta', 'Uber'],
    packages: { entry: '15-30 LPA', mid: '30-60 LPA', senior: '60-150 LPA' },
    demand: 'Very High',
    difficulty: 'Hard',
    timeToJob: '6-9 months',
    whoShould: 'You want high package product company jobs. You can grind daily for months.',
  },
  {
    slug: 'ml',
    name: 'Machine Learning',
    icon: '◉',
    color: '#9eedc8',
    hot: true,
    shortDesc: 'Build predictive models and ML systems',
    longDesc: 'Use Python and frameworks to build models that predict, classify, and recommend. High demand in fintech and e-commerce.',
    stack: ['Python', 'Scikit-learn', 'Pandas', 'NumPy', 'TensorFlow'],
    careers: ['ML Engineer', 'Data Scientist', 'ML Researcher'],
    companies: ['Google', 'Meta', 'Paytm', 'Razorpay', 'Flipkart'],
    packages: { entry: '10-18 LPA', mid: '20-40 LPA', senior: '50-80 LPA' },
    demand: 'High',
    difficulty: 'Hard',
    timeToJob: '6-10 months',
    whoShould: 'You love math and data. You want to build AI systems.',
  },
  {
    slug: 'ai',
    name: 'AI & LLM Engineering',
    icon: '◎',
    color: '#14b87c',
    hot: true,
    shortDesc: 'Build GPT, Claude, and AI products',
    longDesc: 'The hottest field in tech. Build chatbots, RAG systems, AI agents, and LLM applications. Massively growing.',
    stack: ['Python', 'LangChain', 'OpenAI API', 'Anthropic API', 'Vector DBs'],
    careers: ['AI Engineer', 'LLM Developer', 'AI Product Engineer'],
    companies: ['OpenAI', 'Anthropic', 'Microsoft', 'Google', 'Startups'],
    packages: { entry: '12-25 LPA', mid: '25-50 LPA', senior: '60-120 LPA' },
    demand: 'Explosive',
    difficulty: 'Medium',
    timeToJob: '3-6 months',
    whoShould: 'You want to be at the frontier. AI-first career.',
  },
  {
    slug: 'ds',
    name: 'Data Science',
    icon: '◇',
    color: '#bcebc7',
    shortDesc: 'Turn data into business insights',
    longDesc: 'Analyze data, build dashboards, create predictions. Every company needs data scientists now.',
    stack: ['Python', 'SQL', 'Tableau', 'Power BI', 'Statistics'],
    careers: ['Data Scientist', 'Data Analyst', 'BI Analyst'],
    companies: ['Swiggy', 'Zomato', 'Flipkart', 'Amazon', 'Banks'],
    packages: { entry: '8-15 LPA', mid: '18-35 LPA', senior: '40-70 LPA' },
    demand: 'High',
    difficulty: 'Medium',
    timeToJob: '5-8 months',
    whoShould: 'You love numbers and storytelling with data.',
  },
  {
    slug: 'cybersec',
    name: 'Cybersecurity',
    icon: '◆',
    color: '#1fbd49',
    hot: true,
    shortDesc: 'Protect systems from hackers',
    longDesc: 'Ethical hacking, penetration testing, security analysis. Extreme shortage of security engineers in India.',
    stack: ['Kali Linux', 'Python', 'Networking', 'OWASP', 'Burp Suite'],
    careers: ['Security Analyst', 'Penetration Tester', 'SOC Engineer'],
    companies: ['EY', 'Deloitte', 'Wipro', 'TCS Cyber', 'Cisco'],
    packages: { entry: '6-12 LPA', mid: '15-30 LPA', senior: '35-70 LPA' },
    demand: 'Very High',
    difficulty: 'Medium',
    timeToJob: '4-7 months',
    whoShould: 'You love breaking things to understand how they work.',
  },
  {
    slug: 'cloud',
    name: 'Cloud Engineering',
    icon: '○',
    color: '#86e9c8',
    shortDesc: 'Master AWS, Azure, GCP',
    longDesc: 'Deploy and manage cloud infrastructure. Every company is moving to cloud. High demand certifications.',
    stack: ['AWS', 'Azure', 'Terraform', 'Kubernetes', 'Linux'],
    careers: ['Cloud Engineer', 'Cloud Architect', 'DevOps Cloud'],
    companies: ['Amazon', 'Microsoft', 'Accenture', 'Infosys', 'TCS'],
    packages: { entry: '8-15 LPA', mid: '20-40 LPA', senior: '45-90 LPA' },
    demand: 'Very High',
    difficulty: 'Medium',
    timeToJob: '4-6 months',
    whoShould: 'You want to manage infrastructure at scale.',
  },
  {
    slug: 'mobile',
    name: 'Mobile Development',
    icon: '▣',
    color: '#13aa68',
    shortDesc: 'Build iOS and Android apps',
    longDesc: 'Create mobile apps that millions use. React Native and Flutter are most in demand.',
    stack: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase'],
    careers: ['Mobile Developer', 'iOS Developer', 'Android Developer'],
    companies: ['Paytm', 'PhonePe', 'Zomato', 'Uber', 'Swiggy'],
    packages: { entry: '7-14 LPA', mid: '16-32 LPA', senior: '35-65 LPA' },
    demand: 'High',
    difficulty: 'Medium',
    timeToJob: '4-6 months',
    whoShould: 'You want your code in millions of pockets.',
  },
  {
    slug: 'devops',
    name: 'DevOps',
    icon: '▷',
    color: '#a6e5c1',
    shortDesc: 'Automate deployment and infrastructure',
    longDesc: 'Bridge between developers and operations. CI/CD, Docker, Kubernetes. Massive salary potential.',
    stack: ['Docker', 'Kubernetes', 'Jenkins', 'AWS', 'Terraform'],
    careers: ['DevOps Engineer', 'SRE', 'Platform Engineer'],
    companies: ['Netflix', 'Amazon', 'Flipkart', 'Razorpay', 'Startups'],
    packages: { entry: '8-16 LPA', mid: '20-40 LPA', senior: '45-90 LPA' },
    demand: 'Very High',
    difficulty: 'Medium',
    timeToJob: '5-8 months',
    whoShould: 'You love automation and infrastructure.',
  },
  {
    slug: 'sysdesign',
    name: 'System Design',
    icon: '▦',
    color: '#1daf57',
    shortDesc: 'Design Instagram, Uber, Netflix',
    longDesc: 'The skill that separates junior from senior engineers. Design scalable systems.',
    stack: ['Scalability', 'Microservices', 'Caching', 'Databases', 'Load Balancing'],
    careers: ['Senior Software Engineer', 'Staff Engineer', 'Architect'],
    companies: ['Google', 'Amazon', 'Meta', 'Netflix', 'Uber'],
    packages: { entry: 'Senior role', mid: '40-80 LPA', senior: '80-150 LPA' },
    demand: 'High',
    difficulty: 'Very Hard',
    timeToJob: '6-12 months',
    whoShould: 'You are already a developer and want senior roles.',
  },

  {
    slug: 'gamedev',
    name: 'Game Development',
    icon: '◐',
    color: '#b6f2dc',
    shortDesc: 'Build games that millions play',
    longDesc: 'Indie game dev, AAA studios, or mobile games. Growing industry in India with Nodwin, Krafton, etc.',
    stack: ['Unity', 'C#', 'Unreal Engine', 'C++', 'Blender'],
    careers: ['Game Developer', 'Unity Developer', 'Technical Artist'],
    companies: ['Krafton', 'Nodwin Gaming', 'Dream11', 'Zynga India', 'Ubisoft'],
    packages: { entry: '6-12 LPA', mid: '15-28 LPA', senior: '30-60 LPA' },
    demand: 'Medium',
    difficulty: 'Hard',
    timeToJob: '6-10 months',
    whoShould: 'You are passionate about games and want to build them.',
  },
  {
    slug: 'blockchain',
    name: 'Blockchain & Web3',
    icon: '◑',
    color: '#16c591',
    shortDesc: 'Build DeFi, NFTs, Smart Contracts',
    longDesc: 'Web3 is rebuilding the internet. Very high salaries, remote work, global opportunities.',
    stack: ['Solidity', 'Ethereum', 'Web3.js', 'Rust', 'Hardhat'],
    careers: ['Blockchain Developer', 'Smart Contract Engineer', 'Web3 Engineer'],
    companies: ['Polygon', 'CoinDCX', 'WazirX', 'Global remote startups'],
    packages: { entry: '12-25 LPA', mid: '30-60 LPA', senior: '60-150 LPA' },
    demand: 'High',
    difficulty: 'Hard',
    timeToJob: '6-10 months',
    whoShould: 'You want remote global work and high salaries.',
  },
  {
    slug: 'arvr',
    name: 'AR/VR Development',
    icon: '◒',
    color: '#90dfa5',
    shortDesc: 'Build immersive experiences',
    longDesc: 'Augmented and Virtual Reality. Apple Vision Pro, Meta Quest. Growing industry.',
    stack: ['Unity', 'Unreal', 'C#', 'ARKit', 'WebXR'],
    careers: ['AR/VR Developer', 'XR Engineer', 'Immersive Tech Lead'],
    companies: ['Meta', 'Microsoft', 'Flipkart', 'Jio', 'Startups'],
    packages: { entry: '8-16 LPA', mid: '18-35 LPA', senior: '40-80 LPA' },
    demand: 'Growing',
    difficulty: 'Hard',
    timeToJob: '6-10 months',
    whoShould: 'You are early adopter. Want to build the future of computing.',
  },
  {
    slug: 'iot',
    name: 'IoT & Embedded',
    icon: '◓',
    color: '#1aa248',
    shortDesc: 'Program smart devices and sensors',
    longDesc: 'Internet of Things, embedded systems, hardware. Growing with smart homes and industrial IoT.',
    stack: ['C', 'C++', 'Arduino', 'Raspberry Pi', 'MQTT'],
    careers: ['Embedded Engineer', 'IoT Developer', 'Firmware Engineer'],
    companies: ['Bosch', 'Tata Elxsi', 'Intel', 'Qualcomm', 'Honeywell'],
    packages: { entry: '5-10 LPA', mid: '12-24 LPA', senior: '28-55 LPA' },
    demand: 'High',
    difficulty: 'Medium',
    timeToJob: '5-8 months',
    whoShould: 'You love hardware and software together.',
  },
  {
    slug: 'qa',
    name: 'QA & Test Automation',
    icon: '◔',
    color: '#9eedcb',
    shortDesc: 'Break software professionally',
    longDesc: 'Test automation, manual testing, performance testing. Every software company needs QA.',
    stack: ['Selenium', 'Cypress', 'Jest', 'JMeter', 'Postman'],
    careers: ['QA Engineer', 'SDET', 'Automation Engineer'],
    companies: ['TCS', 'Infosys', 'Thoughtworks', 'Accenture', 'Microsoft'],
    packages: { entry: '5-10 LPA', mid: '12-22 LPA', senior: '25-50 LPA' },
    demand: 'High',
    difficulty: 'Easy',
    timeToJob: '3-5 months',
    whoShould: 'You have attention to detail. Want faster route to a job.',
  },
  {
    slug: 'uiux',
    name: 'UI/UX Design',
    icon: '◕',
    color: '#14b86b',
    shortDesc: 'Design beautiful products',
    longDesc: 'User interface and experience design. High demand with growing tech industry.',
    stack: ['Figma', 'Adobe XD', 'Prototyping', 'User Research', 'Design Systems'],
    careers: ['UI Designer', 'UX Designer', 'Product Designer'],
    companies: ['CRED', 'Razorpay', 'Swiggy', 'Zomato', 'Flipkart'],
    packages: { entry: '5-12 LPA', mid: '15-30 LPA', senior: '35-65 LPA' },
    demand: 'High',
    difficulty: 'Medium',
    timeToJob: '4-6 months',
    whoShould: 'You are creative and love solving user problems.',
  },
  {
    slug: 'productmgmt',
    name: 'Product Management',
    icon: '◖',
    color: '#bcebcf',
    shortDesc: 'Lead products from idea to launch',
    longDesc: 'Decide what engineers build. Combines tech, business, design. Highest paying non-coding role.',
    stack: ['Analytics', 'User Research', 'SQL', 'Roadmapping', 'Business Strategy'],
    careers: ['Associate Product Manager', 'Product Manager', 'Sr PM'],
    companies: ['Flipkart', 'Amazon', 'Google', 'Swiggy', 'Razorpay'],
    packages: { entry: '15-25 LPA', mid: '30-60 LPA', senior: '70-150 LPA' },
    demand: 'High',
    difficulty: 'Hard',
    timeToJob: '8-12 months',
    whoShould: 'You are strategic thinker. Engineering plus business mindset.',
  },
  {
    slug: 'dataeng',
    name: 'Data Engineering',
    icon: '◗',
    color: '#1fbd44',
    shortDesc: 'Build data pipelines at scale',
    longDesc: 'ETL pipelines, data warehouses, big data. High demand, very high pay.',
    stack: ['Python', 'SQL', 'Spark', 'Airflow', 'Snowflake'],
    careers: ['Data Engineer', 'Analytics Engineer', 'Big Data Engineer'],
    companies: ['Netflix', 'Uber', 'Swiggy', 'Flipkart', 'Banks'],
    packages: { entry: '10-18 LPA', mid: '22-45 LPA', senior: '50-90 LPA' },
    demand: 'Very High',
    difficulty: 'Medium',
    timeToJob: '5-8 months',
    whoShould: 'You love data infrastructure at scale.',
  },
  {
    slug: 'robotics',
    name: 'Robotics Engineering',
    icon: '◘',
    color: '#86e9cb',
    shortDesc: 'Build autonomous robots and drones',
    longDesc: 'Robotics, automation, drones. Growing with manufacturing and Industry 4.0.',
    stack: ['ROS', 'Python', 'C++', 'Computer Vision', 'Sensors'],
    careers: ['Robotics Engineer', 'Automation Engineer', 'Drone Developer'],
    companies: ['Swiggy Instamart', 'Ola Electric', 'Tata', 'Boston Dynamics', 'Bosch'],
    packages: { entry: '8-15 LPA', mid: '18-35 LPA', senior: '40-75 LPA' },
    demand: 'Growing',
    difficulty: 'Hard',
    timeToJob: '6-10 months',
    whoShould: 'You love mechanical plus software plus AI.',
  },
  {
    slug: 'quantdev',
    name: 'Quantitative Development',
    icon: '◙',
    color: '#13aa78',
    shortDesc: 'Code for trading firms',
    longDesc: 'Build trading systems, algorithmic trading. Highest paying field, mostly in finance.',
    stack: ['C++', 'Python', 'Math', 'Finance', 'Low Latency'],
    careers: ['Quant Developer', 'Algo Trader', 'HFT Engineer'],
    companies: ['Morgan Stanley', 'Citadel', 'Tower Research', 'Quadeye', 'AQR'],
    packages: { entry: '25-50 LPA', mid: '50-100 LPA', senior: '100-300 LPA' },
    demand: 'Medium',
    difficulty: 'Extreme',
    timeToJob: '9-15 months',
    whoShould: 'You are math+coding genius. Want highest salaries in the world.',
  },
];

export const DOMAIN_CATEGORIES = [
  { slug: 'all', label: 'All Domains', count: ALL_DOMAINS.length },
  { slug: 'hot', label: '🔥 Hot', filter: d => d.hot },
  { slug: 'high-pay', label: '💰 High Pay', filter: d => parseInt(d.packages.entry) >= 10 },
  { slug: 'fast-job', label: '⚡ Fast to Job', filter: d => d.timeToJob.includes('3-') || d.timeToJob.includes('4-') },
  { slug: 'easy', label: '🌱 Easier Start', filter: d => d.difficulty === 'Easy' || d.difficulty === 'Medium' },
];
