export const DSA_CURRICULUM = [
  // Week 1 — Arrays Foundation
  { day: 1, week: 1, topic: 'Arrays Introduction & Basics', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=Fl_Bt5KXaI8', videoTitle: 'Arrays in DSA - Striver', resource: 'https://takeuforward.org/arrays/introduction-to-arrays/', resourceTitle: 'Arrays Introduction Guide', codingProblem: 'Given an array of integers, find the largest element. Also find the smallest element.', testTopic: 'Array basics, indexing, length operations', notesTopic: 'Array fundamentals cheatsheet' },
  { day: 2, week: 1, topic: 'Array Traversal & Searching', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=f6UU7V3szVw', videoTitle: 'Linear Search Algorithm', resource: 'https://www.geeksforgeeks.org/linear-search/', resourceTitle: 'Linear Search Guide', codingProblem: 'Implement linear search to find a target element. Return its index or -1.', testTopic: 'Linear search time complexity, iteration', notesTopic: 'Searching algorithms basics' },
  { day: 3, week: 1, topic: 'Binary Search', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=MHf6awe89xw', videoTitle: 'Binary Search Striver', resource: 'https://takeuforward.org/data-structure/binary-search-explained/', resourceTitle: 'Binary Search Guide', codingProblem: 'Implement binary search on a sorted array. Return index of target.', testTopic: 'Binary search, O(log n), divide and conquer', notesTopic: 'Binary search patterns' },
  { day: 4, week: 1, topic: 'Two Pointers Technique', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=On03HWe2tZM', videoTitle: 'Two Pointers Pattern', resource: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', resourceTitle: 'Two Sum II Problem', codingProblem: 'Given sorted array, find two numbers that sum to target. Return indices.', testTopic: 'Two pointer technique, O(n) approaches', notesTopic: 'Two pointer patterns' },
  { day: 5, week: 1, topic: 'Sliding Window Basics', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=EHCGAZBbB88', videoTitle: 'Sliding Window Maximum', resource: 'https://takeuforward.org/sliding-window/sliding-window-template/', resourceTitle: 'Sliding Window Template', codingProblem: 'Find maximum sum of contiguous subarray of size k.', testTopic: 'Sliding window, fixed and variable windows', notesTopic: 'Sliding window template' },
  { day: 6, week: 1, topic: 'Array Reversal & Rotation', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=wvcQg43_V8U', videoTitle: 'Array Rotation', resource: 'https://leetcode.com/problems/rotate-array/', resourceTitle: 'Rotate Array Problem', codingProblem: 'Rotate array by k positions. In-place with O(1) extra space.', testTopic: 'Array manipulation, rotation techniques', notesTopic: 'Array rotation algorithms' },
  { day: 7, week: 1, topic: 'Week 1 Review & Practice', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=37E9ckMDdTk', videoTitle: 'Array Patterns Summary', resource: 'https://takeuforward.org/arrays/arrays-easy-problems/', resourceTitle: 'Array Easy Problems', codingProblem: 'Solve 3 array problems: reverse in place, find missing number, find duplicates.', testTopic: 'Arrays comprehensive review', notesTopic: 'Week 1 cheatsheet' },

  // Week 2 — Hashing
  { day: 8, week: 2, topic: 'Hash Maps Introduction', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=KyUTuwz_b7Q', videoTitle: 'HashMap Fundamentals', resource: 'https://leetcode.com/problems/two-sum/', resourceTitle: 'Two Sum Problem', codingProblem: 'Classic Two Sum: return indices of two numbers that add to target.', testTopic: 'Hashmap basics, O(1) lookups', notesTopic: 'HashMap fundamentals' },
  { day: 9, week: 2, topic: 'Frequency Counting', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=lBH9mvKKFZc', videoTitle: 'Frequency Counter Pattern', resource: 'https://leetcode.com/problems/valid-anagram/', resourceTitle: 'Valid Anagram', codingProblem: 'Check if two strings are anagrams using frequency map.', testTopic: 'Frequency counting, character maps', notesTopic: 'Frequency counter technique' },
  { day: 10, week: 2, topic: 'Hash Sets', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=zIin5q6Q_z0', videoTitle: 'HashSet vs HashMap', resource: 'https://leetcode.com/problems/contains-duplicate/', resourceTitle: 'Contains Duplicate', codingProblem: 'Check if array contains any duplicates.', testTopic: 'Hash sets, unique elements', notesTopic: 'HashSet patterns' },
  { day: 11, week: 2, topic: 'Subarray Sum Problems', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=xvNwoz-ufXA', videoTitle: 'Subarray Sum Equals K', resource: 'https://leetcode.com/problems/subarray-sum-equals-k/', resourceTitle: 'Subarray Sum = K', codingProblem: 'Count number of subarrays with sum equal to k.', testTopic: 'Prefix sums with hashmap', notesTopic: 'Subarray sum patterns' },
  { day: 12, week: 2, topic: 'Group Anagrams Pattern', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=vzdNOK2oB2E', videoTitle: 'Group Anagrams', resource: 'https://leetcode.com/problems/group-anagrams/', resourceTitle: 'Group Anagrams Problem', codingProblem: 'Group strings that are anagrams of each other.', testTopic: 'Grouping with hash keys', notesTopic: 'Group-by pattern' },
  { day: 13, week: 2, topic: 'Longest Substring Without Repeat', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=wiGpQwVHdE0', videoTitle: 'Longest Substring Without Repeating', resource: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', resourceTitle: 'LeetCode Problem', codingProblem: 'Find length of longest substring without repeating characters.', testTopic: 'Sliding window with hashmap', notesTopic: 'Substring problems' },
  { day: 14, week: 2, topic: 'Week 2 Review', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=KEs5UyBJ39g', videoTitle: 'Hashing Patterns Review', resource: 'https://takeuforward.org/hashing/', resourceTitle: 'Hashing Problems Sheet', codingProblem: 'Solve 3 hashing problems of varying difficulty.', testTopic: 'Hashing comprehensive', notesTopic: 'Week 2 cheatsheet' },

  // Week 3 — Linked Lists
  { day: 15, week: 3, topic: 'Linked List Basics', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=NobHlGUjV3g', videoTitle: 'Linked List Introduction', resource: 'https://takeuforward.org/data-structure/introduction-to-linked-list/', resourceTitle: 'Linked List Guide', codingProblem: 'Implement singly linked list with insert, delete, print methods.', testTopic: 'Linked list structure, pointers', notesTopic: 'Linked list fundamentals' },
  { day: 16, week: 3, topic: 'Reverse Linked List', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=iRtLEoL-r-g', videoTitle: 'Reverse Linked List', resource: 'https://leetcode.com/problems/reverse-linked-list/', resourceTitle: 'Reverse Linked List', codingProblem: 'Reverse a singly linked list iteratively and recursively.', testTopic: 'Pointer manipulation', notesTopic: 'Reversal patterns' },
  { day: 17, week: 3, topic: 'Cycle Detection (Floyd)', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=-YiQZi3mLq0', videoTitle: 'Floyd Cycle Detection', resource: 'https://leetcode.com/problems/linked-list-cycle/', resourceTitle: 'Linked List Cycle', codingProblem: 'Detect if linked list has a cycle using slow/fast pointers.', testTopic: 'Floyd algorithm, slow fast pointer', notesTopic: 'Cycle detection' },
  { day: 18, week: 3, topic: 'Merge Two Sorted Lists', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=GfRQvf7MB3k', videoTitle: 'Merge Two Sorted Lists', resource: 'https://leetcode.com/problems/merge-two-sorted-lists/', resourceTitle: 'Merge Sorted Lists', codingProblem: 'Merge two sorted linked lists into one sorted list.', testTopic: 'Merging lists, dummy node pattern', notesTopic: 'List merging' },
  { day: 19, week: 3, topic: 'Middle of Linked List', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=7LjQ57RqgEc', videoTitle: 'Middle of Linked List', resource: 'https://leetcode.com/problems/middle-of-the-linked-list/', resourceTitle: 'LC Problem', codingProblem: 'Find middle of linked list in single pass.', testTopic: 'Two pointer on linked lists', notesTopic: 'Middle finding' },
  { day: 20, week: 3, topic: 'Remove Nth Node From End', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=Lhu3MsXZy-Q', videoTitle: 'Remove Nth From End', resource: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', resourceTitle: 'Remove Nth Problem', codingProblem: 'Remove Nth node from end in one pass.', testTopic: 'Two pointer with gap', notesTopic: 'Remove node patterns' },
  { day: 21, week: 3, topic: 'Week 3 Review', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=58YbpRDc4yw', videoTitle: 'Linked List Summary', resource: 'https://takeuforward.org/linked-list/', resourceTitle: 'Linked List Sheet', codingProblem: 'Solve 3 linked list problems.', testTopic: 'Linked list comprehensive', notesTopic: 'Week 3 cheatsheet' },

  // Weeks 4-12 continue same pattern - add 63 more days
  { day: 22, week: 4, topic: 'Stack Basics & Operations', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=PGWZUgzDMYI', videoTitle: 'Stack Introduction', resource: 'https://takeuforward.org/data-structure/implement-stack-using-arrays/', resourceTitle: 'Stack Implementation', codingProblem: 'Implement stack using array with push, pop, top, empty.', testTopic: 'Stack LIFO principle', notesTopic: 'Stack fundamentals' },
  { day: 23, week: 4, topic: 'Valid Parentheses', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=WQoB2z67hvY', videoTitle: 'Valid Parentheses', resource: 'https://leetcode.com/problems/valid-parentheses/', resourceTitle: 'Valid Parentheses LC', codingProblem: 'Check if string of brackets is valid using stack.', testTopic: 'Stack for matching', notesTopic: 'Bracket matching' },
  { day: 24, week: 4, topic: 'Monotonic Stack', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=Du881K7Jtk8', videoTitle: 'Monotonic Stack', resource: 'https://leetcode.com/problems/next-greater-element-i/', resourceTitle: 'Next Greater Element', codingProblem: 'Find next greater element for each element in array.', testTopic: 'Monotonic stack technique', notesTopic: 'Monotonic patterns' },
  { day: 25, week: 4, topic: 'Queue Basics', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=3Et9MrMc02A', videoTitle: 'Queue Introduction', resource: 'https://takeuforward.org/data-structure/implement-queue-using-array/', resourceTitle: 'Queue Implementation', codingProblem: 'Implement queue using array with enqueue, dequeue.', testTopic: 'Queue FIFO', notesTopic: 'Queue fundamentals' },
  { day: 26, week: 4, topic: 'Priority Queue Basics', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=9fDeZ4uwJXM', videoTitle: 'Priority Queue', resource: 'https://www.geeksforgeeks.org/priority-queue-set-1-introduction/', resourceTitle: 'Priority Queue Guide', codingProblem: 'Find Kth largest element using priority queue.', testTopic: 'Heaps basics, min/max heaps', notesTopic: 'Priority queue patterns' },
  { day: 27, week: 4, topic: 'Sliding Window Maximum', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=CZQGRp93K4k', videoTitle: 'Sliding Window Maximum Deque', resource: 'https://leetcode.com/problems/sliding-window-maximum/', resourceTitle: 'Sliding Window Max', codingProblem: 'Find maximum in each sliding window of size k.', testTopic: 'Deque, sliding window optimal', notesTopic: 'Window max patterns' },
  { day: 28, week: 4, topic: 'Week 4 Review', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=MEZHhFAIypI', videoTitle: 'Stack Queue Summary', resource: 'https://takeuforward.org/stack-and-queue/', resourceTitle: 'Stack Queue Sheet', codingProblem: 'Solve 3 mixed problems.', testTopic: 'Stack queue comprehensive', notesTopic: 'Week 4 cheatsheet' },

  // Week 5 - Recursion & Backtracking
  { day: 29, week: 5, topic: 'Recursion Fundamentals', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=M2uO2nMT0Bk', videoTitle: 'Recursion Basics', resource: 'https://takeuforward.org/recursion/introduction-to-recursion/', resourceTitle: 'Recursion Intro', codingProblem: 'Print numbers 1 to N using recursion. Print sum using recursion.', testTopic: 'Base case, recursive case', notesTopic: 'Recursion fundamentals' },
  { day: 30, week: 5, topic: 'Factorial & Fibonacci', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=yVd3yYh_3Pw', videoTitle: 'Factorial Fibonacci', resource: 'https://www.geeksforgeeks.org/program-for-factorial-of-a-number/', resourceTitle: 'Factorial Guide', codingProblem: 'Calculate factorial and Nth Fibonacci recursively.', testTopic: 'Simple recursion problems', notesTopic: 'Math recursion' },
  { day: 31, week: 5, topic: 'Subset Generation', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=AxNNVECce8c', videoTitle: 'Power Set Recursion', resource: 'https://leetcode.com/problems/subsets/', resourceTitle: 'Subsets Problem', codingProblem: 'Generate all subsets of a set using recursion.', testTopic: 'Include exclude pattern', notesTopic: 'Subset generation' },
  { day: 32, week: 5, topic: 'Permutations', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=YyRYxTvbcT8', videoTitle: 'All Permutations', resource: 'https://leetcode.com/problems/permutations/', resourceTitle: 'Permutations LC', codingProblem: 'Generate all permutations of an array.', testTopic: 'Swapping pattern', notesTopic: 'Permutation generation' },
  { day: 33, week: 5, topic: 'N-Queens Backtracking', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=i05Ju7AftcM', videoTitle: 'N-Queens Solution', resource: 'https://leetcode.com/problems/n-queens/', resourceTitle: 'N-Queens LC', codingProblem: 'Solve N-Queens problem for given n.', testTopic: 'Backtracking pattern', notesTopic: 'N-Queens approach' },
  { day: 34, week: 5, topic: 'Sudoku Solver', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=FWAIf_EVUKE', videoTitle: 'Sudoku Solver', resource: 'https://leetcode.com/problems/sudoku-solver/', resourceTitle: 'Sudoku LC', codingProblem: 'Solve 9x9 Sudoku using backtracking.', testTopic: 'Constraint satisfaction', notesTopic: 'Sudoku patterns' },
  { day: 35, week: 5, topic: 'Week 5 Review', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=4s6Yi-zSK00', videoTitle: 'Recursion Summary', resource: 'https://takeuforward.org/recursion/', resourceTitle: 'Recursion Sheet', codingProblem: 'Solve 3 recursion problems.', testTopic: 'Recursion comprehensive', notesTopic: 'Week 5 cheatsheet' },

  // Week 6 - Trees
  { day: 36, week: 6, topic: 'Binary Tree Basics', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=_ANrF3FJm7I', videoTitle: 'Binary Tree Intro', resource: 'https://takeuforward.org/data-structure/binary-tree-representation-in-c/', resourceTitle: 'Binary Tree Guide', codingProblem: 'Create binary tree and print all nodes.', testTopic: 'Tree structure, nodes', notesTopic: 'Tree basics' },
  { day: 37, week: 6, topic: 'Tree Traversals (DFS)', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=jmy0LaGET1I', videoTitle: 'Tree Traversals', resource: 'https://leetcode.com/problems/binary-tree-inorder-traversal/', resourceTitle: 'Inorder Traversal', codingProblem: 'Implement inorder, preorder, postorder traversals.', testTopic: 'DFS on trees', notesTopic: 'Tree traversal patterns' },
  { day: 38, week: 6, topic: 'Level Order Traversal (BFS)', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=EoAsWbO7sqg', videoTitle: 'Level Order BFS', resource: 'https://leetcode.com/problems/binary-tree-level-order-traversal/', resourceTitle: 'Level Order LC', codingProblem: 'Level order traversal using queue.', testTopic: 'BFS with queue', notesTopic: 'BFS on trees' },
  { day: 39, week: 6, topic: 'Height & Depth of Tree', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=eD3tmO66aBA', videoTitle: 'Tree Height', resource: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', resourceTitle: 'Max Depth LC', codingProblem: 'Find max depth of binary tree.', testTopic: 'Recursion on trees', notesTopic: 'Tree metrics' },
  { day: 40, week: 6, topic: 'Binary Search Tree (BST)', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=p7-9UvDQZ3w', videoTitle: 'BST Intro', resource: 'https://takeuforward.org/binary-search-tree/introduction-to-binary-search-tree/', resourceTitle: 'BST Guide', codingProblem: 'Implement BST with insert, search, delete.', testTopic: 'BST properties', notesTopic: 'BST operations' },
  { day: 41, week: 6, topic: 'LCA of Binary Tree', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=_-QHfMDde90', videoTitle: 'LCA Problem', resource: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/', resourceTitle: 'LCA LC', codingProblem: 'Find LCA of two nodes in binary tree.', testTopic: 'LCA techniques', notesTopic: 'LCA algorithms' },
  { day: 42, week: 6, topic: 'Week 6 Review', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=ROyC2qz07Eg', videoTitle: 'Trees Summary', resource: 'https://takeuforward.org/binary-tree/', resourceTitle: 'Trees Sheet', codingProblem: 'Solve 3 tree problems.', testTopic: 'Trees comprehensive', notesTopic: 'Week 6 cheatsheet' },

  // Week 7 - Heaps & Advanced Trees
  { day: 43, week: 7, topic: 'Heap Data Structure', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=Qf-TDPr0nYw', videoTitle: 'Heap Introduction', resource: 'https://www.geeksforgeeks.org/heap-data-structure/', resourceTitle: 'Heap Guide', codingProblem: 'Implement min heap with insert and extract min.', testTopic: 'Heap property, heapify', notesTopic: 'Heap fundamentals' },
  { day: 44, week: 7, topic: 'Kth Largest/Smallest', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=FrWq2rznPLQ', videoTitle: 'Kth Largest Element', resource: 'https://leetcode.com/problems/kth-largest-element-in-an-array/', resourceTitle: 'Kth Largest LC', codingProblem: 'Find Kth largest element using heap.', testTopic: 'Top K pattern', notesTopic: 'Top K patterns' },
  { day: 45, week: 7, topic: 'Merge K Sorted Lists', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=q5a5OiGbT6Q', videoTitle: 'Merge K Sorted Lists', resource: 'https://leetcode.com/problems/merge-k-sorted-lists/', resourceTitle: 'Merge K LC', codingProblem: 'Merge K sorted linked lists using heap.', testTopic: 'Heap with lists', notesTopic: 'K-way merge' },
  { day: 46, week: 7, topic: 'Top K Frequent Elements', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=YPTqKIgVk-k', videoTitle: 'Top K Frequent', resource: 'https://leetcode.com/problems/top-k-frequent-elements/', resourceTitle: 'Top K Frequent LC', codingProblem: 'Find K most frequent elements.', testTopic: 'Frequency with heap', notesTopic: 'Frequency heap' },
  { day: 47, week: 7, topic: 'Tries Introduction', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=dBGUmUQhjaM', videoTitle: 'Trie Data Structure', resource: 'https://takeuforward.org/data-structure/implement-trie-1/', resourceTitle: 'Trie Guide', codingProblem: 'Implement trie with insert, search, startsWith.', testTopic: 'Trie structure, prefix matching', notesTopic: 'Trie fundamentals' },
  { day: 48, week: 7, topic: 'Segment Trees Basics', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=ezZ87UJlCbw', videoTitle: 'Segment Tree', resource: 'https://www.geeksforgeeks.org/segment-tree-set-1-sum-of-given-range/', resourceTitle: 'Segment Tree Guide', codingProblem: 'Build segment tree for range sum queries.', testTopic: 'Segment tree operations', notesTopic: 'Segment trees' },
  { day: 49, week: 7, topic: 'Week 7 Review', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=IlVBx6j8Rgg', videoTitle: 'Heaps Summary', resource: 'https://takeuforward.org/heap/', resourceTitle: 'Heap Sheet', codingProblem: 'Solve 3 heap problems.', testTopic: 'Heaps comprehensive', notesTopic: 'Week 7 cheatsheet' },

  // Week 8 - Graphs Basics
  { day: 50, week: 8, topic: 'Graph Representation', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=OsNklbH_YsQ', videoTitle: 'Graph Introduction', resource: 'https://takeuforward.org/graph/introduction-to-graphs/', resourceTitle: 'Graph Guide', codingProblem: 'Build graph using adjacency list and matrix.', testTopic: 'Graph types, representations', notesTopic: 'Graph basics' },
  { day: 51, week: 8, topic: 'BFS Traversal', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=-tgVpUgsQ5k', videoTitle: 'BFS Algorithm', resource: 'https://takeuforward.org/graph/breadth-first-search-bfs-level-order-traversal/', resourceTitle: 'BFS Guide', codingProblem: 'Implement BFS traversal of graph.', testTopic: 'BFS with queue', notesTopic: 'BFS pattern' },
  { day: 52, week: 8, topic: 'DFS Traversal', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=Qzf1a--rhp8', videoTitle: 'DFS Algorithm', resource: 'https://takeuforward.org/data-structure/depth-first-search-dfs/', resourceTitle: 'DFS Guide', codingProblem: 'Implement DFS traversal recursively and iteratively.', testTopic: 'DFS with stack/recursion', notesTopic: 'DFS pattern' },
  { day: 53, week: 8, topic: 'Connected Components', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=ACQwqQQv_mQ', videoTitle: 'Connected Components', resource: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', resourceTitle: 'Connected Components', codingProblem: 'Count number of connected components in graph.', testTopic: 'DFS/BFS for components', notesTopic: 'Connected components' },
  { day: 54, week: 8, topic: 'Cycle Detection in Graph', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=pcKY4hjDrxk', videoTitle: 'Cycle in Undirected Graph', resource: 'https://www.geeksforgeeks.org/detect-cycle-undirected-graph/', resourceTitle: 'Cycle Detection', codingProblem: 'Detect cycle in undirected graph.', testTopic: 'Cycle detection DFS', notesTopic: 'Cycle in graphs' },
  { day: 55, week: 8, topic: 'Islands Problem', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=muncqlKJrH0', videoTitle: 'Number of Islands', resource: 'https://leetcode.com/problems/number-of-islands/', resourceTitle: 'Islands LC', codingProblem: 'Count number of islands in grid using DFS/BFS.', testTopic: 'Grid DFS problems', notesTopic: 'Grid traversal' },
  { day: 56, week: 8, topic: 'Week 8 Review', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=M3_pLsDdeuU', videoTitle: 'Graph Basics Summary', resource: 'https://takeuforward.org/graph/', resourceTitle: 'Graph Sheet', codingProblem: 'Solve 3 graph problems.', testTopic: 'Graph basics comprehensive', notesTopic: 'Week 8 cheatsheet' },

  // Week 9 - Advanced Graphs
  { day: 57, week: 9, topic: 'Topological Sort', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=5lZ0iJMrUMk', videoTitle: 'Topological Sort', resource: 'https://takeuforward.org/data-structure/kahns-algorithm-topological-sort-algorithm-bfs/', resourceTitle: 'Topo Sort Guide', codingProblem: 'Implement topological sort using Kahn algorithm.', testTopic: 'DAG, topological ordering', notesTopic: 'Topological sort' },
  { day: 58, week: 9, topic: 'Dijkstra Shortest Path', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=V6H1qAeB-l4', videoTitle: 'Dijkstra Algorithm', resource: 'https://takeuforward.org/data-structure/dijkstras-algorithm-using-priority-queue-g-32/', resourceTitle: 'Dijkstra Guide', codingProblem: 'Implement Dijkstra shortest path algorithm.', testTopic: 'Shortest path, priority queue', notesTopic: 'Dijkstra algorithm' },
  { day: 59, week: 9, topic: 'Union Find (DSU)', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=aBxjDBC4M1U', videoTitle: 'Disjoint Set Union', resource: 'https://takeuforward.org/data-structure/disjoint-set-union-by-rank-union-by-size-path-compression-g-46/', resourceTitle: 'DSU Guide', codingProblem: 'Implement Union-Find with path compression.', testTopic: 'Union find operations', notesTopic: 'DSU patterns' },
  { day: 60, week: 9, topic: 'Minimum Spanning Tree', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=3stJiTIErLM', videoTitle: 'Kruskal Algorithm', resource: 'https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/', resourceTitle: 'Kruskal Guide', codingProblem: 'Implement Kruskal MST algorithm.', testTopic: 'MST concepts', notesTopic: 'MST algorithms' },
  { day: 61, week: 9, topic: 'Bellman Ford Algorithm', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=0vVofAhAYjc', videoTitle: 'Bellman Ford', resource: 'https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-23/', resourceTitle: 'Bellman Ford Guide', codingProblem: 'Implement Bellman Ford for negative weights.', testTopic: 'Negative edge weights', notesTopic: 'Bellman Ford' },
  { day: 62, week: 9, topic: 'Course Schedule Problem', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=EgI5nU9etnU', videoTitle: 'Course Schedule', resource: 'https://leetcode.com/problems/course-schedule/', resourceTitle: 'Course Schedule LC', codingProblem: 'Determine if courses can be finished given prerequisites.', testTopic: 'Topological sort application', notesTopic: 'Prerequisite problems' },
  { day: 63, week: 9, topic: 'Week 9 Review', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=P6HKtKClQH4', videoTitle: 'Advanced Graphs Summary', resource: 'https://takeuforward.org/graph/', resourceTitle: 'Advanced Graph Sheet', codingProblem: 'Solve 3 advanced graph problems.', testTopic: 'Advanced graphs', notesTopic: 'Week 9 cheatsheet' },

  // Week 10 - DP Basics
  { day: 64, week: 10, topic: 'DP Introduction', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=tyB0ztf0DNY', videoTitle: 'DP Introduction', resource: 'https://takeuforward.org/dynamic-programming/introduction-to-dp/', resourceTitle: 'DP Intro Guide', codingProblem: 'Solve Fibonacci using memoization and tabulation.', testTopic: 'DP patterns basics', notesTopic: 'DP fundamentals' },
  { day: 65, week: 10, topic: 'Climbing Stairs', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=Y0lT9Fck7qI', videoTitle: 'Climbing Stairs DP', resource: 'https://leetcode.com/problems/climbing-stairs/', resourceTitle: 'Climbing Stairs LC', codingProblem: 'Count ways to climb N stairs.', testTopic: 'Basic DP', notesTopic: '1D DP' },
  { day: 66, week: 10, topic: 'House Robber', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=GrMBfJNk_NY', videoTitle: 'House Robber', resource: 'https://leetcode.com/problems/house-robber/', resourceTitle: 'House Robber LC', codingProblem: 'Maximum money robbed from houses in a row.', testTopic: 'Decision DP', notesTopic: 'Robber patterns' },
  { day: 67, week: 10, topic: 'Longest Increasing Subsequence', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=on2hvxBXJH4', videoTitle: 'LIS Problem', resource: 'https://leetcode.com/problems/longest-increasing-subsequence/', resourceTitle: 'LIS LC', codingProblem: 'Find length of longest increasing subsequence.', testTopic: 'LIS patterns', notesTopic: 'Subsequence DP' },
  { day: 68, week: 10, topic: 'Coin Change Problem', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=H9bfqozjoqs', videoTitle: 'Coin Change DP', resource: 'https://leetcode.com/problems/coin-change/', resourceTitle: 'Coin Change LC', codingProblem: 'Minimum coins to make amount.', testTopic: 'Unbounded knapsack', notesTopic: 'Coin problems' },
  { day: 69, week: 10, topic: 'Maximum Subarray', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=AHZpyENo7k4', videoTitle: 'Maximum Subarray Kadane', resource: 'https://leetcode.com/problems/maximum-subarray/', resourceTitle: 'Max Subarray LC', codingProblem: 'Find max sum contiguous subarray - Kadane algorithm.', testTopic: 'Kadane algorithm', notesTopic: 'Kadane patterns' },
  { day: 70, week: 10, topic: 'Week 10 Review', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=FfXoiwwnxFw', videoTitle: '1D DP Summary', resource: 'https://takeuforward.org/dynamic-programming/', resourceTitle: 'DP Sheet', codingProblem: 'Solve 3 DP problems.', testTopic: '1D DP comprehensive', notesTopic: 'Week 10 cheatsheet' },

  // Week 11 - Advanced DP
  { day: 71, week: 11, topic: '2D DP Introduction', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=lBRtnuxg-gU', videoTitle: '2D DP Introduction', resource: 'https://takeuforward.org/data-structure/dynamic-programming-introduction/', resourceTitle: '2D DP Guide', codingProblem: 'Unique paths in grid.', testTopic: '2D DP patterns', notesTopic: '2D DP basics' },
  { day: 72, week: 11, topic: 'Longest Common Subsequence', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=sSno9rV8Rhg', videoTitle: 'LCS Problem', resource: 'https://leetcode.com/problems/longest-common-subsequence/', resourceTitle: 'LCS LC', codingProblem: 'Find length of LCS between two strings.', testTopic: 'LCS pattern', notesTopic: 'String DP' },
  { day: 73, week: 11, topic: 'Edit Distance', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=fJaKO8FbDdo', videoTitle: 'Edit Distance', resource: 'https://leetcode.com/problems/edit-distance/', resourceTitle: 'Edit Distance LC', codingProblem: 'Minimum edit distance between two strings.', testTopic: 'Edit distance patterns', notesTopic: 'Levenshtein distance' },
  { day: 74, week: 11, topic: '0/1 Knapsack', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=cJ21moQpofY', videoTitle: '01 Knapsack', resource: 'https://takeuforward.org/data-structure/0-1-knapsack-dp-19/', resourceTitle: '0/1 Knapsack Guide', codingProblem: 'Solve 0/1 knapsack problem.', testTopic: 'Knapsack variants', notesTopic: 'Knapsack patterns' },
  { day: 75, week: 11, topic: 'Partition Equal Subset', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=fWX9xDmIzRI', videoTitle: 'Partition Equal Subset', resource: 'https://leetcode.com/problems/partition-equal-subset-sum/', resourceTitle: 'Partition LC', codingProblem: 'Partition array into equal subsets.', testTopic: 'Subset sum DP', notesTopic: 'Partition DP' },
  { day: 76, week: 11, topic: 'Matrix Chain Multiplication', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=prx1psByp7U', videoTitle: 'MCM', resource: 'https://takeuforward.org/data-structure/matrix-chain-multiplication-dp-48/', resourceTitle: 'MCM Guide', codingProblem: 'Solve matrix chain multiplication.', testTopic: 'MCM pattern', notesTopic: 'Interval DP' },
  { day: 77, week: 11, topic: 'Week 11 Review', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=lBRtnuxg-gU', videoTitle: 'Advanced DP Review', resource: 'https://takeuforward.org/dynamic-programming/', resourceTitle: 'Advanced DP Sheet', codingProblem: 'Solve 3 advanced DP problems.', testTopic: 'Advanced DP', notesTopic: 'Week 11 cheatsheet' },

  // Week 12 - Greedy & Review
  { day: 78, week: 12, topic: 'Greedy Introduction', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=ARvQcqJ_-NY', videoTitle: 'Greedy Algorithms', resource: 'https://www.geeksforgeeks.org/greedy-algorithms/', resourceTitle: 'Greedy Guide', codingProblem: 'Activity selection problem.', testTopic: 'Greedy choice property', notesTopic: 'Greedy fundamentals' },
  { day: 79, week: 12, topic: 'Job Scheduling', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=zPtI8q9gvX8', videoTitle: 'Job Scheduling', resource: 'https://www.geeksforgeeks.org/job-sequencing-problem/', resourceTitle: 'Job Sequencing', codingProblem: 'Maximum profit job scheduling.', testTopic: 'Scheduling problems', notesTopic: 'Job scheduling' },
  { day: 80, week: 12, topic: 'Interval Problems', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=qKczfGUrFY4', videoTitle: 'Merge Intervals', resource: 'https://leetcode.com/problems/merge-intervals/', resourceTitle: 'Merge Intervals LC', codingProblem: 'Merge overlapping intervals.', testTopic: 'Interval patterns', notesTopic: 'Interval problems' },
  { day: 81, week: 12, topic: 'System Design Basics', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=MbjObHmDbZo', videoTitle: 'System Design Intro', resource: 'https://github.com/donnemartin/system-design-primer', resourceTitle: 'System Design Primer', codingProblem: 'Design URL shortener system on paper.', testTopic: 'Scalability, components', notesTopic: 'System design basics' },
  { day: 82, week: 12, topic: 'Design Rate Limiter', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=FU4WlwfS3G0', videoTitle: 'Rate Limiter Design', resource: 'https://www.geeksforgeeks.org/rate-limiting-algorithms/', resourceTitle: 'Rate Limiting', codingProblem: 'Design a rate limiter with various algorithms.', testTopic: 'Rate limiting', notesTopic: 'Rate limiter design' },
  { day: 83, week: 12, topic: 'Mock Interview 1', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=AfYZ_YkLj2M', videoTitle: 'DSA Mock Interview', resource: 'https://leetcode.com/problemset/all/', resourceTitle: 'LeetCode Problems', codingProblem: 'Solve 2 medium and 1 hard problem under 60 minutes.', testTopic: 'Mixed problems', notesTopic: 'Interview strategies' },
  { day: 84, week: 12, topic: 'Mock Interview 2', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=lXj0oFGkyKQ', videoTitle: 'Google Interview', resource: 'https://leetcode.com/problemset/all/', resourceTitle: 'LeetCode Problems', codingProblem: 'Solve 2 medium and 1 hard problem.', testTopic: 'Mixed problems', notesTopic: 'Company-specific tips' },
  { day: 85, week: 12, topic: 'Mock Interview 3', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=Ji9ZWgQ1OdQ', videoTitle: 'Amazon Interview', resource: 'https://leetcode.com/problemset/all/', resourceTitle: 'LeetCode', codingProblem: 'Full mock interview with system design.', testTopic: 'Complete interview', notesTopic: 'Mock interview prep' },
  { day: 86, week: 12, topic: 'Resume & LinkedIn', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=y8YH0Qbu5h4', videoTitle: 'Tech Resume', resource: 'https://www.linkedin.com/in/', resourceTitle: 'LinkedIn Guide', codingProblem: 'Update resume with all projects and skills.', testTopic: 'Resume dos and donts', notesTopic: 'Resume templates' },
  { day: 87, week: 12, topic: 'Behavioral Interviews', difficulty: 'medium', video: 'https://www.youtube.com/watch?v=PJKYqLP6MRE', videoTitle: 'Behavioral Questions', resource: 'https://www.amazon.jobs/en/principles', resourceTitle: 'Leadership Principles', codingProblem: 'Prepare answers to 10 common behavioral questions using STAR.', testTopic: 'STAR method', notesTopic: 'Behavioral prep' },
  { day: 88, week: 12, topic: 'Final Review Day 1', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=jgiZlGzXMBw', videoTitle: 'DSA Final Review', resource: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2', resourceTitle: 'Complete DSA Sheet', codingProblem: 'Solve top 10 interview questions.', testTopic: 'All topics review', notesTopic: 'Final review' },
  { day: 89, week: 12, topic: 'Final Review Day 2', difficulty: 'hard', video: 'https://www.youtube.com/watch?v=WuzlwOYZDos', videoTitle: 'Final Practice', resource: 'https://neetcode.io/practice', resourceTitle: 'NeetCode 150', codingProblem: 'Solve 5 random medium problems.', testTopic: 'Random mix', notesTopic: 'Last mile prep' },
  { day: 90, week: 12, topic: 'Graduation Day', difficulty: 'easy', video: 'https://www.youtube.com/watch?v=LKQqh9xmmp4', videoTitle: 'You Made It', resource: 'https://leetcode.com/', resourceTitle: 'Continue Grinding', codingProblem: 'Apply to 10 companies today. You are ready.', testTopic: 'Final assessment', notesTopic: 'Career next steps' },
];
