export const DSA_CURRICULUM = [
  {
    "day": 1,
    "week": 1,
    "topic": "Arrays Introduction & Basics",
    "difficulty": "easy",
    "videoTitle": "Arrays in DSA - Striver",
    "resource": "https://takeuforward.org/arrays/introduction-to-arrays/",
    "resourceTitle": "Arrays Introduction Guide",
    "codingProblem": "Given an array of integers, find the largest element. Also find the smallest element. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Array basics, indexing, length operations",
    "notesTopic": "Array fundamentals cheatsheet",
    "visualizerLink": "/dsa-visualizer?algo=bubble-sort"
  },
  {
    "day": 2,
    "week": 1,
    "topic": "Array Traversal & Searching",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=C46QfTjVCnu",
    "videoTitle": "Linear Search Algorithm",
    "resource": "https://www.geeksforgeeks.org/linear-search/",
    "resourceTitle": "Linear Search Guide",
    "codingProblem": "Implement linear search to find a target element. Return its index or -1. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Linear search time complexity, iteration",
    "notesTopic": "Searching algorithms basics",
    "visualizerLink": "/dsa-visualizer?algo=linear-search"
  },
  {
    "day": 3,
    "week": 1,
    "topic": "Binary Search",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=6zhGS79oQ4k",
    "videoTitle": "Binary Search Striver",
    "resource": "https://takeuforward.org/data-structure/binary-search-explained/",
    "resourceTitle": "Binary Search Guide",
    "codingProblem": "Implement binary search on a sorted array. Return index of target. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Binary search, O(log n), divide and conquer",
    "notesTopic": "Binary search patterns",
    "visualizerLink": "/dsa-visualizer?algo=binary-search"
  },
  {
    "day": 4,
    "week": 1,
    "topic": "Two Pointers Technique",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=jzZsG8n2R9A",
    "videoTitle": "Two Pointers Pattern",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Two Sum II Problem",
    "codingProblem": "Given sorted array, find two numbers that sum to target. Return indices. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Two pointer technique, O(n) approaches",
    "notesTopic": "Two pointer patterns",
    "visualizerLink": "/dsa-visualizer?algo=binary-search"
  },
  {
    "day": 5,
    "week": 1,
    "topic": "Sliding Window Basics",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=oAuKPLWHiNs",
    "videoTitle": "Sliding Window Maximum",
    "resource": "https://takeuforward.org/sliding-window/sliding-window-template/",
    "resourceTitle": "Sliding Window Template",
    "codingProblem": "Find maximum sum of contiguous subarray of size k. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Sliding window, fixed and variable windows",
    "notesTopic": "Sliding window template",
    "visualizerLink": "/dsa-visualizer?algo=bubble-sort"
  },
  {
    "day": 6,
    "week": 1,
    "topic": "Array Reversal & Rotation",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=JDOXKqF60RQ",
    "videoTitle": "Array Rotation",
    "resource": "https://takeuforward.org/arrays/",
    "resourceTitle": "Rotate Array Problem",
    "codingProblem": "Rotate array by k positions. In-place with O(1) extra space. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Array manipulation, rotation techniques",
    "notesTopic": "Array rotation algorithms",
    "visualizerLink": "/dsa-visualizer?algo=selection-sort"
  },
  {
    "day": 7,
    "week": 1,
    "topic": "Week 1 Review & Practice",
    "difficulty": "medium",
    "videoTitle": "Array Patterns Summary",
    "resource": "https://takeuforward.org/arrays/arrays-easy-problems/",
    "resourceTitle": "Array Easy Problems",
    "codingProblem": "Solve 3 array problems: reverse in place, find missing number, find duplicates. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Arrays comprehensive review",
    "notesTopic": "Week 1 cheatsheet",
    "visualizerLink": "/dsa-visualizer?algo=bubble-sort"
  },
  {
    "day": 8,
    "week": 2,
    "topic": "Hash Maps Introduction",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=UXDSeD9mN-k",
    "videoTitle": "HashMap Fundamentals",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Two Sum Problem",
    "codingProblem": "Classic Two Sum: return indices of two numbers that add to target. (Solve in C++. Use unordered_map<int,int> for O(1) lookups)",
    "testTopic": "Hashmap basics, O(1) lookups",
    "notesTopic": "HashMap fundamentals"
  },
  {
    "day": 9,
    "week": 2,
    "topic": "Frequency Counting",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=UXDSeD9mN-k",
    "videoTitle": "Frequency Counter Pattern",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Valid Anagram",
    "codingProblem": "Check if two strings are anagrams using frequency map. (Solve in C++. Use string, unordered_map<char,int> for frequency)",
    "testTopic": "Frequency counting, character maps",
    "notesTopic": "Frequency counter technique"
  },
  {
    "day": 10,
    "week": 2,
    "topic": "Hash Sets",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=UXDSeD9mN-k",
    "videoTitle": "HashSet vs HashMap",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Contains Duplicate",
    "codingProblem": "Check if array contains any duplicates. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Hash sets, unique elements",
    "notesTopic": "HashSet patterns"
  },
  {
    "day": 11,
    "week": 2,
    "topic": "Subarray Sum Problems",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=w_KEocd__20",
    "videoTitle": "Subarray Sum Equals K",
    "resource": "https://takeuforward.org/arrays/",
    "resourceTitle": "Subarray Sum = K",
    "codingProblem": "Count number of subarrays with sum equal to k. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Prefix sums with hashmap",
    "notesTopic": "Subarray sum patterns"
  },
  {
    "day": 12,
    "week": 2,
    "topic": "Group Anagrams Pattern",
    "difficulty": "medium",
    "videoTitle": "Group Anagrams",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Group Anagrams Problem",
    "codingProblem": "Group strings that are anagrams of each other. (Solve in C++. Use string, unordered_map<char,int> for frequency)",
    "testTopic": "Grouping with hash keys",
    "notesTopic": "Group-by pattern"
  },
  {
    "day": 13,
    "week": 2,
    "topic": "Longest Substring Without Repeat",
    "difficulty": "medium",
    "videoTitle": "Longest Substring Without Repeating",
    "resource": "https://takeuforward.org/binary-tree/",
    "resourceTitle": "LeetCode Problem",
    "codingProblem": "Find length of longest substring without repeating characters. (Solve in C++. Use string, unordered_map<char,int> for frequency)",
    "testTopic": "Sliding window with hashmap",
    "notesTopic": "Substring problems"
  },
  {
    "day": 14,
    "week": 2,
    "topic": "Week 2 Review",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=UXDSeD9mN-k",
    "videoTitle": "Hashing Patterns Review",
    "resource": "https://takeuforward.org/hashing/",
    "resourceTitle": "Hashing Problems Sheet",
    "codingProblem": "Solve 3 hashing problems of varying difficulty. (Solve in C++)",
    "testTopic": "Hashing comprehensive",
    "notesTopic": "Week 2 cheatsheet"
  },
  {
    "day": 15,
    "week": 3,
    "topic": "Linked List Basics",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=N8XKRmS_0_0",
    "videoTitle": "Linked List Introduction",
    "resource": "https://takeuforward.org/data-structure/introduction-to-linked-list/",
    "resourceTitle": "Linked List Guide",
    "codingProblem": "Implement singly linked list with insert, delete, print methods. (Solve in C++. Define struct ListNode { int val; ListNode* next; })",
    "testTopic": "Linked list structure, pointers",
    "notesTopic": "Linked list fundamentals",
    "visualizerLink": "/dsa-visualizer?algo=linked-list"
  },
  {
    "day": 16,
    "week": 3,
    "topic": "Reverse Linked List",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=7K7n0E-6Fvo",
    "videoTitle": "Reverse Linked List",
    "resource": "https://takeuforward.org/linked-list/",
    "resourceTitle": "Reverse Linked List",
    "codingProblem": "Reverse a singly linked list iteratively and recursively. (Solve in C++. Define struct ListNode { int val; ListNode* next; })",
    "testTopic": "Pointer manipulation",
    "notesTopic": "Reversal patterns",
    "visualizerLink": "/dsa-visualizer?algo=linked-list"
  },
  {
    "day": 17,
    "week": 3,
    "topic": "Cycle Detection (Floyd)",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=wjYc2G73C3o",
    "videoTitle": "Floyd Cycle Detection",
    "resource": "https://takeuforward.org/graph/",
    "resourceTitle": "Linked List Cycle",
    "codingProblem": "Detect if linked list has a cycle using slow/fast pointers. (Solve in C++. Define struct ListNode { int val; ListNode* next; })",
    "testTopic": "Floyd algorithm, slow fast pointer",
    "notesTopic": "Cycle detection",
    "visualizerLink": "/dsa-visualizer?algo=linked-list"
  },
  {
    "day": 18,
    "week": 3,
    "topic": "Merge Two Sorted Lists",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=7K7n0E-6Fvo",
    "videoTitle": "Merge Two Sorted Lists",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Merge Sorted Lists",
    "codingProblem": "Merge two sorted linked lists into one sorted list. (Solve in C++. Define struct ListNode { int val; ListNode* next; })",
    "testTopic": "Merging lists, dummy node pattern",
    "notesTopic": "List merging",
    "visualizerLink": "/dsa-visualizer?algo=merge-sort"
  },
  {
    "day": 19,
    "week": 3,
    "topic": "Middle of Linked List",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=7K7n0E-6Fvo",
    "videoTitle": "Middle of Linked List",
    "resource": "https://takeuforward.org/linked-list/",
    "resourceTitle": "LC Problem",
    "codingProblem": "Find middle of linked list in single pass. (Solve in C++. Define struct ListNode { int val; ListNode* next; })",
    "testTopic": "Two pointer on linked lists",
    "notesTopic": "Middle finding",
    "visualizerLink": "/dsa-visualizer?algo=linked-list"
  },
  {
    "day": 20,
    "week": 3,
    "topic": "Remove Nth Node From End",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=7K7n0E-6Fvo",
    "videoTitle": "Remove Nth From End",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Remove Nth Problem",
    "codingProblem": "Remove Nth node from end in one pass. (Solve in C++. Define struct ListNode { int val; ListNode* next; })",
    "testTopic": "Two pointer with gap",
    "notesTopic": "Remove node patterns",
    "visualizerLink": "/dsa-visualizer?algo=linked-list"
  },
  {
    "day": 21,
    "week": 3,
    "topic": "Week 3 Review",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=7K7n0E-6Fvo",
    "videoTitle": "Linked List Summary",
    "resource": "https://takeuforward.org/linked-list/",
    "resourceTitle": "Linked List Sheet",
    "codingProblem": "Solve 3 linked list problems. (Solve in C++. Define struct ListNode { int val; ListNode* next; })",
    "testTopic": "Linked list comprehensive",
    "notesTopic": "Week 3 cheatsheet",
    "visualizerLink": "/dsa-visualizer?algo=linked-list"
  },
  {
    "day": 22,
    "week": 4,
    "topic": "Stack Basics & Operations",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=GYptUgnIM_I",
    "videoTitle": "Stack Introduction",
    "resource": "https://takeuforward.org/data-structure/implement-stack-using-arrays/",
    "resourceTitle": "Stack Implementation",
    "codingProblem": "Implement stack using array with push, pop, top, empty. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Stack LIFO principle",
    "notesTopic": "Stack fundamentals",
    "visualizerLink": "/dsa-visualizer?algo=stack"
  },
  {
    "day": 23,
    "week": 4,
    "topic": "Valid Parentheses",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=GYptUgnIM_I",
    "videoTitle": "Valid Parentheses",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Valid Parentheses LC",
    "codingProblem": "Check if string of brackets is valid using stack. (Solve in C++. Use string, unordered_map<char,int> for frequency)",
    "testTopic": "Stack for matching",
    "notesTopic": "Bracket matching",
    "visualizerLink": "/dsa-visualizer?algo=stack"
  },
  {
    "day": 24,
    "week": 4,
    "topic": "Monotonic Stack",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=GYptUgnIM_I",
    "videoTitle": "Monotonic Stack",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Next Greater Element",
    "codingProblem": "Find next greater element for each element in array. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Monotonic stack technique",
    "notesTopic": "Monotonic patterns",
    "visualizerLink": "/dsa-visualizer?algo=stack"
  },
  {
    "day": 25,
    "week": 4,
    "topic": "Queue Basics",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=GYptUgnIM_I",
    "videoTitle": "Queue Introduction",
    "resource": "https://takeuforward.org/data-structure/implement-queue-using-array/",
    "resourceTitle": "Queue Implementation",
    "codingProblem": "Implement queue using array with enqueue, dequeue. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Queue FIFO",
    "notesTopic": "Queue fundamentals",
    "visualizerLink": "/dsa-visualizer?algo=queue"
  },
  {
    "day": 26,
    "week": 4,
    "topic": "Priority Queue Basics",
    "difficulty": "medium",
    "videoTitle": "Priority Queue",
    "resource": "https://www.geeksforgeeks.org/priority-queue-set-1-introduction/",
    "resourceTitle": "Priority Queue Guide",
    "codingProblem": "Find Kth largest element using priority queue. (Solve in C++. Use queue<int> from <queue> for BFS)",
    "testTopic": "Heaps basics, min/max heaps",
    "notesTopic": "Priority queue patterns",
    "visualizerLink": "/dsa-visualizer?algo=queue"
  },
  {
    "day": 27,
    "week": 4,
    "topic": "Sliding Window Maximum",
    "difficulty": "hard",
    "video": "https://www.youtube.com/watch?v=oAuKPLWHiNs",
    "videoTitle": "Sliding Window Maximum Deque",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Sliding Window Max",
    "codingProblem": "Find maximum in each sliding window of size k. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Deque, sliding window optimal",
    "notesTopic": "Window max patterns",
    "visualizerLink": "/dsa-visualizer?algo=queue"
  },
  {
    "day": 28,
    "week": 4,
    "topic": "Week 4 Review",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=GYptUgnIM_I",
    "videoTitle": "Stack Queue Summary",
    "resource": "https://takeuforward.org/stack-and-queue/",
    "resourceTitle": "Stack Queue Sheet",
    "codingProblem": "Solve 3 mixed problems. (Solve in C++)",
    "testTopic": "Stack queue comprehensive",
    "notesTopic": "Week 4 cheatsheet",
    "visualizerLink": "/dsa-visualizer?algo=stack"
  },
  {
    "day": 29,
    "week": 5,
    "topic": "Recursion Fundamentals",
    "difficulty": "easy",
    "videoTitle": "Recursion Basics",
    "resource": "https://takeuforward.org/recursion/introduction-to-recursion/",
    "resourceTitle": "Recursion Intro",
    "codingProblem": "Print numbers 1 to N using recursion. Print sum using recursion. (Solve in C++. Use recursive function with backtracking; vector<vector<int>> for results)",
    "testTopic": "Base case, recursive case",
    "notesTopic": "Recursion fundamentals"
  },
  {
    "day": 30,
    "week": 5,
    "topic": "Factorial & Fibonacci",
    "difficulty": "easy",
    "videoTitle": "Factorial Fibonacci",
    "resource": "https://www.geeksforgeeks.org/program-for-factorial-of-a-number/",
    "resourceTitle": "Factorial Guide",
    "codingProblem": "Calculate factorial and Nth Fibonacci recursively. (Solve in C++. Use vector<int> dp(n, 0) or vector<vector<int>> dp(m, vector<int>(n, 0)))",
    "testTopic": "Simple recursion problems",
    "notesTopic": "Math recursion"
  },
  {
    "day": 31,
    "week": 5,
    "topic": "Subset Generation",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=tKnmI1kUbSg",
    "videoTitle": "Power Set Recursion",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Subsets Problem",
    "codingProblem": "Generate all subsets of a set using recursion. (Solve in C++. Use vector<int> dp(n, 0) or vector<vector<int>> dp(m, vector<int>(n, 0)))",
    "testTopic": "Include exclude pattern",
    "notesTopic": "Subset generation"
  },
  {
    "day": 32,
    "week": 5,
    "topic": "Permutations",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=f2ic2Rsc9pU",
    "videoTitle": "All Permutations",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Permutations LC",
    "codingProblem": "Generate all permutations of an array. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Swapping pattern",
    "notesTopic": "Permutation generation"
  },
  {
    "day": 33,
    "week": 5,
    "topic": "N-Queens Backtracking",
    "difficulty": "hard",
    "videoTitle": "N-Queens Solution",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "N-Queens LC",
    "codingProblem": "Solve N-Queens problem for given n. (Solve in C++. Use bitset<N> or bit manipulation operators (&, |, ^, <<, >>))",
    "testTopic": "Backtracking pattern",
    "notesTopic": "N-Queens approach"
  },
  {
    "day": 34,
    "week": 5,
    "topic": "Sudoku Solver",
    "difficulty": "hard",
    "videoTitle": "Sudoku Solver",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Sudoku LC",
    "codingProblem": "Solve 9x9 Sudoku using backtracking. (Solve in C++. Use recursive function with backtracking; vector<vector<int>> for results)",
    "testTopic": "Constraint satisfaction",
    "notesTopic": "Sudoku patterns"
  },
  {
    "day": 35,
    "week": 5,
    "topic": "Week 5 Review",
    "difficulty": "hard",
    "videoTitle": "Recursion Summary",
    "resource": "https://takeuforward.org/recursion/",
    "resourceTitle": "Recursion Sheet",
    "codingProblem": "Solve 3 recursion problems. (Solve in C++. Use recursive function with backtracking; vector<vector<int>> for results)",
    "testTopic": "Recursion comprehensive",
    "notesTopic": "Week 5 cheatsheet"
  },
  {
    "day": 36,
    "week": 6,
    "topic": "Binary Tree Basics",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=jmy0La5Mqko",
    "videoTitle": "Binary Tree Intro",
    "resource": "https://takeuforward.org/data-structure/binary-tree-representation-in-c/",
    "resourceTitle": "Binary Tree Guide",
    "codingProblem": "Create binary tree and print all nodes. (Solve in C++. Define struct ListNode { int val; ListNode* next; })",
    "testTopic": "Tree structure, nodes",
    "notesTopic": "Tree basics"
  },
  {
    "day": 37,
    "week": 6,
    "topic": "Tree Traversals (DFS)",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=jmy0La5Mqko",
    "videoTitle": "Tree Traversals",
    "resource": "https://takeuforward.org/binary-tree/",
    "resourceTitle": "Inorder Traversal",
    "codingProblem": "Implement inorder, preorder, postorder traversals. (Solve in C++. Define struct TreeNode { int val; TreeNode *left, *right; })",
    "testTopic": "DFS on trees",
    "notesTopic": "Tree traversal patterns"
  },
  {
    "day": 38,
    "week": 6,
    "topic": "Level Order Traversal (BFS)",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=jmy0La5Mqko",
    "videoTitle": "Level Order BFS",
    "resource": "https://takeuforward.org/graph/",
    "resourceTitle": "Level Order LC",
    "codingProblem": "Level order traversal using queue. (Solve in C++. Use queue<int> from <queue> for BFS)",
    "testTopic": "BFS with queue",
    "notesTopic": "BFS on trees"
  },
  {
    "day": 39,
    "week": 6,
    "topic": "Height & Depth of Tree",
    "difficulty": "easy",
    "videoTitle": "Tree Height",
    "resource": "https://takeuforward.org/binary-tree/",
    "resourceTitle": "Max Depth LC",
    "codingProblem": "Find max depth of binary tree. (Solve in C++. Define struct TreeNode { int val; TreeNode *left, *right; })",
    "testTopic": "Recursion on trees",
    "notesTopic": "Tree metrics"
  },
  {
    "day": 40,
    "week": 6,
    "topic": "Binary Search Tree (BST)",
    "difficulty": "medium",
    "videoTitle": "BST Intro",
    "resource": "https://takeuforward.org/binary-search-tree/introduction-to-binary-search-tree/",
    "resourceTitle": "BST Guide",
    "codingProblem": "Implement BST with insert, search, delete. (Solve in C++. Define struct TreeNode { int val; TreeNode *left, *right; })",
    "testTopic": "BST properties",
    "notesTopic": "BST operations"
  },
  {
    "day": 41,
    "week": 6,
    "topic": "LCA of Binary Tree",
    "difficulty": "medium",
    "videoTitle": "LCA Problem",
    "resource": "https://takeuforward.org/binary-tree/",
    "resourceTitle": "LCA LC",
    "codingProblem": "Find LCA of two nodes in binary tree. (Solve in C++. Define struct ListNode { int val; ListNode* next; })",
    "testTopic": "LCA techniques",
    "notesTopic": "LCA algorithms"
  },
  {
    "day": 42,
    "week": 6,
    "topic": "Week 6 Review",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=jmy0La5Mqko",
    "videoTitle": "Trees Summary",
    "resource": "https://takeuforward.org/binary-tree/",
    "resourceTitle": "Trees Sheet",
    "codingProblem": "Solve 3 tree problems. (Solve in C++. Define struct TreeNode { int val; TreeNode *left, *right; })",
    "testTopic": "Trees comprehensive",
    "notesTopic": "Week 6 cheatsheet"
  },
  {
    "day": 43,
    "week": 7,
    "topic": "Heap Data Structure",
    "difficulty": "medium",
    "videoTitle": "Heap Introduction",
    "resource": "https://www.geeksforgeeks.org/heap-data-structure/",
    "resourceTitle": "Heap Guide",
    "codingProblem": "Implement min heap with insert and extract min. (Solve in C++. Use priority_queue<int> (max-heap) or priority_queue<int,vector<int>,greater<int>> (min-heap))",
    "testTopic": "Heap property, heapify",
    "notesTopic": "Heap fundamentals"
  },
  {
    "day": 44,
    "week": 7,
    "topic": "Kth Largest/Smallest",
    "difficulty": "medium",
    "videoTitle": "Kth Largest Element",
    "resource": "https://takeuforward.org/heap/",
    "resourceTitle": "Kth Largest LC",
    "codingProblem": "Find Kth largest element using heap. (Solve in C++. Use priority_queue<int> (max-heap) or priority_queue<int,vector<int>,greater<int>> (min-heap))",
    "testTopic": "Top K pattern",
    "notesTopic": "Top K patterns"
  },
  {
    "day": 45,
    "week": 7,
    "topic": "Merge K Sorted Lists",
    "difficulty": "hard",
    "videoTitle": "Merge K Sorted Lists",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Merge K LC",
    "codingProblem": "Merge K sorted linked lists using heap. (Solve in C++. Use priority_queue<int> (max-heap) or priority_queue<int,vector<int>,greater<int>> (min-heap))",
    "testTopic": "Heap with lists",
    "notesTopic": "K-way merge"
  },
  {
    "day": 46,
    "week": 7,
    "topic": "Top K Frequent Elements",
    "difficulty": "medium",
    "videoTitle": "Top K Frequent",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Top K Frequent LC",
    "codingProblem": "Find K most frequent elements. (Solve in C++. Use priority_queue<int> (max-heap) or priority_queue<int,vector<int>,greater<int>> (min-heap))",
    "testTopic": "Frequency with heap",
    "notesTopic": "Frequency heap"
  },
  {
    "day": 47,
    "week": 7,
    "topic": "Tries Introduction",
    "difficulty": "medium",
    "videoTitle": "Trie Data Structure",
    "resource": "https://takeuforward.org/data-structure/implement-trie-1/",
    "resourceTitle": "Trie Guide",
    "codingProblem": "Implement trie with insert, search, startsWith. (Solve in C++. Implement TrieNode with array<TrieNode*,26> children)",
    "testTopic": "Trie structure, prefix matching",
    "notesTopic": "Trie fundamentals"
  },
  {
    "day": 48,
    "week": 7,
    "topic": "Segment Trees Basics",
    "difficulty": "hard",
    "video": "https://www.youtube.com/watch?v=2bSS8rtFym4",
    "videoTitle": "Segment Tree",
    "resource": "https://www.geeksforgeeks.org/segment-tree-set-1-sum-of-given-range/",
    "resourceTitle": "Segment Tree Guide",
    "codingProblem": "Build segment tree for range sum queries. (Solve in C++. Define struct TreeNode { int val; TreeNode *left, *right; })",
    "testTopic": "Segment tree operations",
    "notesTopic": "Segment trees"
  },
  {
    "day": 49,
    "week": 7,
    "topic": "Week 7 Review",
    "difficulty": "hard",
    "videoTitle": "Heaps Summary",
    "resource": "https://takeuforward.org/heap/",
    "resourceTitle": "Heap Sheet",
    "codingProblem": "Solve 3 heap problems. (Solve in C++. Use priority_queue<int> (max-heap) or priority_queue<int,vector<int>,greater<int>> (min-heap))",
    "testTopic": "Heaps comprehensive",
    "notesTopic": "Week 7 cheatsheet"
  },
  {
    "day": 50,
    "week": 8,
    "topic": "Graph Representation",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=3oI-34aPMWM",
    "videoTitle": "Graph Introduction",
    "resource": "https://takeuforward.org/graph/introduction-to-graphs/",
    "resourceTitle": "Graph Guide",
    "codingProblem": "Build graph using adjacency list and matrix. (Solve in C++. Use vector<vector<int>> adj(n) for adjacency list)",
    "testTopic": "Graph types, representations",
    "notesTopic": "Graph basics"
  },
  {
    "day": 51,
    "week": 8,
    "topic": "BFS Traversal",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=3oI-34aPMWM",
    "videoTitle": "BFS Algorithm",
    "resource": "https://takeuforward.org/graph/breadth-first-search-bfs-level-order-traversal/",
    "resourceTitle": "BFS Guide",
    "codingProblem": "Implement BFS traversal of graph. (Solve in C++. Use queue<int> from <queue> for BFS)",
    "testTopic": "BFS with queue",
    "notesTopic": "BFS pattern"
  },
  {
    "day": 52,
    "week": 8,
    "topic": "DFS Traversal",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=3oI-34aPMWM",
    "videoTitle": "DFS Algorithm",
    "resource": "https://takeuforward.org/data-structure/depth-first-search-dfs/",
    "resourceTitle": "DFS Guide",
    "codingProblem": "Implement DFS traversal recursively and iteratively. (Solve in C++. Use vector<vector<int>> adj(n) for adjacency list)",
    "testTopic": "DFS with stack/recursion",
    "notesTopic": "DFS pattern"
  },
  {
    "day": 53,
    "week": 8,
    "topic": "Connected Components",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=ACzkVtewUYA",
    "videoTitle": "Connected Components",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Connected Components",
    "codingProblem": "Count number of connected components in graph. (Solve in C++. Use vector<vector<int>> adj(n) for adjacency list)",
    "testTopic": "DFS/BFS for components",
    "notesTopic": "Connected components"
  },
  {
    "day": 54,
    "week": 8,
    "topic": "Cycle Detection in Graph",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=V8qR99309ds",
    "videoTitle": "Cycle in Undirected Graph",
    "resource": "https://www.geeksforgeeks.org/detect-cycle-undirected-graph/",
    "resourceTitle": "Cycle Detection",
    "codingProblem": "Detect cycle in undirected graph. (Solve in C++. Define struct ListNode { int val; ListNode* next; })",
    "testTopic": "Cycle detection DFS",
    "notesTopic": "Cycle in graphs"
  },
  {
    "day": 55,
    "week": 8,
    "topic": "Islands Problem",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=V8qR99309ds",
    "videoTitle": "Number of Islands",
    "resource": "https://takeuforward.org/graph/",
    "resourceTitle": "Islands LC",
    "codingProblem": "Count number of islands in grid using DFS/BFS. (Solve in C++. Use queue<int> from <queue> for BFS)",
    "testTopic": "Grid DFS problems",
    "notesTopic": "Grid traversal"
  },
  {
    "day": 56,
    "week": 8,
    "topic": "Week 8 Review",
    "difficulty": "medium",
    "video": "https://www.youtube.com/watch?v=3oI-34aPMWM",
    "videoTitle": "Graph Basics Summary",
    "resource": "https://takeuforward.org/graph/",
    "resourceTitle": "Graph Sheet",
    "codingProblem": "Solve 3 graph problems. (Solve in C++. Use vector<vector<int>> adj(n) for adjacency list)",
    "testTopic": "Graph basics comprehensive",
    "notesTopic": "Week 8 cheatsheet"
  },
  {
    "day": 57,
    "week": 9,
    "topic": "Topological Sort",
    "difficulty": "hard",
    "videoTitle": "Topological Sort",
    "resource": "https://takeuforward.org/data-structure/kahns-algorithm-topological-sort-algorithm-bfs/",
    "resourceTitle": "Topo Sort Guide",
    "codingProblem": "Implement topological sort using Kahn algorithm. (Solve in C++. Use vector<vector<int>> adj(n) for adjacency list)",
    "testTopic": "DAG, topological ordering",
    "notesTopic": "Topological sort"
  },
  {
    "day": 58,
    "week": 9,
    "topic": "Dijkstra Shortest Path",
    "difficulty": "hard",
    "videoTitle": "Dijkstra Algorithm",
    "resource": "https://takeuforward.org/data-structure/dijkstras-algorithm-using-priority-queue-g-32/",
    "resourceTitle": "Dijkstra Guide",
    "codingProblem": "Implement Dijkstra shortest path algorithm. (Solve in C++. Use vector<vector<int>> adj(n) for adjacency list)",
    "testTopic": "Shortest path, priority queue",
    "notesTopic": "Dijkstra algorithm"
  },
  {
    "day": 59,
    "week": 9,
    "topic": "Union Find (DSU)",
    "difficulty": "hard",
    "videoTitle": "Disjoint Set Union",
    "resource": "https://takeuforward.org/data-structure/disjoint-set-union-by-rank-union-by-size-path-compression-g-46/",
    "resourceTitle": "DSU Guide",
    "codingProblem": "Implement Union-Find with path compression. (Solve in C++. Use vector<int> dp(n, 0) or vector<vector<int>> dp(m, vector<int>(n, 0)))",
    "testTopic": "Union find operations",
    "notesTopic": "DSU patterns"
  },
  {
    "day": 60,
    "week": 9,
    "topic": "Minimum Spanning Tree",
    "difficulty": "hard",
    "videoTitle": "Kruskal Algorithm",
    "resource": "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/",
    "resourceTitle": "Kruskal Guide",
    "codingProblem": "Implement Kruskal MST algorithm. (Solve in C++. Define struct TreeNode { int val; TreeNode *left, *right; })",
    "testTopic": "MST concepts",
    "notesTopic": "MST algorithms"
  },
  {
    "day": 61,
    "week": 9,
    "topic": "Bellman Ford Algorithm",
    "difficulty": "hard",
    "videoTitle": "Bellman Ford",
    "resource": "https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-23/",
    "resourceTitle": "Bellman Ford Guide",
    "codingProblem": "Implement Bellman Ford for negative weights. (Solve in C++. Use vector<vector<int>> adj(n) for adjacency list)",
    "testTopic": "Negative edge weights",
    "notesTopic": "Bellman Ford"
  },
  {
    "day": 62,
    "week": 9,
    "topic": "Course Schedule Problem",
    "difficulty": "medium",
    "videoTitle": "Course Schedule",
    "resource": "https://takeuforward.org/greedy/",
    "resourceTitle": "Course Schedule LC",
    "codingProblem": "Determine if courses can be finished given prerequisites. (Solve in C++. Use sort + greedy selection; pair<int,int> for intervals)",
    "testTopic": "Topological sort application",
    "notesTopic": "Prerequisite problems"
  },
  {
    "day": 63,
    "week": 9,
    "topic": "Week 9 Review",
    "difficulty": "hard",
    "videoTitle": "Advanced Graphs Summary",
    "resource": "https://takeuforward.org/graph/",
    "resourceTitle": "Advanced Graph Sheet",
    "codingProblem": "Solve 3 advanced graph problems. (Solve in C++. Use vector<vector<int>> adj(n) for adjacency list)",
    "testTopic": "Advanced graphs",
    "notesTopic": "Week 9 cheatsheet"
  },
  {
    "day": 64,
    "week": 10,
    "topic": "DP Introduction",
    "difficulty": "medium",
    "videoTitle": "DP Introduction",
    "resource": "https://takeuforward.org/dynamic-programming/introduction-to-dp/",
    "resourceTitle": "DP Intro Guide",
    "codingProblem": "Solve Fibonacci using memoization and tabulation. (Solve in C++. Use vector<int> dp(n, 0) or vector<vector<int>> dp(m, vector<int>(n, 0)))",
    "testTopic": "DP patterns basics",
    "notesTopic": "DP fundamentals"
  },
  {
    "day": 65,
    "week": 10,
    "topic": "Climbing Stairs",
    "difficulty": "easy",
    "videoTitle": "Climbing Stairs DP",
    "resource": "https://takeuforward.org/dynamic-programming/",
    "resourceTitle": "Climbing Stairs LC",
    "codingProblem": "Count ways to climb N stairs. (Solve in C++)",
    "testTopic": "Basic DP",
    "notesTopic": "1D DP"
  },
  {
    "day": 66,
    "week": 10,
    "topic": "House Robber",
    "difficulty": "medium",
    "videoTitle": "House Robber",
    "resource": "https://takeuforward.org/dynamic-programming/",
    "resourceTitle": "House Robber LC",
    "codingProblem": "Maximum money robbed from houses in a row. (Solve in C++)",
    "testTopic": "Decision DP",
    "notesTopic": "Robber patterns"
  },
  {
    "day": 67,
    "week": 10,
    "topic": "Longest Increasing Subsequence",
    "difficulty": "medium",
    "videoTitle": "LIS Problem",
    "resource": "https://takeuforward.org/dynamic-programming/",
    "resourceTitle": "LIS LC",
    "codingProblem": "Find length of longest increasing subsequence. (Solve in C++)",
    "testTopic": "LIS patterns",
    "notesTopic": "Subsequence DP"
  },
  {
    "day": 68,
    "week": 10,
    "topic": "Coin Change Problem",
    "difficulty": "medium",
    "videoTitle": "Coin Change DP",
    "resource": "https://takeuforward.org/dynamic-programming/",
    "resourceTitle": "Coin Change LC",
    "codingProblem": "Minimum coins to make amount. (Solve in C++. Use vector<int> dp(n, 0) or vector<vector<int>> dp(m, vector<int>(n, 0)))",
    "testTopic": "Unbounded knapsack",
    "notesTopic": "Coin problems"
  },
  {
    "day": 69,
    "week": 10,
    "topic": "Maximum Subarray",
    "difficulty": "easy",
    "video": "https://www.youtube.com/watch?v=w_KEocd__20",
    "videoTitle": "Maximum Subarray Kadane",
    "resource": "https://takeuforward.org/arrays/",
    "resourceTitle": "Max Subarray LC",
    "codingProblem": "Find max sum contiguous subarray - Kadane algorithm. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Kadane algorithm",
    "notesTopic": "Kadane patterns"
  },
  {
    "day": 70,
    "week": 10,
    "topic": "Week 10 Review",
    "difficulty": "medium",
    "videoTitle": "1D DP Summary",
    "resource": "https://takeuforward.org/dynamic-programming/",
    "resourceTitle": "DP Sheet",
    "codingProblem": "Solve 3 DP problems. (Solve in C++. Use vector<int> dp(n, 0) or vector<vector<int>> dp(m, vector<int>(n, 0)))",
    "testTopic": "1D DP comprehensive",
    "notesTopic": "Week 10 cheatsheet"
  },
  {
    "day": 71,
    "week": 11,
    "topic": "2D DP Introduction",
    "difficulty": "hard",
    "videoTitle": "2D DP Introduction",
    "resource": "https://takeuforward.org/data-structure/dynamic-programming-introduction/",
    "resourceTitle": "2D DP Guide",
    "codingProblem": "Unique paths in grid. (Solve in C++. Use unordered_set<int> for O(1) membership checks)",
    "testTopic": "2D DP patterns",
    "notesTopic": "2D DP basics"
  },
  {
    "day": 72,
    "week": 11,
    "topic": "Longest Common Subsequence",
    "difficulty": "medium",
    "videoTitle": "LCS Problem",
    "resource": "https://takeuforward.org/dynamic-programming/",
    "resourceTitle": "LCS LC",
    "codingProblem": "Find length of LCS between two strings. (Solve in C++. Use string, unordered_map<char,int> for frequency)",
    "testTopic": "LCS pattern",
    "notesTopic": "String DP"
  },
  {
    "day": 73,
    "week": 11,
    "topic": "Edit Distance",
    "difficulty": "hard",
    "videoTitle": "Edit Distance",
    "resource": "https://takeuforward.org/dynamic-programming/",
    "resourceTitle": "Edit Distance LC",
    "codingProblem": "Minimum edit distance between two strings. (Solve in C++. Use string, unordered_map<char,int> for frequency)",
    "testTopic": "Edit distance patterns",
    "notesTopic": "Levenshtein distance"
  },
  {
    "day": 74,
    "week": 11,
    "topic": "0/1 Knapsack",
    "difficulty": "medium",
    "videoTitle": "01 Knapsack",
    "resource": "https://takeuforward.org/data-structure/0-1-knapsack-dp-19/",
    "resourceTitle": "0/1 Knapsack Guide",
    "codingProblem": "Solve 0/1 knapsack problem. (Solve in C++. Use vector<int> dp(n, 0) or vector<vector<int>> dp(m, vector<int>(n, 0)))",
    "testTopic": "Knapsack variants",
    "notesTopic": "Knapsack patterns"
  },
  {
    "day": 75,
    "week": 11,
    "topic": "Partition Equal Subset",
    "difficulty": "medium",
    "videoTitle": "Partition Equal Subset",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Partition LC",
    "codingProblem": "Partition array into equal subsets. (Solve in C++. Use vector<int> and STL algorithms (sort, reverse, accumulate))",
    "testTopic": "Subset sum DP",
    "notesTopic": "Partition DP"
  },
  {
    "day": 76,
    "week": 11,
    "topic": "Matrix Chain Multiplication",
    "difficulty": "hard",
    "videoTitle": "MCM",
    "resource": "https://takeuforward.org/data-structure/matrix-chain-multiplication-dp-48/",
    "resourceTitle": "MCM Guide",
    "codingProblem": "Solve matrix chain multiplication. (Solve in C++)",
    "testTopic": "MCM pattern",
    "notesTopic": "Interval DP"
  },
  {
    "day": 77,
    "week": 11,
    "topic": "Week 11 Review",
    "difficulty": "hard",
    "videoTitle": "Advanced DP Review",
    "resource": "https://takeuforward.org/dynamic-programming/",
    "resourceTitle": "Advanced DP Sheet",
    "codingProblem": "Solve 3 advanced DP problems. (Solve in C++. Use vector<int> dp(n, 0) or vector<vector<int>> dp(m, vector<int>(n, 0)))",
    "testTopic": "Advanced DP",
    "notesTopic": "Week 11 cheatsheet"
  },
  {
    "day": 78,
    "week": 12,
    "topic": "Greedy Introduction",
    "difficulty": "medium",
    "videoTitle": "Greedy Algorithms",
    "resource": "https://www.geeksforgeeks.org/greedy-algorithms/",
    "resourceTitle": "Greedy Guide",
    "codingProblem": "Activity selection problem. (Solve in C++. Use sort + greedy selection; pair<int,int> for intervals)",
    "testTopic": "Greedy choice property",
    "notesTopic": "Greedy fundamentals"
  },
  {
    "day": 79,
    "week": 12,
    "topic": "Job Scheduling",
    "difficulty": "medium",
    "videoTitle": "Job Scheduling",
    "resource": "https://www.geeksforgeeks.org/job-sequencing-problem/",
    "resourceTitle": "Job Sequencing",
    "codingProblem": "Maximum profit job scheduling. (Solve in C++)",
    "testTopic": "Scheduling problems",
    "notesTopic": "Job scheduling"
  },
  {
    "day": 80,
    "week": 12,
    "topic": "Interval Problems",
    "difficulty": "medium",
    "videoTitle": "Merge Intervals",
    "resource": "https://takeuforward.org/greedy/",
    "resourceTitle": "Merge Intervals LC",
    "codingProblem": "Merge overlapping intervals. (Solve in C++. Use sort + greedy selection; pair<int,int> for intervals)",
    "testTopic": "Interval patterns",
    "notesTopic": "Interval problems"
  },
  {
    "day": 81,
    "week": 12,
    "topic": "System Design Basics",
    "difficulty": "hard",
    "videoTitle": "System Design Intro",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "System Design Primer",
    "codingProblem": "Design URL shortener system on paper. (Solve in C++. Use bitset<N> or bit manipulation operators (&, |, ^, <<, >>))",
    "testTopic": "Scalability, components",
    "notesTopic": "System design basics"
  },
  {
    "day": 82,
    "week": 12,
    "topic": "Design Rate Limiter",
    "difficulty": "hard",
    "videoTitle": "Rate Limiter Design",
    "resource": "https://www.geeksforgeeks.org/rate-limiting-algorithms/",
    "resourceTitle": "Rate Limiting",
    "codingProblem": "Design a rate limiter with various algorithms. (Solve in C++. Use bitset<N> or bit manipulation operators (&, |, ^, <<, >>))",
    "testTopic": "Rate limiting",
    "notesTopic": "Rate limiter design"
  },
  {
    "day": 83,
    "week": 12,
    "topic": "Mock Interview 1",
    "difficulty": "hard",
    "videoTitle": "DSA Mock Interview",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "LeetCode Problems",
    "codingProblem": "Solve 2 medium and 1 hard problem under 60 minutes. (Solve in C++. Use bitset<N> or bit manipulation operators (&, |, ^, <<, >>))",
    "testTopic": "Mixed problems",
    "notesTopic": "Interview strategies"
  },
  {
    "day": 84,
    "week": 12,
    "topic": "Mock Interview 2",
    "difficulty": "hard",
    "videoTitle": "Google Interview",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "LeetCode Problems",
    "codingProblem": "Solve 2 medium and 1 hard problem. (Solve in C++. Use bitset<N> or bit manipulation operators (&, |, ^, <<, >>))",
    "testTopic": "Mixed problems",
    "notesTopic": "Company-specific tips"
  },
  {
    "day": 85,
    "week": 12,
    "topic": "Mock Interview 3",
    "difficulty": "hard",
    "videoTitle": "Amazon Interview",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "LeetCode",
    "codingProblem": "Full mock interview with system design. (Solve in C++)",
    "testTopic": "Complete interview",
    "notesTopic": "Mock interview prep"
  },
  {
    "day": 86,
    "week": 12,
    "topic": "Resume & LinkedIn",
    "difficulty": "easy",
    "videoTitle": "Tech Resume",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "LinkedIn Guide",
    "codingProblem": "Update resume with all projects and skills. (Solve in C++. Use bitset<N> or bit manipulation operators (&, |, ^, <<, >>))",
    "testTopic": "Resume dos and donts",
    "notesTopic": "Resume templates"
  },
  {
    "day": 87,
    "week": 12,
    "topic": "Behavioral Interviews",
    "difficulty": "medium",
    "videoTitle": "Behavioral Questions",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Leadership Principles",
    "codingProblem": "Prepare answers to 10 common behavioral questions using STAR. (Solve in C++. Use bitset<N> or bit manipulation operators (&, |, ^, <<, >>))",
    "testTopic": "STAR method",
    "notesTopic": "Behavioral prep"
  },
  {
    "day": 88,
    "week": 12,
    "topic": "Final Review Day 1",
    "difficulty": "hard",
    "videoTitle": "DSA Final Review",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Complete DSA Sheet",
    "codingProblem": "Solve top 10 interview questions. (Solve in C++)",
    "testTopic": "All topics review",
    "notesTopic": "Final review"
  },
  {
    "day": 89,
    "week": 12,
    "topic": "Final Review Day 2",
    "difficulty": "hard",
    "videoTitle": "Final Practice",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "NeetCode 150",
    "codingProblem": "Solve 5 random medium problems. (Solve in C++. Use bitset<N> or bit manipulation operators (&, |, ^, <<, >>))",
    "testTopic": "Random mix",
    "notesTopic": "Last mile prep"
  },
  {
    "day": 90,
    "week": 12,
    "topic": "Graduation Day",
    "difficulty": "easy",
    "videoTitle": "You Made It",
    "resource": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2",
    "resourceTitle": "Continue Grinding",
    "codingProblem": "Apply to 10 companies today. You are ready. (Solve in C++)",
    "testTopic": "Final assessment",
    "notesTopic": "Career next steps"
  }
];
