export const COMPANY_TYPES = {
  service: {
    label: 'Service Company (TCS / Infosys / Wipro)',
    color: '#378ADD',
    icon: '🏢',
    focus: 'Aptitude heavy, basic coding, communication',
    rounds: ['aptitude', 'coding_basic', 'technical_basic', 'hr'],
    difficulty: 'easy-medium',
    passingScore: 65,
    examples: ['TCS', 'Infosys', 'Wipro', 'Cognizant', 'Capgemini', 'Accenture'],
  },
  product: {
    label: 'Product Company (Google / Amazon / Meta)',
    color: '#1D9E75',
    icon: '🏆',
    focus: 'Hard DSA, system design, deep technical',
    rounds: ['coding_hard', 'technical_deep', 'system_design', 'hr'],
    difficulty: 'hard',
    passingScore: 75,
    examples: ['Google', 'Amazon', 'Meta', 'Microsoft', 'Netflix', 'Uber'],
  },
  startup: {
    label: 'Startup (Razorpay / CRED / Swiggy)',
    color: '#7b5cff',
    icon: '⚡',
    focus: 'Practical skills, project deep dive, culture fit',
    rounds: ['coding_medium', 'technical_practical', 'project_deep_dive', 'hr'],
    difficulty: 'medium-hard',
    passingScore: 70,
    examples: ['Razorpay', 'CRED', 'Swiggy', 'Zomato', 'Zerodha', 'Groww'],
  },
  fintech: {
    label: 'Fintech / Bank (Goldman / JP Morgan)',
    color: '#EF9F27',
    icon: '💰',
    focus: 'Strong DSA, problem solving, analytical',
    rounds: ['aptitude', 'coding_hard', 'technical_deep', 'hr'],
    difficulty: 'hard',
    passingScore: 75,
    examples: ['Goldman Sachs', 'JP Morgan', 'Morgan Stanley', 'Deutsche Bank', 'Paytm', 'Razorpay'],
  },
};

export const ROUND_CONFIG = {
  aptitude: {
    label: 'Aptitude Round',
    icon: '🧠',
    duration: 15,
    questionCount: 5,
    promptContext: 'Generate 5 aptitude questions mixing quantitative, logical reasoning and verbal. TCS/Infosys level difficulty.',
  },
  coding_basic: {
    label: 'Basic Coding Round',
    icon: '💻',
    duration: 20,
    questionCount: 3,
    promptContext: 'Generate 3 basic coding problems. Level: loops, arrays, strings, simple logic. Common in service company tests.',
  },
  coding_medium: {
    label: 'Coding Round',
    icon: '💻',
    duration: 30,
    questionCount: 3,
    promptContext: 'Generate 3 medium-level coding problems involving arrays, strings, hashmaps, basic recursion.',
  },
  coding_hard: {
    label: 'Advanced Coding Round',
    icon: '🔥',
    duration: 40,
    questionCount: 3,
    promptContext: 'Generate 3 hard DSA problems (trees, graphs, DP, complex recursion) like actual Google/Amazon interviews.',
  },
  technical_basic: {
    label: 'Technical Interview',
    icon: '🎯',
    duration: 20,
    questionCount: 5,
    promptContext: 'Generate 5 basic CS fundamentals questions covering OOP, DBMS basics, OS basics, networking basics.',
  },
  technical_practical: {
    label: 'Technical Deep Dive',
    icon: '🎯',
    duration: 25,
    questionCount: 5,
    promptContext: 'Generate 5 practical technical questions about web development, databases, APIs, real-world debugging scenarios.',
  },
  technical_deep: {
    label: 'Deep Technical',
    icon: '🔬',
    duration: 35,
    questionCount: 5,
    promptContext: 'Generate 5 deep technical questions covering advanced CS concepts, algorithm complexity, concurrency, tradeoffs.',
  },
  system_design: {
    label: 'System Design',
    icon: '🏛️',
    duration: 45,
    questionCount: 3,
    promptContext: 'Generate 3 system design questions like "design Instagram feed", "design URL shortener". Focus on scalability, tradeoffs, components.',
  },
  project_deep_dive: {
    label: 'Project Deep Dive',
    icon: '📦',
    duration: 20,
    questionCount: 5,
    promptContext: 'Generate 5 project-related questions that test if candidate actually built what they claim. Ask about architecture, tech choices, challenges, scaling.',
  },
  hr: {
    label: 'HR Round',
    icon: '👔',
    duration: 15,
    questionCount: 5,
    promptContext: 'Generate 5 HR behavioral questions. Mix of tell-me-about-yourself, strengths weaknesses, conflict handling, salary expectations, why this company.',
  },
};
