-- NOTE: roadmap.video_url is intentionally seeded NULL. Videos are resolved at
-- read time from the curated map in lib/curatedVideos.js and played in-page;
-- this column previously held youtube.com/results search links, which sent the
-- student off the site. Do not repopulate it.
-- ── INSERT ALL 10 DOMAINS ─────────────────────────
insert into domains (slug, label, icon, color, description) values
('fullstack','Full Stack Development','⬡','#7F77DD','Build complete web applications'),
('dsa','Data Structures & Algorithms','◈','#1D9E75','Master CS fundamentals and problem solving'),
('ml','Machine Learning','◉','#D85A30','Train models and work with data'),
('ai','Artificial Intelligence','◎','#BA7517','Build intelligent systems and AI applications'),
('ds','Data Science','◇','#378ADD','Analyze data and extract insights'),
('cybersec','Cybersecurity','◆','#D4537E','Protect systems and networks'),
('cloud','Cloud Computing','○','#639922','Build and deploy cloud infrastructure'),
('mobile','Mobile App Development','▣','#E24B4A','Create iOS and Android apps'),
('devops','DevOps','▷','#888780','Automate and deploy software'),
('sysdesign','System Design','▦','#534AB7','Design scalable distributed systems')
on conflict (slug) do nothing;

-- ── FULLSTACK: 30 DAYS ────────────────────────────
insert into roadmap (domain_slug,week_number,day_number,topic,description,video_url,resource_url,article_url,difficulty) values
('fullstack',1,1,'HTML Semantics','Learn proper HTML structure and semantic elements',null,'https://developer.mozilla.org/en-US/docs/Web/HTML','https://dev.to/search?q=html+semantics','beginner'),
('fullstack',1,2,'CSS Box Model','Understand margin, padding, border and how elements flow',null,'https://developer.mozilla.org/en-US/docs/Web/CSS/box_model','https://dev.to/search?q=css+box+model','beginner'),
('fullstack',1,3,'Flexbox Layout','Master flexible box layout for modern CSS',null,'https://css-tricks.com/snippets/css/a-guide-to-flexbox/','https://dev.to/search?q=flexbox','beginner'),
('fullstack',1,4,'CSS Grid','Build powerful two-dimensional layouts with Grid',null,'https://css-tricks.com/snippets/css/complete-guide-grid/','https://dev.to/search?q=css+grid','beginner'),
('fullstack',1,5,'JavaScript Basics','Variables, data types, functions and control flow',null,'https://javascript.info/first-steps','https://dev.to/search?q=javascript+basics','beginner'),
('fullstack',1,6,'DOM Manipulation','Select and modify HTML elements with JavaScript',null,'https://javascript.info/dom-nodes','https://dev.to/search?q=dom+manipulation','beginner'),
('fullstack',1,7,'ES6 Plus Features','Arrow functions, destructuring, spread, promises',null,'https://javascript.info/modern-javascript-tutorial','https://dev.to/search?q=es6+features','beginner'),
('fullstack',2,8,'Async JavaScript','Callbacks, promises, async await explained',null,'https://javascript.info/async','https://dev.to/search?q=async+javascript','beginner'),
('fullstack',2,9,'Fetch API and REST','Make HTTP requests and work with APIs',null,'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API','https://dev.to/search?q=fetch+api','beginner'),
('fullstack',2,10,'React Basics','Components, JSX, and React fundamentals',null,'https://react.dev/learn','https://dev.to/search?q=react+basics','beginner'),
('fullstack',2,11,'React Hooks','useState, useEffect, and custom hooks',null,'https://react.dev/reference/react','https://dev.to/search?q=react+hooks','intermediate'),
('fullstack',2,12,'React Router','Client-side routing and navigation in React',null,'https://reactrouter.com/en/main','https://dev.to/search?q=react+router','intermediate'),
('fullstack',2,13,'Forms and Validation','Handle forms and validate user input in React',null,'https://react.dev/reference/react-dom/components/form','https://dev.to/search?q=react+forms','intermediate'),
('fullstack',2,14,'State Management','Global state with Zustand or Context API',null,'https://zustand-demo.pmnd.rs/','https://dev.to/search?q=state+management+react','intermediate'),
('fullstack',3,15,'Node.js Basics','Server-side JavaScript, modules, file system',null,'https://nodejs.org/en/docs/guides','https://dev.to/search?q=nodejs+basics','intermediate'),
('fullstack',3,16,'Express.js Setup','Build REST APIs with Express framework',null,'https://expressjs.com/en/starter/hello-world.html','https://dev.to/search?q=express+js','intermediate'),
('fullstack',3,17,'REST API Design','Best practices for designing REST APIs',null,'https://restfulapi.net/','https://dev.to/search?q=rest+api+design','intermediate'),
('fullstack',3,18,'JWT Authentication','Secure your APIs with JSON Web Tokens',null,'https://jwt.io/introduction','https://dev.to/search?q=jwt+authentication','intermediate'),
('fullstack',3,19,'Middleware and Error Handling','Express middleware patterns and error handling',null,'https://expressjs.com/en/guide/using-middleware.html','https://dev.to/search?q=express+middleware','intermediate'),
('fullstack',3,20,'Database Basics','SQL fundamentals and database design',null,'https://www.postgresql.org/docs/current/tutorial.html','https://dev.to/search?q=sql+basics','intermediate'),
('fullstack',3,21,'PostgreSQL and ORM','Work with PostgreSQL using Prisma ORM',null,'https://www.prisma.io/docs/getting-started','https://dev.to/search?q=prisma+postgresql','intermediate'),
('fullstack',4,22,'File Uploads','Handle file uploads with Multer and cloud storage',null,'https://github.com/expressjs/multer','https://dev.to/search?q=file+upload+nodejs','advanced'),
('fullstack',4,23,'Email Integration','Send emails with Nodemailer and templates',null,'https://nodemailer.com/about/','https://dev.to/search?q=nodemailer','advanced'),
('fullstack',4,24,'Testing with Jest','Unit and integration testing in JavaScript',null,'https://jestjs.io/docs/getting-started','https://dev.to/search?q=jest+testing','advanced'),
('fullstack',4,25,'Docker Basics','Containerize your applications with Docker',null,'https://docs.docker.com/get-started/','https://dev.to/search?q=docker+basics','advanced'),
('fullstack',4,26,'Deployment on Railway','Deploy Node.js apps to Railway platform',null,'https://docs.railway.app/','https://dev.to/search?q=railway+deployment','advanced'),
('fullstack',4,27,'CI/CD with GitHub Actions','Automate testing and deployment pipelines',null,'https://docs.github.com/en/actions','https://dev.to/search?q=github+actions','advanced'),
('fullstack',4,28,'Performance Optimization','Optimize React and Node.js applications',null,'https://react.dev/learn/render-and-commit','https://dev.to/search?q=react+performance','advanced'),
('fullstack',5,29,'Full Stack Capstone','Build a complete full stack application',null,'https://react.dev/learn','https://dev.to/search?q=full+stack+project','advanced'),
('fullstack',5,30,'Portfolio and Resume','Polish your portfolio and prepare your resume',null,'https://docs.github.com/en/pages','https://dev.to/search?q=developer+portfolio','advanced')
on conflict (domain_slug, day_number) do nothing;

-- ── DSA: 30 DAYS ──────────────────────────────────
insert into roadmap (domain_slug,week_number,day_number,topic,description,video_url,resource_url,article_url,difficulty) values
('dsa',1,1,'Big O Notation','Time and space complexity analysis',null,'https://www.bigocheatsheet.com/','https://dev.to/search?q=big+o+notation','beginner'),
('dsa',1,2,'Arrays and Sliding Window','Array operations and sliding window pattern',null,'https://neetcode.io/roadmap','https://dev.to/search?q=sliding+window','beginner'),
('dsa',1,3,'Two Pointers','Two pointer technique for array problems',null,'https://neetcode.io/roadmap','https://dev.to/search?q=two+pointers','beginner'),
('dsa',1,4,'Binary Search','Search sorted arrays in O(log n) time',null,'https://neetcode.io/roadmap','https://dev.to/search?q=binary+search','beginner'),
('dsa',1,5,'Linked Lists','Singly and doubly linked list operations',null,'https://neetcode.io/roadmap','https://dev.to/search?q=linked+list','beginner'),
('dsa',1,6,'Stacks and Queues','Stack and queue data structures and uses',null,'https://neetcode.io/roadmap','https://dev.to/search?q=stack+queue','beginner'),
('dsa',1,7,'Hash Maps and Sets','Hash table internals and common patterns',null,'https://neetcode.io/roadmap','https://dev.to/search?q=hash+map','beginner'),
('dsa',2,8,'Recursion','Recursive thinking and base cases',null,'https://neetcode.io/roadmap','https://dev.to/search?q=recursion','beginner'),
('dsa',2,9,'Trees and BST','Binary trees and binary search trees',null,'https://neetcode.io/roadmap','https://dev.to/search?q=binary+tree','beginner'),
('dsa',2,10,'Level Order BFS','Breadth first search on trees',null,'https://neetcode.io/roadmap','https://dev.to/search?q=bfs+tree','beginner'),
('dsa',2,11,'DFS and Backtracking','Depth first search and backtracking',null,'https://neetcode.io/roadmap','https://dev.to/search?q=dfs+backtracking','intermediate'),
('dsa',2,12,'Graphs','Graph representation and traversal',null,'https://neetcode.io/roadmap','https://dev.to/search?q=graphs+programming','intermediate'),
('dsa',2,13,'Topological Sort','Ordering directed acyclic graphs',null,'https://neetcode.io/roadmap','https://dev.to/search?q=topological+sort','intermediate'),
('dsa',2,14,'Union Find','Disjoint set union data structure',null,'https://neetcode.io/roadmap','https://dev.to/search?q=union+find','intermediate'),
('dsa',3,15,'Dynamic Programming Basics','Memoization and tabulation fundamentals',null,'https://neetcode.io/roadmap','https://dev.to/search?q=dynamic+programming','intermediate'),
('dsa',3,16,'Knapsack Problem','Classic DP pattern for optimization',null,'https://neetcode.io/roadmap','https://dev.to/search?q=knapsack+problem','intermediate'),
('dsa',3,17,'Longest Common Subsequence','LCS and string DP problems',null,'https://neetcode.io/roadmap','https://dev.to/search?q=lcs+dp','intermediate'),
('dsa',3,18,'Greedy Algorithms','Greedy choice property and examples',null,'https://neetcode.io/roadmap','https://dev.to/search?q=greedy+algorithms','intermediate'),
('dsa',3,19,'Intervals','Interval merge and overlap problems',null,'https://neetcode.io/roadmap','https://dev.to/search?q=interval+problems','intermediate'),
('dsa',3,20,'Bit Manipulation','Bitwise operations and tricks',null,'https://neetcode.io/roadmap','https://dev.to/search?q=bit+manipulation','intermediate'),
('dsa',3,21,'Math and Number Theory','GCD, prime numbers, modular arithmetic',null,'https://neetcode.io/roadmap','https://dev.to/search?q=number+theory','intermediate'),
('dsa',4,22,'Heaps and Priority Queue','Min and max heap operations',null,'https://neetcode.io/roadmap','https://dev.to/search?q=heap+data+structure','advanced'),
('dsa',4,23,'Trie Data Structure','Prefix tree for string problems',null,'https://neetcode.io/roadmap','https://dev.to/search?q=trie+data+structure','advanced'),
('dsa',4,24,'Segment Tree','Range query data structure',null,'https://neetcode.io/roadmap','https://dev.to/search?q=segment+tree','advanced'),
('dsa',4,25,'Merge Sort','Divide and conquer sorting algorithm',null,'https://neetcode.io/roadmap','https://dev.to/search?q=merge+sort','advanced'),
('dsa',4,26,'Quick Sort','Partition-based sorting algorithm',null,'https://neetcode.io/roadmap','https://dev.to/search?q=quick+sort','advanced'),
('dsa',4,27,'String Algorithms','KMP, Rabin-Karp, string matching',null,'https://neetcode.io/roadmap','https://dev.to/search?q=string+algorithms','advanced'),
('dsa',4,28,'Advanced Graph Algorithms','Dijkstra, Bellman-Ford, Floyd-Warshall',null,'https://neetcode.io/roadmap','https://dev.to/search?q=dijkstra+algorithm','advanced'),
('dsa',5,29,'Mock Interview Day 1','Solve 5 medium problems under timed conditions',null,'https://leetcode.com/interview/','https://dev.to/search?q=coding+interview','advanced'),
('dsa',5,30,'Mock Interview Day 2','Final mock with hard problems and review',null,'https://leetcode.com/interview/','https://dev.to/search?q=technical+interview','advanced')
on conflict (domain_slug, day_number) do nothing;

-- ── ML: 30 DAYS ───────────────────────────────────
insert into roadmap (domain_slug,week_number,day_number,topic,description,video_url,resource_url,article_url,difficulty) values
('ml',1,1,'Python for ML','NumPy, Pandas basics for machine learning',null,'https://numpy.org/doc/stable/','https://dev.to/search?q=python+machine+learning','beginner'),
('ml',1,2,'NumPy Arrays','Array operations and linear algebra with NumPy',null,'https://numpy.org/doc/stable/user/quickstart.html','https://dev.to/search?q=numpy+tutorial','beginner'),
('ml',1,3,'Pandas DataFrames','Data manipulation and analysis with Pandas',null,'https://pandas.pydata.org/docs/user_guide/index.html','https://dev.to/search?q=pandas+tutorial','beginner'),
('ml',1,4,'Data Visualization','Matplotlib and Seaborn for data plots',null,'https://matplotlib.org/stable/tutorials/index.html','https://dev.to/search?q=matplotlib+tutorial','beginner'),
('ml',1,5,'Statistics Fundamentals','Mean, variance, distributions for ML',null,'https://scipy.org/docs.html','https://dev.to/search?q=statistics+machine+learning','beginner'),
('ml',1,6,'Probability Theory','Bayes theorem and probability for ML',null,'https://scipy.org/docs.html','https://dev.to/search?q=probability+machine+learning','beginner'),
('ml',1,7,'Linear Algebra for ML','Vectors, matrices, and transformations',null,'https://numpy.org/doc/stable/reference/routines.linalg.html','https://dev.to/search?q=linear+algebra+ml','beginner'),
('ml',2,8,'Linear Regression','Predict continuous values with regression',null,'https://scikit-learn.org/stable/modules/linear_model.html','https://dev.to/search?q=linear+regression','beginner'),
('ml',2,9,'Logistic Regression','Binary classification with logistic regression',null,'https://scikit-learn.org/stable/modules/linear_model.html','https://dev.to/search?q=logistic+regression','beginner'),
('ml',2,10,'Decision Trees','Tree-based classification and regression',null,'https://scikit-learn.org/stable/modules/tree.html','https://dev.to/search?q=decision+tree','beginner'),
('ml',2,11,'Random Forest','Ensemble of decision trees explained',null,'https://scikit-learn.org/stable/modules/ensemble.html','https://dev.to/search?q=random+forest','intermediate'),
('ml',2,12,'Support Vector Machine','SVM for classification problems',null,'https://scikit-learn.org/stable/modules/svm.html','https://dev.to/search?q=svm+machine+learning','intermediate'),
('ml',2,13,'K-Nearest Neighbors','KNN algorithm for classification',null,'https://scikit-learn.org/stable/modules/neighbors.html','https://dev.to/search?q=knn+algorithm','intermediate'),
('ml',2,14,'Naive Bayes','Probabilistic classifier based on Bayes theorem',null,'https://scikit-learn.org/stable/modules/naive_bayes.html','https://dev.to/search?q=naive+bayes','intermediate'),
('ml',3,15,'Neural Networks Basics','Neurons, layers, activation functions',null,'https://www.tensorflow.org/guide/keras','https://dev.to/search?q=neural+networks','intermediate'),
('ml',3,16,'Backpropagation','How neural networks learn with gradient descent',null,'https://www.tensorflow.org/guide/autodiff','https://dev.to/search?q=backpropagation','intermediate'),
('ml',3,17,'TensorFlow and Keras','Build and train neural networks with Keras',null,'https://www.tensorflow.org/tutorials','https://dev.to/search?q=tensorflow+keras','intermediate'),
('ml',3,18,'CNN Architecture','Convolutional neural networks for images',null,'https://www.tensorflow.org/tutorials/images/cnn','https://dev.to/search?q=cnn+deep+learning','intermediate'),
('ml',3,19,'RNN and LSTM','Recurrent networks for sequential data',null,'https://www.tensorflow.org/guide/keras/rnn','https://dev.to/search?q=rnn+lstm','advanced'),
('ml',3,20,'NLP Basics','Text preprocessing and classification',null,'https://www.nltk.org/book/','https://dev.to/search?q=nlp+basics','advanced'),
('ml',3,21,'Feature Engineering','Create better features for ML models',null,'https://scikit-learn.org/stable/modules/preprocessing.html','https://dev.to/search?q=feature+engineering','advanced'),
('ml',4,22,'Model Evaluation','Accuracy, precision, recall, F1 score',null,'https://scikit-learn.org/stable/modules/model_evaluation.html','https://dev.to/search?q=model+evaluation','advanced'),
('ml',4,23,'Cross Validation','K-fold validation to prevent overfitting',null,'https://scikit-learn.org/stable/modules/cross_validation.html','https://dev.to/search?q=cross+validation','advanced'),
('ml',4,24,'Hyperparameter Tuning','Grid search and random search for tuning',null,'https://scikit-learn.org/stable/modules/grid_search.html','https://dev.to/search?q=hyperparameter+tuning','advanced'),
('ml',4,25,'Ensemble Methods','Boosting and bagging techniques',null,'https://scikit-learn.org/stable/modules/ensemble.html','https://dev.to/search?q=ensemble+methods','advanced'),
('ml',4,26,'Dimensionality Reduction','PCA and t-SNE for high dimensional data',null,'https://scikit-learn.org/stable/modules/decomposition.html','https://dev.to/search?q=pca+machine+learning','advanced'),
('ml',4,27,'MLOps Basics','Version control for models and data',null,'https://mlflow.org/docs/latest/index.html','https://dev.to/search?q=mlops+basics','advanced'),
('ml',4,28,'ML Project Pipeline','End to end machine learning workflow',null,'https://scikit-learn.org/stable/modules/pipeline.html','https://dev.to/search?q=ml+pipeline','advanced'),
('ml',5,29,'End to End ML Project','Build a complete ML project from scratch',null,'https://scikit-learn.org/stable/getting_started.html','https://dev.to/search?q=ml+project','advanced'),
('ml',5,30,'Model Deployment with FastAPI','Deploy ML model as REST API',null,'https://fastapi.tiangolo.com/tutorial/','https://dev.to/search?q=model+deployment+fastapi','advanced')
on conflict (domain_slug, day_number) do nothing;

-- -- AI: 30 DAYS -----------------------------------
insert into roadmap (domain_slug,week_number,day_number,topic,description,video_url,resource_url,article_url,difficulty) values
('ai',1,1,'AI Fundamentals','History and overview of artificial intelligence',null,'https://ai.google/education/','https://dev.to/search?q=ai+fundamentals','beginner'),
('ai',1,2,'Search Algorithms','BFS DFS and uninformed search',null,'https://aima.cs.berkeley.edu/','https://dev.to/search?q=ai+search+algorithms','beginner'),
('ai',1,3,'A Star Search','Heuristic search and pathfinding',null,'https://aima.cs.berkeley.edu/','https://dev.to/search?q=a+star+algorithm','beginner'),
('ai',1,4,'Game Theory','Minimax and adversarial search',null,'https://aima.cs.berkeley.edu/','https://dev.to/search?q=minimax+algorithm','beginner'),
('ai',1,5,'Knowledge Representation','Logic and knowledge bases in AI',null,'https://aima.cs.berkeley.edu/','https://dev.to/search?q=knowledge+representation','beginner'),
('ai',1,6,'Propositional Logic','Boolean logic for AI reasoning',null,'https://aima.cs.berkeley.edu/','https://dev.to/search?q=propositional+logic+ai','beginner'),
('ai',1,7,'First Order Logic','Predicate logic and inference rules',null,'https://aima.cs.berkeley.edu/','https://dev.to/search?q=first+order+logic','beginner'),
('ai',2,8,'Bayesian Networks','Probabilistic graphical models',null,'https://www.cs.cmu.edu/~awm/tutorials/','https://dev.to/search?q=bayesian+networks','beginner'),
('ai',2,9,'Reinforcement Learning','Agents learning from rewards',null,'https://spinningup.openai.com/','https://dev.to/search?q=reinforcement+learning','beginner'),
('ai',2,10,'Deep Learning Foundations','Neural networks for AI applications',null,'https://www.deeplearning.ai/','https://dev.to/search?q=deep+learning+foundations','beginner'),
('ai',2,11,'Transformer Architecture','Self attention and transformer models',null,'https://huggingface.co/docs/transformers/','https://dev.to/search?q=transformer+architecture','intermediate'),
('ai',2,12,'BERT and GPT','Pre-trained language models explained',null,'https://huggingface.co/docs/transformers/','https://dev.to/search?q=bert+gpt+models','intermediate'),
('ai',2,13,'LLMs and Prompt Engineering','Large language models and prompting',null,'https://platform.openai.com/docs/guides/prompt-engineering','https://dev.to/search?q=prompt+engineering','intermediate'),
('ai',2,14,'RAG Systems','Retrieval augmented generation explained',null,'https://docs.anthropic.com/','https://dev.to/search?q=rag+systems','intermediate'),
('ai',3,15,'AI Agents','Autonomous AI agents and tool use',null,'https://docs.anthropic.com/','https://dev.to/search?q=ai+agents','intermediate'),
('ai',3,16,'Vector Databases','Store and search embeddings efficiently',null,'https://www.pinecone.io/learn/','https://dev.to/search?q=vector+database','intermediate'),
('ai',3,17,'LangChain Basics','Build LLM applications with LangChain',null,'https://python.langchain.com/docs/get_started/introduction','https://dev.to/search?q=langchain+tutorial','intermediate'),
('ai',3,18,'Fine Tuning LLMs','Customize LLMs for specific tasks',null,'https://huggingface.co/docs/transformers/training','https://dev.to/search?q=fine+tuning+llm','advanced'),
('ai',3,19,'Computer Vision AI','Image recognition and object detection',null,'https://pytorch.org/vision/stable/index.html','https://dev.to/search?q=computer+vision+ai','advanced'),
('ai',3,20,'NLP Applications','Text classification and sentiment analysis',null,'https://huggingface.co/docs/transformers/tasks/sequence_classification','https://dev.to/search?q=nlp+applications','advanced'),
('ai',3,21,'Generative AI','Image and text generation with AI',null,'https://stability.ai/research','https://dev.to/search?q=generative+ai','advanced'),
('ai',4,22,'AI System Design','Architecture patterns for AI systems',null,'https://docs.anthropic.com/','https://dev.to/search?q=ai+system+design','advanced'),
('ai',4,23,'AI APIs Integration','Use Anthropic, OpenAI APIs in projects',null,'https://docs.anthropic.com/en/api/getting-started','https://dev.to/search?q=anthropic+api','advanced'),
('ai',4,24,'AI Safety and Ethics','Responsible AI development practices',null,'https://www.anthropic.com/research','https://dev.to/search?q=ai+safety+ethics','advanced'),
('ai',4,25,'Evaluating AI Systems','Benchmarks and evaluation methods',null,'https://www.anthropic.com/research','https://dev.to/search?q=ai+evaluation','advanced'),
('ai',4,26,'Production AI Systems','Deploy and monitor AI in production',null,'https://docs.anthropic.com/','https://dev.to/search?q=production+ai','advanced'),
('ai',4,27,'Multi-modal AI','AI that handles text images and audio',null,'https://docs.anthropic.com/en/docs/vision','https://dev.to/search?q=multimodal+ai','advanced'),
('ai',4,28,'AI Research Reading','Read and understand AI research papers',null,'https://arxiv.org/cs/AI','https://dev.to/search?q=ai+research+papers','advanced'),
('ai',5,29,'AI Project Build','Build a complete AI-powered application',null,'https://docs.anthropic.com/','https://dev.to/search?q=ai+project+build','advanced'),
('ai',5,30,'AI Career Roadmap','Jobs skills and path in AI field',null,'https://roadmap.sh/ai-data-scientist','https://dev.to/search?q=ai+career','advanced')
on conflict (domain_slug, day_number) do nothing;

-- -- DS: 30 DAYS -----------------------------------
insert into roadmap (domain_slug,week_number,day_number,topic,description,video_url,resource_url,article_url,difficulty) values
('ds',1,1,'Python for Data Science','Setup Python environment for data analysis',null,'https://pandas.pydata.org/docs/','https://dev.to/search?q=python+data+science','beginner'),
('ds',1,2,'NumPy Deep Dive','Advanced array operations for data science',null,'https://numpy.org/doc/stable/user/absolute_beginners.html','https://dev.to/search?q=numpy+data+science','beginner'),
('ds',1,3,'Pandas Advanced','GroupBy, merge, pivot tables in Pandas',null,'https://pandas.pydata.org/docs/user_guide/groupby.html','https://dev.to/search?q=pandas+advanced','beginner'),
('ds',1,4,'Data Cleaning','Handle missing data and outliers',null,'https://pandas.pydata.org/docs/user_guide/missing_data.html','https://dev.to/search?q=data+cleaning','beginner'),
('ds',1,5,'Exploratory Data Analysis','EDA techniques to understand datasets',null,'https://pandas.pydata.org/docs/user_guide/visualization.html','https://dev.to/search?q=eda+data+science','beginner'),
('ds',1,6,'Matplotlib and Seaborn','Data visualization with Python libraries',null,'https://seaborn.pydata.org/tutorial.html','https://dev.to/search?q=matplotlib+seaborn','beginner'),
('ds',1,7,'Plotly Interactive Viz','Interactive charts and dashboards',null,'https://plotly.com/python/','https://dev.to/search?q=plotly+python','beginner'),
('ds',2,8,'Statistics for DS','Descriptive and inferential statistics',null,'https://scipy.org/docs.html','https://dev.to/search?q=statistics+data+science','beginner'),
('ds',2,9,'Hypothesis Testing','T-test, chi-square and statistical tests',null,'https://scipy.org/docs.html','https://dev.to/search?q=hypothesis+testing','beginner'),
('ds',2,10,'SQL for Data Science','Query databases for data analysis',null,'https://mode.com/sql-tutorial/','https://dev.to/search?q=sql+data+science','beginner'),
('ds',2,11,'Advanced SQL','Window functions, CTEs, complex queries',null,'https://mode.com/sql-tutorial/sql-window-functions/','https://dev.to/search?q=advanced+sql','intermediate'),
('ds',2,12,'A/B Testing','Design and analyze experiments',null,'https://www.optimizely.com/optimization-glossary/ab-testing/','https://dev.to/search?q=ab+testing','intermediate'),
('ds',2,13,'Data Wrangling','Transform and reshape data for analysis',null,'https://pandas.pydata.org/docs/user_guide/reshaping.html','https://dev.to/search?q=data+wrangling','intermediate'),
('ds',2,14,'Feature Engineering','Create features for machine learning',null,'https://scikit-learn.org/stable/modules/preprocessing.html','https://dev.to/search?q=feature+engineering','intermediate'),
('ds',3,15,'Regression Analysis','Linear and multiple regression models',null,'https://scikit-learn.org/stable/modules/linear_model.html','https://dev.to/search?q=regression+analysis','intermediate'),
('ds',3,16,'Classification Methods','Logistic regression and tree classifiers',null,'https://scikit-learn.org/stable/supervised_learning.html','https://dev.to/search?q=classification+data+science','intermediate'),
('ds',3,17,'Clustering Techniques','K-means and hierarchical clustering',null,'https://scikit-learn.org/stable/modules/clustering.html','https://dev.to/search?q=clustering+python','intermediate'),
('ds',3,18,'Time Series Analysis','Forecast trends with time series data',null,'https://www.statsmodels.org/stable/tsa.html','https://dev.to/search?q=time+series+python','intermediate'),
('ds',3,19,'Storytelling with Data','Communicate insights effectively',null,'https://www.storytellingwithdata.com/','https://dev.to/search?q=data+storytelling','intermediate'),
('ds',3,20,'Dashboard Design','Build interactive data dashboards',null,'https://plotly.com/dash/','https://dev.to/search?q=dashboard+design','advanced'),
('ds',3,21,'Tableau Basics','Create visualizations with Tableau',null,'https://help.tableau.com/current/guides/get-started-tutorial/en-us/get-started-tutorial-home.htm','https://dev.to/search?q=tableau+tutorial','advanced'),
('ds',4,22,'Big Data Concepts','Hadoop, Spark and distributed computing',null,'https://spark.apache.org/docs/latest/','https://dev.to/search?q=big+data+concepts','advanced'),
('ds',4,23,'Apache Spark Basics','Process large datasets with PySpark',null,'https://spark.apache.org/docs/latest/api/python/','https://dev.to/search?q=apache+spark','advanced'),
('ds',4,24,'Data Pipelines and ETL','Build automated data pipelines',null,'https://airflow.apache.org/docs/','https://dev.to/search?q=data+pipeline+etl','advanced'),
('ds',4,25,'Data Warehousing','Design star schemas and data warehouses',null,'https://docs.snowflake.com/en/user-guide/intro-key-concepts','https://dev.to/search?q=data+warehousing','advanced'),
('ds',4,26,'Cloud Data Tools','BigQuery Redshift and cloud analytics',null,'https://cloud.google.com/bigquery/docs','https://dev.to/search?q=bigquery+tutorial','advanced'),
('ds',4,27,'ML Model Building','End to end model for data science',null,'https://scikit-learn.org/stable/getting_started.html','https://dev.to/search?q=ml+model+data+science','advanced'),
('ds',4,28,'Model Deployment','Deploy data science models to production',null,'https://fastapi.tiangolo.com/','https://dev.to/search?q=model+deployment','advanced'),
('ds',5,29,'Capstone Data Project','End to end data science project',null,'https://kaggle.com','https://dev.to/search?q=data+science+project','advanced'),
('ds',5,30,'DS Portfolio and Interview','Build portfolio and prepare for interviews',null,'https://kaggle.com','https://dev.to/search?q=data+science+interview','advanced')
on conflict (domain_slug, day_number) do nothing;

-- -- CYBERSEC: 30 DAYS -----------------------------
insert into roadmap (domain_slug,week_number,day_number,topic,description,video_url,resource_url,article_url,difficulty) values
('cybersec',1,1,'Cybersecurity Fundamentals','Core concepts of information security',null,'https://www.cybrary.it/','https://dev.to/search?q=cybersecurity+basics','beginner'),
('cybersec',1,2,'Networking Basics','TCP IP DNS HTTP protocols explained',null,'https://www.cloudflare.com/learning/network-layer/what-is-the-network-layer/','https://dev.to/search?q=networking+basics','beginner'),
('cybersec',1,3,'Linux Command Line','Essential Linux commands for security',null,'https://linuxcommand.org/','https://dev.to/search?q=linux+commands','beginner'),
('cybersec',1,4,'HTTP and HTTPS','Web protocol security and encryption',null,'https://developer.mozilla.org/en-US/docs/Web/HTTP','https://dev.to/search?q=http+https+security','beginner'),
('cybersec',1,5,'Firewalls and IDS','Network security tools and configurations',null,'https://www.cisco.com/c/en/us/products/security/firewalls/what-is-a-firewall.html','https://dev.to/search?q=firewall+security','beginner'),
('cybersec',1,6,'Cryptography Basics','Encryption decryption and hashing',null,'https://www.cloudflare.com/learning/ssl/what-is-encryption/','https://dev.to/search?q=cryptography+basics','beginner'),
('cybersec',1,7,'PKI and Certificates','Public key infrastructure and SSL',null,'https://www.cloudflare.com/learning/ssl/what-is-ssl/','https://dev.to/search?q=pki+certificates','beginner'),
('cybersec',2,8,'OWASP Top 10','Top web application security risks',null,'https://owasp.org/www-project-top-ten/','https://dev.to/search?q=owasp+top+10','beginner'),
('cybersec',2,9,'SQL Injection','Attack and defense against SQLi',null,'https://owasp.org/www-community/attacks/SQL_Injection','https://dev.to/search?q=sql+injection','beginner'),
('cybersec',2,10,'XSS and CSRF','Cross site scripting and request forgery',null,'https://owasp.org/www-community/attacks/xss/','https://dev.to/search?q=xss+csrf','beginner'),
('cybersec',2,11,'Authentication Attacks','Brute force and credential stuffing',null,'https://owasp.org/www-project-top-ten/','https://dev.to/search?q=authentication+attacks','intermediate'),
('cybersec',2,12,'Penetration Testing Basics','Ethical hacking methodology',null,'https://www.offensive-security.com/metasploit-unleashed/','https://dev.to/search?q=penetration+testing','intermediate'),
('cybersec',2,13,'Nmap and Reconnaissance','Network scanning and enumeration',null,'https://nmap.org/docs.html','https://dev.to/search?q=nmap+tutorial','intermediate'),
('cybersec',2,14,'Burp Suite','Web application security testing tool',null,'https://portswigger.net/burp/documentation','https://dev.to/search?q=burp+suite','intermediate'),
('cybersec',3,15,'Metasploit Framework','Exploit development and testing',null,'https://www.offensive-security.com/metasploit-unleashed/','https://dev.to/search?q=metasploit','intermediate'),
('cybersec',3,16,'Wireless Security','WiFi attacks and WPA2 security',null,'https://www.aircrack-ng.org/documentation.html','https://dev.to/search?q=wireless+security','intermediate'),
('cybersec',3,17,'Social Engineering','Phishing and human-based attacks',null,'https://www.social-engineer.org/framework/general-discussion/','https://dev.to/search?q=social+engineering','intermediate'),
('cybersec',3,18,'Malware Analysis','Analyze and reverse engineer malware',null,'https://any.run/','https://dev.to/search?q=malware+analysis','advanced'),
('cybersec',3,19,'Digital Forensics','Investigate security incidents',null,'https://www.autopsy.com/','https://dev.to/search?q=digital+forensics','advanced'),
('cybersec',3,20,'Incident Response','Handle and recover from security breaches',null,'https://www.sans.org/white-papers/33901/','https://dev.to/search?q=incident+response','advanced'),
('cybersec',3,21,'Cloud Security','Secure AWS Azure and GCP environments',null,'https://docs.aws.amazon.com/security/','https://dev.to/search?q=cloud+security','advanced'),
('cybersec',4,22,'DevSecOps','Security in CI/CD pipelines',null,'https://owasp.org/www-project-devsecops-guideline/','https://dev.to/search?q=devsecops','advanced'),
('cybersec',4,23,'Security Compliance','GDPR PCI DSS and compliance frameworks',null,'https://www.nist.gov/cyberframework','https://dev.to/search?q=security+compliance','advanced'),
('cybersec',4,24,'Threat Intelligence','Gather and analyze threat data',null,'https://attack.mitre.org/','https://dev.to/search?q=threat+intelligence','advanced'),
('cybersec',4,25,'CTF Challenges','Capture the flag competition practice',null,'https://ctftime.org/','https://dev.to/search?q=ctf+challenges','advanced'),
('cybersec',4,26,'Zero Day Vulnerabilities','Understanding and disclosing zero days',null,'https://nvd.nist.gov/','https://dev.to/search?q=zero+day+vulnerability','advanced'),
('cybersec',4,27,'Bug Bounty Programs','Find bugs and earn money legally',null,'https://www.hackerone.com/','https://dev.to/search?q=bug+bounty','advanced'),
('cybersec',4,28,'Security Certifications','CEH OSCP and certification paths',null,'https://www.offensive-security.com/pwk-oscp/','https://dev.to/search?q=security+certification','advanced'),
('cybersec',5,29,'Security Audit Project','Perform a full security audit',null,'https://owasp.org/','https://dev.to/search?q=security+audit','advanced'),
('cybersec',5,30,'Cybersecurity Career Path','Jobs roles and skills in security',null,'https://roadmap.sh/cyber-security','https://dev.to/search?q=cybersecurity+career','advanced')
on conflict (domain_slug, day_number) do nothing;

-- -- CLOUD: 30 DAYS --------------------------------
insert into roadmap (domain_slug,week_number,day_number,topic,description,video_url,resource_url,article_url,difficulty) values
('cloud',1,1,'Cloud Fundamentals','IaaS PaaS SaaS and cloud concepts',null,'https://aws.amazon.com/what-is-cloud-computing/','https://dev.to/search?q=cloud+fundamentals','beginner'),
('cloud',1,2,'AWS Basics','Navigate AWS console and core services',null,'https://aws.amazon.com/getting-started/','https://dev.to/search?q=aws+basics','beginner'),
('cloud',1,3,'EC2 Instances','Launch and manage virtual servers',null,'https://docs.aws.amazon.com/ec2/','https://dev.to/search?q=aws+ec2','beginner'),
('cloud',1,4,'S3 Storage','Object storage for files and backups',null,'https://docs.aws.amazon.com/s3/','https://dev.to/search?q=aws+s3','beginner'),
('cloud',1,5,'IAM and Security','Identity and access management on AWS',null,'https://docs.aws.amazon.com/IAM/latest/UserGuide/','https://dev.to/search?q=aws+iam','beginner'),
('cloud',1,6,'VPC Networking','Virtual private cloud and networking',null,'https://docs.aws.amazon.com/vpc/','https://dev.to/search?q=aws+vpc','beginner'),
('cloud',1,7,'Route 53 DNS','Domain management and routing',null,'https://docs.aws.amazon.com/route53/','https://dev.to/search?q=aws+route53','beginner'),
('cloud',2,8,'RDS Database','Managed relational database on AWS',null,'https://docs.aws.amazon.com/rds/','https://dev.to/search?q=aws+rds','beginner'),
('cloud',2,9,'DynamoDB','NoSQL database service on AWS',null,'https://docs.aws.amazon.com/dynamodb/','https://dev.to/search?q=dynamodb+tutorial','beginner'),
('cloud',2,10,'Lambda Serverless','Run code without managing servers',null,'https://docs.aws.amazon.com/lambda/','https://dev.to/search?q=aws+lambda','beginner'),
('cloud',2,11,'API Gateway','Create and manage REST APIs on AWS',null,'https://docs.aws.amazon.com/apigateway/','https://dev.to/search?q=aws+api+gateway','intermediate'),
('cloud',2,12,'Docker Containers','Containerize applications with Docker',null,'https://docs.docker.com/get-started/','https://dev.to/search?q=docker+tutorial','intermediate'),
('cloud',2,13,'CloudFormation','Infrastructure as code with CloudFormation',null,'https://docs.aws.amazon.com/cloudformation/','https://dev.to/search?q=cloudformation','intermediate'),
('cloud',2,14,'SQS and SNS','Message queuing and notifications on AWS',null,'https://docs.aws.amazon.com/sqs/','https://dev.to/search?q=aws+sqs+sns','intermediate'),
('cloud',3,15,'Kubernetes Basics','Container orchestration with Kubernetes',null,'https://kubernetes.io/docs/tutorials/','https://dev.to/search?q=kubernetes+basics','intermediate'),
('cloud',3,16,'EKS on AWS','Managed Kubernetes service on AWS',null,'https://docs.aws.amazon.com/eks/','https://dev.to/search?q=aws+eks','intermediate'),
('cloud',3,17,'Terraform IaC','Infrastructure as code with Terraform',null,'https://developer.hashicorp.com/terraform/docs','https://dev.to/search?q=terraform+tutorial','intermediate'),
('cloud',3,18,'Cloud Monitoring','CloudWatch metrics alerts and logs',null,'https://docs.aws.amazon.com/cloudwatch/','https://dev.to/search?q=aws+cloudwatch','intermediate'),
('cloud',3,19,'Auto Scaling','Scale applications automatically',null,'https://docs.aws.amazon.com/autoscaling/','https://dev.to/search?q=aws+autoscaling','intermediate'),
('cloud',3,20,'Load Balancing','Distribute traffic with ALB and NLB',null,'https://docs.aws.amazon.com/elasticloadbalancing/','https://dev.to/search?q=aws+load+balancer','advanced'),
('cloud',3,21,'CloudFront CDN','Content delivery and caching globally',null,'https://docs.aws.amazon.com/cloudfront/','https://dev.to/search?q=aws+cloudfront','advanced'),
('cloud',4,22,'Azure Fundamentals','Microsoft Azure core services overview',null,'https://learn.microsoft.com/en-us/azure/','https://dev.to/search?q=azure+fundamentals','advanced'),
('cloud',4,23,'GCP Basics','Google Cloud Platform fundamentals',null,'https://cloud.google.com/docs','https://dev.to/search?q=gcp+basics','advanced'),
('cloud',4,24,'Multi-cloud Strategy','Work across multiple cloud providers',null,'https://aws.amazon.com/partners/work-with-aws/','https://dev.to/search?q=multi+cloud','advanced'),
('cloud',4,25,'Cloud Security','Secure cloud infrastructure and data',null,'https://docs.aws.amazon.com/security/','https://dev.to/search?q=cloud+security','advanced'),
('cloud',4,26,'Cost Optimization','Reduce and optimize cloud spending',null,'https://aws.amazon.com/aws-cost-management/','https://dev.to/search?q=aws+cost+optimization','advanced'),
('cloud',4,27,'Serverless Architecture','Design serverless applications',null,'https://www.serverless.com/framework/docs','https://dev.to/search?q=serverless+architecture','advanced'),
('cloud',4,28,'Site Reliability Engineering','SRE principles and practices',null,'https://sre.google/books/','https://dev.to/search?q=sre+practices','advanced'),
('cloud',5,29,'Cloud Deployment Project','Deploy a full application to AWS',null,'https://docs.aws.amazon.com/','https://dev.to/search?q=aws+deployment','advanced'),
('cloud',5,30,'AWS Certification Prep','Prepare for AWS Solutions Architect exam',null,'https://aws.amazon.com/certification/','https://dev.to/search?q=aws+certification','advanced')
on conflict (domain_slug, day_number) do nothing;

-- -- MOBILE: 30 DAYS -------------------------------
insert into roadmap (domain_slug,week_number,day_number,topic,description,video_url,resource_url,article_url,difficulty) values
('mobile',1,1,'React Native Setup','Install and configure React Native environment',null,'https://reactnative.dev/docs/environment-setup','https://dev.to/search?q=react+native+setup','beginner'),
('mobile',1,2,'Components and JSX','Build UI with React Native components',null,'https://reactnative.dev/docs/components-and-apis','https://dev.to/search?q=react+native+components','beginner'),
('mobile',1,3,'Styling in React Native','StyleSheet and Flexbox for mobile UI',null,'https://reactnative.dev/docs/style','https://dev.to/search?q=react+native+styling','beginner'),
('mobile',1,4,'Navigation Basics','Stack Tab and Drawer navigation',null,'https://reactnavigation.org/docs/getting-started','https://dev.to/search?q=react+navigation','beginner'),
('mobile',1,5,'State and Props','Manage data flow in React Native',null,'https://reactnative.dev/docs/state','https://dev.to/search?q=react+native+state','beginner'),
('mobile',1,6,'AsyncStorage','Persist data locally on device',null,'https://react-native-async-storage.github.io/async-storage/','https://dev.to/search?q=asyncstorage+react+native','beginner'),
('mobile',1,7,'REST API Integration','Fetch data from APIs in React Native',null,'https://reactnative.dev/docs/network','https://dev.to/search?q=react+native+api','beginner'),
('mobile',2,8,'Redux Toolkit','State management with Redux in mobile',null,'https://redux-toolkit.js.org/introduction/getting-started','https://dev.to/search?q=redux+react+native','beginner'),
('mobile',2,9,'Animations','Smooth animations with Reanimated',null,'https://docs.swmansion.com/react-native-reanimated/','https://dev.to/search?q=react+native+animations','beginner'),
('mobile',2,10,'Gesture Handling','Touch and gesture interactions',null,'https://docs.swmansion.com/react-native-gesture-handler/','https://dev.to/search?q=react+native+gestures','beginner'),
('mobile',2,11,'Camera and Media','Access camera and image picker',null,'https://mrousavy.com/react-native-vision-camera/docs/guides/','https://dev.to/search?q=react+native+camera','intermediate'),
('mobile',2,12,'Push Notifications','Send and receive push notifications',null,'https://docs.expo.dev/push-notifications/overview/','https://dev.to/search?q=push+notifications+react+native','intermediate'),
('mobile',2,13,'Firebase Integration','Connect Firebase to React Native',null,'https://rnfirebase.io/','https://dev.to/search?q=firebase+react+native','intermediate'),
('mobile',2,14,'Maps and Location','Integrate maps and geolocation',null,'https://github.com/react-native-maps/react-native-maps','https://dev.to/search?q=react+native+maps','intermediate'),
('mobile',3,15,'Firebase Auth','Authentication with Firebase in mobile',null,'https://rnfirebase.io/auth/usage','https://dev.to/search?q=firebase+auth+mobile','intermediate'),
('mobile',3,16,'Real-time Firestore','Live data sync with Firestore',null,'https://rnfirebase.io/firestore/usage','https://dev.to/search?q=firestore+react+native','intermediate'),
('mobile',3,17,'Performance Optimization','Optimize React Native app performance',null,'https://reactnative.dev/docs/performance','https://dev.to/search?q=react+native+performance','intermediate'),
('mobile',3,18,'Testing React Native','Unit and integration tests for mobile',null,'https://reactnative.dev/docs/testing-overview','https://dev.to/search?q=react+native+testing','advanced'),
('mobile',3,19,'App Store Guidelines','Prepare app for App Store submission',null,'https://developer.apple.com/app-store/guidelines/','https://dev.to/search?q=app+store+guidelines','advanced'),
('mobile',3,20,'Building APK and IPA','Generate release builds for Android iOS',null,'https://reactnative.dev/docs/signed-apk-android','https://dev.to/search?q=react+native+release+build','advanced'),
('mobile',3,21,'Flutter Basics','Introduction to Flutter and Dart',null,'https://flutter.dev/docs/get-started/codelab','https://dev.to/search?q=flutter+basics','advanced'),
('mobile',4,22,'Dart Language','Learn Dart programming for Flutter',null,'https://dart.dev/guides','https://dev.to/search?q=dart+language','advanced'),
('mobile',4,23,'Flutter Widgets','Core Flutter widget system',null,'https://docs.flutter.dev/ui/widgets-intro','https://dev.to/search?q=flutter+widgets','advanced'),
('mobile',4,24,'Flutter State Management','Riverpod and Provider in Flutter',null,'https://riverpod.dev/docs/introduction/getting_started','https://dev.to/search?q=flutter+state+management','advanced'),
('mobile',4,25,'Flutter Navigation','Navigation and routing in Flutter',null,'https://docs.flutter.dev/ui/navigation','https://dev.to/search?q=flutter+navigation','advanced'),
('mobile',4,26,'Native Modules','Bridge JavaScript to native code',null,'https://reactnative.dev/docs/native-modules-intro','https://dev.to/search?q=native+modules','advanced'),
('mobile',4,27,'App Monetization','In-app purchases and subscriptions',null,'https://developer.apple.com/in-app-purchase/','https://dev.to/search?q=app+monetization','advanced'),
('mobile',4,28,'Analytics Integration','Track user behavior in mobile apps',null,'https://firebase.google.com/docs/analytics','https://dev.to/search?q=mobile+analytics','advanced'),
('mobile',5,29,'Full Mobile App Project','Build and deploy a complete mobile app',null,'https://reactnative.dev/','https://dev.to/search?q=react+native+project','advanced'),
('mobile',5,30,'App Store Publishing','Publish to App Store and Play Store',null,'https://developer.apple.com/app-store/submitting/','https://dev.to/search?q=app+store+publishing','advanced')
on conflict (domain_slug, day_number) do nothing;

-- -- DEVOPS: 30 DAYS -------------------------------
insert into roadmap (domain_slug,week_number,day_number,topic,description,video_url,resource_url,article_url,difficulty) values
('devops',1,1,'Linux Fundamentals','File system permissions and shell basics',null,'https://linuxcommand.org/','https://dev.to/search?q=linux+fundamentals','beginner'),
('devops',1,2,'Shell Scripting','Automate tasks with bash scripts',null,'https://www.gnu.org/software/bash/manual/','https://dev.to/search?q=bash+scripting','beginner'),
('devops',1,3,'Git Advanced','Branching rebasing and git workflows',null,'https://git-scm.com/book/en/v2','https://dev.to/search?q=git+advanced','beginner'),
('devops',1,4,'Docker Fundamentals','Containers images and Dockerfile',null,'https://docs.docker.com/get-started/','https://dev.to/search?q=docker+fundamentals','beginner'),
('devops',1,5,'Docker Compose','Multi-container apps with Compose',null,'https://docs.docker.com/compose/','https://dev.to/search?q=docker+compose','beginner'),
('devops',1,6,'Networking for DevOps','Ports protocols and network debugging',null,'https://www.cloudflare.com/learning/network-layer/','https://dev.to/search?q=networking+devops','beginner'),
('devops',1,7,'SSH and Security','Secure shell setup and key management',null,'https://www.openssh.com/manual.html','https://dev.to/search?q=ssh+tutorial','beginner'),
('devops',2,8,'Jenkins CI/CD','Build pipelines with Jenkins',null,'https://www.jenkins.io/doc/tutorials/','https://dev.to/search?q=jenkins+cicd','beginner'),
('devops',2,9,'GitHub Actions','Automate workflows with GitHub Actions',null,'https://docs.github.com/en/actions','https://dev.to/search?q=github+actions','beginner'),
('devops',2,10,'GitLab CI','CI/CD pipelines with GitLab',null,'https://docs.gitlab.com/ee/ci/','https://dev.to/search?q=gitlab+ci','beginner'),
('devops',2,11,'Kubernetes Architecture','Pods nodes clusters explained',null,'https://kubernetes.io/docs/concepts/','https://dev.to/search?q=kubernetes+architecture','intermediate'),
('devops',2,12,'kubectl Commands','Manage Kubernetes with kubectl',null,'https://kubernetes.io/docs/reference/kubectl/','https://dev.to/search?q=kubectl+commands','intermediate'),
('devops',2,13,'Helm Charts','Package Kubernetes applications',null,'https://helm.sh/docs/','https://dev.to/search?q=helm+charts','intermediate'),
('devops',2,14,'Terraform Basics','Provision infrastructure as code',null,'https://developer.hashicorp.com/terraform/tutorials','https://dev.to/search?q=terraform+basics','intermediate'),
('devops',3,15,'Ansible Playbooks','Configuration management with Ansible',null,'https://docs.ansible.com/ansible/latest/getting_started/','https://dev.to/search?q=ansible+playbooks','intermediate'),
('devops',3,16,'Prometheus Monitoring','Collect and query metrics',null,'https://prometheus.io/docs/introduction/overview/','https://dev.to/search?q=prometheus+monitoring','intermediate'),
('devops',3,17,'Grafana Dashboards','Visualize metrics with Grafana',null,'https://grafana.com/docs/grafana/latest/','https://dev.to/search?q=grafana+dashboards','intermediate'),
('devops',3,18,'ELK Stack Logging','Elasticsearch Logstash Kibana',null,'https://www.elastic.co/guide/index.html','https://dev.to/search?q=elk+stack','advanced'),
('devops',3,19,'Alertmanager','Set up alerts for infrastructure',null,'https://prometheus.io/docs/alerting/latest/alertmanager/','https://dev.to/search?q=alertmanager','advanced'),
('devops',3,20,'SRE Principles','Site reliability engineering practices',null,'https://sre.google/books/','https://dev.to/search?q=sre+principles','advanced'),
('devops',3,21,'Service Mesh Istio','Manage microservice communication',null,'https://istio.io/latest/docs/','https://dev.to/search?q=istio+service+mesh','advanced'),
('devops',4,22,'ArgoCD GitOps','GitOps continuous delivery with ArgoCD',null,'https://argo-cd.readthedocs.io/en/stable/','https://dev.to/search?q=argocd+gitops','advanced'),
('devops',4,23,'Vault for Secrets','Manage secrets securely with Vault',null,'https://developer.hashicorp.com/vault/docs','https://dev.to/search?q=vault+secrets','advanced'),
('devops',4,24,'AWS DevOps Tools','CodePipeline CodeBuild CodeDeploy',null,'https://aws.amazon.com/devops/','https://dev.to/search?q=aws+devops','advanced'),
('devops',4,25,'Chaos Engineering','Test system resilience with chaos',null,'https://principlesofchaos.org/','https://dev.to/search?q=chaos+engineering','advanced'),
('devops',4,26,'Performance Testing','Load testing with k6 and JMeter',null,'https://k6.io/docs/','https://dev.to/search?q=performance+testing','advanced'),
('devops',4,27,'Cost Management','Optimize infrastructure costs',null,'https://aws.amazon.com/aws-cost-management/','https://dev.to/search?q=devops+cost+management','advanced'),
('devops',4,28,'Production Incidents','Manage and resolve production issues',null,'https://sre.google/workbook/incident-response/','https://dev.to/search?q=incident+management','advanced'),
('devops',5,29,'DevOps Pipeline Project','Build complete CI/CD pipeline',null,'https://www.jenkins.io/doc/tutorials/','https://dev.to/search?q=cicd+project','advanced'),
('devops',5,30,'DevOps Interview Prep','Common DevOps interview questions',null,'https://roadmap.sh/devops','https://dev.to/search?q=devops+interview','advanced')
on conflict (domain_slug, day_number) do nothing;

-- -- SYSDESIGN: 30 DAYS ----------------------------
insert into roadmap (domain_slug,week_number,day_number,topic,description,video_url,resource_url,article_url,difficulty) values
('sysdesign',1,1,'System Design Basics','Approach and framework for system design',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=system+design+basics','beginner'),
('sysdesign',1,2,'Scalability and Load Balancing','Scale systems horizontally and vertically',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=scalability+system+design','beginner'),
('sysdesign',1,3,'Caching Strategies','Redis Memcached and cache patterns',null,'https://redis.io/docs/manual/','https://dev.to/search?q=caching+system+design','beginner'),
('sysdesign',1,4,'Database Design','Choose between SQL and NoSQL',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=database+design','beginner'),
('sysdesign',1,5,'CAP Theorem','Consistency availability partition tolerance',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=cap+theorem','beginner'),
('sysdesign',1,6,'Consistency Models','Strong eventual and causal consistency',null,'https://jepsen.io/consistency','https://dev.to/search?q=consistency+models','beginner'),
('sysdesign',1,7,'API Design REST','RESTful API design principles',null,'https://restfulapi.net/','https://dev.to/search?q=api+design+rest','beginner'),
('sysdesign',2,8,'Microservices Architecture','Break monoliths into microservices',null,'https://microservices.io/patterns/microservices.html','https://dev.to/search?q=microservices+architecture','beginner'),
('sysdesign',2,9,'Message Queues','Kafka RabbitMQ for async communication',null,'https://kafka.apache.org/documentation/','https://dev.to/search?q=message+queue+kafka','beginner'),
('sysdesign',2,10,'CDN and Edge Caching','Content delivery networks explained',null,'https://www.cloudflare.com/learning/cdn/what-is-a-cdn/','https://dev.to/search?q=cdn+caching','beginner'),
('sysdesign',2,11,'Rate Limiting','Protect APIs with rate limiting',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=rate+limiting','intermediate'),
('sysdesign',2,12,'Service Discovery','Find services in a microservice system',null,'https://www.consul.io/docs/intro','https://dev.to/search?q=service+discovery','intermediate'),
('sysdesign',2,13,'Event Driven Architecture','Design event-driven systems',null,'https://microservices.io/patterns/data/event-driven-architecture.html','https://dev.to/search?q=event+driven+architecture','intermediate'),
('sysdesign',2,14,'Design URL Shortener','System design of URL shortening service',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=url+shortener+design','intermediate'),
('sysdesign',3,15,'Design Twitter Feed','Design Twitter newsfeed system',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=twitter+system+design','intermediate'),
('sysdesign',3,16,'Design WhatsApp','Design real-time messaging system',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=whatsapp+system+design','intermediate'),
('sysdesign',3,17,'Design YouTube','Design video streaming platform',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=youtube+system+design','intermediate'),
('sysdesign',3,18,'Design Uber','Design ride-sharing location system',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=uber+system+design','intermediate'),
('sysdesign',3,19,'Design Amazon','Design e-commerce platform at scale',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=amazon+system+design','advanced'),
('sysdesign',3,20,'Design Netflix','Design video streaming and CDN',null,'https://netflixtechblog.com/','https://dev.to/search?q=netflix+system+design','advanced'),
('sysdesign',3,21,'Distributed Systems','Clocks consensus and fault tolerance',null,'https://www.distributedsystems.org/','https://dev.to/search?q=distributed+systems','advanced'),
('sysdesign',4,22,'Raft Consensus','Leader election and log replication',null,'https://raft.github.io/','https://dev.to/search?q=raft+consensus','advanced'),
('sysdesign',4,23,'Database Sharding','Horizontal partitioning of databases',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=database+sharding','advanced'),
('sysdesign',4,24,'Replication Strategies','Master-slave and multi-master replication',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=database+replication','advanced'),
('sysdesign',4,25,'Real-time Systems','WebSockets and real-time architecture',null,'https://socket.io/docs/v4/','https://dev.to/search?q=real+time+systems','advanced'),
('sysdesign',4,26,'Search Systems','Build search with Elasticsearch',null,'https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html','https://dev.to/search?q=search+system+design','advanced'),
('sysdesign',4,27,'Observability','Logging metrics and distributed tracing',null,'https://opentelemetry.io/docs/','https://dev.to/search?q=observability+systems','advanced'),
('sysdesign',4,28,'GraphQL API Design','Design flexible APIs with GraphQL',null,'https://graphql.org/learn/','https://dev.to/search?q=graphql+api+design','advanced'),
('sysdesign',5,29,'System Design Interview','Mock system design interview practice',null,'https://github.com/donnemartin/system-design-primer','https://dev.to/search?q=system+design+interview','advanced'),
('sysdesign',5,30,'Architecture Review','Review and critique real architectures',null,'https://martinfowler.com/architecture/','https://dev.to/search?q=software+architecture','advanced')
on conflict (domain_slug, day_number) do nothing;
-- ── CODING TESTS (3 per domain) ───────────────────
insert into coding_tests (domain_slug,topic,title,problem,input_desc,output_desc,example_input,example_output,hints,difficulty) values
('fullstack','JavaScript Basics','Reverse a String','Write a function that reverses a string without using the built-in reverse method','A string s','The reversed string','hello','olleh',ARRAY['Use a for loop','Split the string into characters','Build the result from end to start'],'beginner'),
('fullstack','DOM Manipulation','Build a Todo List','Create a function that adds an item to a todo array and returns the updated array','An array of strings and a new item string','Updated array with new item appended','array and new item','updated array with new item',ARRAY['Use the push method','Return the modified array','Handle empty array case'],'beginner'),
('fullstack','Async JavaScript','Fetch User Data','Write an async function that fetches user data from an API and returns the user name','A user ID number','The user name as a string','1','Leanne Graham',ARRAY['Use fetch with async await','Access the json method on response','Handle errors with try catch'],'intermediate'),
('dsa','Arrays','Two Sum Problem','Find two numbers in an array that add up to target and return their indices','An array of integers and a target number','Array of two indices that sum to target','[2,7,11,15] target=9','[0,1]',ARRAY['Use a hash map for O(n) solution','For each number check if target minus number exists','Store number and index in the map'],'beginner'),
('dsa','Binary Search','Search in Sorted Array','Implement binary search to find a target in a sorted array','A sorted array and a target value','Index of target or -1 if not found','[1,3,5,7,9] target=5','2',ARRAY['Use left and right pointers','Calculate mid as left plus right divided by 2','Move left or right based on comparison'],'beginner'),
('dsa','Dynamic Programming','Fibonacci Sequence','Calculate the nth Fibonacci number using dynamic programming','A number n','The nth Fibonacci number','10','55',ARRAY['Use memoization or bottom-up tabulation','Base cases are fib(0)=0 and fib(1)=1','Build solution from smaller subproblems'],'intermediate'),
('ml','Python','Normalize Array','Write a function to normalize an array to values between 0 and 1','An array of numbers','Normalized array where min=0 and max=1','[1,2,3,4,5]','[0.0, 0.25, 0.5, 0.75, 1.0]',ARRAY['Find min and max of array','Subtract min from each element','Divide by the range max minus min'],'beginner'),
('ml','Statistics','Calculate Mean and Std','Write a function that returns mean and standard deviation of a dataset','An array of numbers','Object with mean and std properties','[2,4,4,4,5,5,7,9]','mean 5.0 std 2.0',ARRAY['Calculate mean as sum divided by length','Variance is average of squared differences from mean','Standard deviation is square root of variance'],'beginner'),
('ml','Linear Regression','Gradient Descent Step','Implement one step of gradient descent for linear regression','Arrays x y and learning rate alpha','Updated weights w and b','x=[1,2,3] y=[2,4,6] w=0 b=0 alpha=0.1','w=0.28 b=0.12',ARRAY['Calculate predictions as w*x + b','Compute gradients using chain rule','Update w and b using learning rate'],'intermediate'),
('ai','Search','Implement BFS','Implement breadth first search on a graph represented as adjacency list','Graph as dict and start node','List of nodes visited in BFS order','A connects to B and C, B connects to D, start=A','[A,B,C,D,E]',ARRAY['Use a queue data structure','Mark nodes as visited when enqueued','Process each node and add its neighbors'],'beginner'),
('ai','Logic','Evaluate Expression','Evaluate a boolean logic expression with AND OR NOT operators','A string expression with AND OR NOT and variables','Boolean result true or false','A AND NOT B where A=true B=false','true',ARRAY['Parse the expression into tokens','Handle operator precedence NOT AND OR','Use recursive descent or a stack'],'intermediate'),
('ai','LLMs','Token Counter','Count tokens in a text where each word is one token and punctuation counts separately','A string of text','Number of tokens','Hello world','2',ARRAY['Split on whitespace for words','Check each character for punctuation','Count punctuation marks separately'],'beginner'),
('ds','Pandas','Find Top N Values','Write a function to find the top N values in a list','A list of numbers and N','List of top N values in descending order','[5,2,8,1,9,3] N=3','[9,8,5]',ARRAY['Sort the list in descending order','Slice the first N elements','Handle N larger than list length'],'beginner'),
('ds','Statistics','Correlation Coefficient','Calculate Pearson correlation between two arrays','Two arrays of equal length','Correlation coefficient between -1 and 1','[1,2,3,4,5] and [2,4,6,8,10]','1.0',ARRAY['Calculate means of both arrays','Compute covariance','Divide by product of standard deviations'],'intermediate'),
('ds','Data Cleaning','Remove Duplicates','Remove duplicate rows from a dataset keeping the first occurrence','List of dicts representing rows','List with duplicates removed','rows with some duplicates','rows without duplicates',ARRAY['Convert each row to a tuple for hashing','Use a set to track seen rows','Keep order of first occurrence'],'beginner'),
('cybersec','Cryptography','Caesar Cipher','Implement Caesar cipher encryption and decryption','A string message and integer shift','Encrypted or decrypted string','hello shift=3','khoor',ARRAY['Use modulo 26 for wrapping','Handle uppercase and lowercase separately','Leave non-alphabetic characters unchanged'],'beginner'),
('cybersec','Security','Password Strength','Check if a password meets security requirements','A password string','Object with isStrong boolean and reasons array','password123','isStrong false with missing requirements listed',ARRAY['Check length minimum 8 characters','Verify has uppercase lowercase number and special char','Return all failed requirements'],'beginner'),
('cybersec','Cryptography','Hash Verification','Verify if a given string matches a stored hash','A string and its expected hash','Boolean true if match false otherwise','hello and its md5 hash','true',ARRAY['Use built-in hash functions','Compare hash of input to expected hash','Return boolean result'],'intermediate'),
('cloud','AWS','Calculate S3 Cost','Calculate monthly S3 storage cost given size in GB','Storage in GB and price per GB','Monthly cost in dollars','100 GB at 0.023 per GB','2.30',ARRAY['Multiply storage by price','Round to 2 decimal places','Consider free tier if applicable'],'beginner'),
('cloud','Networking','Subnet Calculator','Given an IP and CIDR find the network address','IP address string and CIDR prefix length','Network address string','192.168.1.100 with /24','192.168.1.0',ARRAY['Convert IP to binary','Apply subnet mask','Convert result back to dotted notation'],'intermediate'),
('cloud','Docker','Parse Dockerfile','Count the number of layers in a Dockerfile','A Dockerfile as a string','Number of layer-creating commands','FROM ubuntu RUN apt-get update COPY . . RUN make','3',ARRAY['Split on newlines','Count FROM RUN COPY ADD commands','Each of these creates a new layer'],'beginner'),
('mobile','React Native','Format Phone Number','Format a 10-digit number as phone number','A string of 10 digits','Formatted phone string','9876543210','(987) 654-3210',ARRAY['Extract area code first 3 digits','Extract next 3 and last 4','Combine with proper formatting'],'beginner'),
('mobile','JavaScript','Debounce Function','Implement a debounce function for search input','A function and delay in ms','Debounced function that delays execution','fn and 300ms delay','Debounced function that fires after delay',ARRAY['Use setTimeout to delay execution','Clear previous timer on each call','Return a wrapper function'],'intermediate'),
('mobile','Performance','Calculate FPS','Given frame timestamps calculate average FPS','Array of timestamps in ms','Average frames per second','[0, 33, 66, 100]','30',ARRAY['Calculate time differences between frames','Average the differences','FPS is 1000 divided by average ms per frame'],'beginner'),
('devops','Shell','Parse Log File','Count occurrences of each HTTP status code in a log','Array of log line strings','Object with status codes as keys and counts as values','GET /api 200 and POST /login 401 and GET /home 200','200 appears 2 times 401 appears 1 time',ARRAY['Split each line on spaces','Extract the status code field','Use a counter object'],'beginner'),
('devops','Docker','Container Memory','Calculate memory usage percentage','Used memory and total memory in MB','Percentage as float rounded to 1 decimal','512 MB used out of 2048 MB total','25.0',ARRAY['Divide used by total','Multiply by 100','Round to 1 decimal place'],'beginner'),
('devops','CI/CD','Pipeline Duration','Calculate total pipeline duration from stage times','Array of stage duration objects with name and seconds','Total seconds and formatted time string','build 120s and test 300s','total 420 formatted 7m 0s',ARRAY['Sum all seconds','Convert to minutes and seconds','Format as Xm Ys'],'beginner'),
('sysdesign','Caching','LRU Cache','Implement an LRU cache with get and put operations','Capacity integer then get and put operations','Values from get operations','capacity=2 put(1,1) put(2,2) get(1) put(3,3) get(2)','get(1)=1 get(2)=-1',ARRAY['Use a doubly linked list for order','Use a hash map for O(1) access','Move to front on access and evict from back'],'intermediate'),
('sysdesign','Rate Limiting','Token Bucket','Implement token bucket rate limiting algorithm','Max tokens refill rate and request sizes','True if allowed false if rate limited','max=10 rate=1 per second requests=[3,5,8]','true true false',ARRAY['Track current tokens and last refill time','Add tokens based on elapsed time','Consume tokens for each request'],'intermediate'),
('sysdesign','Distributed Systems','Consistent Hashing','Place N servers on hash ring and find server for key','Number of servers and a key string','Server index that handles the key','3 servers key=user123','Server 1',ARRAY['Hash the key to a position 0 to 360','Place servers at equal intervals','Find next server clockwise from key position'],'advanced')
on conflict do nothing;

-- ── PROJECTS (2 per domain) ───────────────────────
insert into projects (domain_slug,week_number,title,description,difficulty,steps,tech_stack,resources) values
('fullstack',1,'Personal Portfolio Website','Build a responsive portfolio website showcasing your projects and skills','beginner','["Plan your layout and sections","Code HTML structure CSS styling and JavaScript interactions","Test on mobile and desktop and fix responsiveness","Deploy to GitHub Pages or Netlify and submit your live URL"]',ARRAY['HTML','CSS','JavaScript','GitHub Pages'],ARRAY['https://developer.mozilla.org/en-US/docs/Web/HTML','https://css-tricks.com/snippets/css/a-guide-to-flexbox/']),
('fullstack',2,'REST API with Authentication','Build a Node.js REST API with JWT authentication and PostgreSQL','intermediate','["Plan your API endpoints and database schema","Set up Express server with JWT auth middleware and routes","Add database integration with Prisma and test all endpoints","Write API documentation and deploy to Railway"]',ARRAY['Node.js','Express','JWT','PostgreSQL','Prisma'],ARRAY['https://expressjs.com/','https://jwt.io/introduction']),
('dsa',1,'Algorithm Visualizer','Build a web app that visualizes sorting algorithms step by step','beginner','["Research bubble sort merge sort and quick sort algorithms","Build the HTML CSS layout with animation framework","Implement each sorting algorithm with step visualization","Add controls for speed and array size then deploy"]',ARRAY['HTML','CSS','JavaScript'],ARRAY['https://developer.mozilla.org/en-US/docs/Web/API/setTimeout']),
('dsa',2,'LeetCode Problem Tracker','Build a tracker to log and analyze your LeetCode progress','intermediate','["Plan data model for problems difficulty status and notes","Build React frontend with filters and statistics dashboard","Add local storage persistence and charts for progress","Add export functionality and deploy as a PWA"]',ARRAY['React','Chart.js','LocalStorage'],ARRAY['https://react.dev/learn']),
('ml',1,'House Price Predictor','Predict house prices using linear regression on real dataset','beginner','["Download and explore the housing dataset with pandas","Clean data handle missing values and engineer features","Train linear regression model and evaluate with metrics","Create a Streamlit web app to make predictions"]',ARRAY['Python','Pandas','Scikit-learn','Streamlit'],ARRAY['https://scikit-learn.org/stable/modules/linear_model.html']),
('ml',2,'Image Classifier','Build a CNN to classify images into 10 categories','intermediate','["Load CIFAR-10 dataset and perform exploratory analysis","Build and train CNN architecture with Keras","Evaluate model performance and visualize predictions","Save model and deploy as a FastAPI endpoint"]',ARRAY['Python','TensorFlow','Keras','FastAPI'],ARRAY['https://www.tensorflow.org/tutorials/images/cnn']),
('ai',1,'AI Chatbot with Memory','Build a chatbot that remembers conversation context','beginner','["Set up Anthropic API and design conversation flow","Implement conversation history and context management","Add personality and domain-specific knowledge to system prompt","Build simple web interface and test with sample conversations"]',ARRAY['Python','Anthropic API','Flask'],ARRAY['https://docs.anthropic.com/en/api/getting-started']),
('ai',2,'RAG Document QA System','Build a system that answers questions from your documents','intermediate','["Process and chunk documents into embeddings","Set up vector database to store and search embeddings","Connect retrieval to Claude API for answer generation","Build web interface to upload docs and ask questions"]',ARRAY['Python','Anthropic API','ChromaDB','FastAPI'],ARRAY['https://docs.anthropic.com/']),
('ds',1,'Sales Dashboard','Build an interactive sales analytics dashboard','beginner','["Load and clean the sales dataset with Pandas","Create visualizations with Plotly for key metrics","Build Streamlit dashboard with filters and date range","Deploy dashboard to Streamlit Cloud and share URL"]',ARRAY['Python','Pandas','Plotly','Streamlit'],ARRAY['https://plotly.com/python/','https://streamlit.io/docs']),
('ds',2,'Customer Churn Predictor','Predict which customers will cancel their subscription','intermediate','["Analyze customer dataset and identify churn indicators","Engineer features and handle class imbalance","Train and compare multiple classification models","Present findings in a clear report with visualizations"]',ARRAY['Python','Pandas','Scikit-learn','Matplotlib'],ARRAY['https://scikit-learn.org/stable/supervised_learning.html']),
('cybersec',1,'Password Manager CLI','Build a command-line password manager with encryption','beginner','["Design data model for storing encrypted passwords","Implement AES encryption and decryption functions","Build CLI interface with add get and list commands","Add master password protection and test security"]',ARRAY['Python','Cryptography library'],ARRAY['https://cryptography.io/en/latest/']),
('cybersec',2,'Web Vulnerability Scanner','Build a basic scanner to detect common web vulnerabilities','intermediate','["Research OWASP top 10 vulnerabilities to test for","Build scanner that tests for SQL injection and XSS","Generate HTML report with findings and severity ratings","Test against your own vulnerable test application"]',ARRAY['Python','Requests','BeautifulSoup'],ARRAY['https://owasp.org/www-project-top-ten/']),
('cloud',1,'Serverless API on AWS','Deploy a serverless REST API using AWS Lambda and API Gateway','beginner','["Design the API endpoints and data structures","Write Lambda functions in Python and test locally","Deploy to AWS using console and configure API Gateway","Set up CloudWatch monitoring and test production endpoint"]',ARRAY['Python','AWS Lambda','API Gateway','CloudWatch'],ARRAY['https://docs.aws.amazon.com/lambda/']),
('cloud',2,'Containerized Microservice','Build and deploy a containerized microservice to Kubernetes','intermediate','["Write a Node.js microservice with Docker containerization","Push image to ECR and write Kubernetes deployment YAML","Deploy to EKS and configure service and ingress","Set up horizontal pod autoscaling and monitoring"]',ARRAY['Node.js','Docker','Kubernetes','AWS EKS'],ARRAY['https://kubernetes.io/docs/tutorials/']),
('mobile',1,'Weather App','Build a mobile weather app using a public API','beginner','["Design app screens and navigation flow","Set up React Native project with navigation","Integrate weather API and display current and forecast data","Add geolocation and unit conversion and deploy to Expo Go"]',ARRAY['React Native','Expo','Weather API'],ARRAY['https://reactnative.dev/docs/getting-started']),
('mobile',2,'Chat Application','Build a real-time chat app with Firebase','intermediate','["Design chat UI and data model for messages and rooms","Set up Firebase Auth and Firestore for real-time data","Implement chat rooms push notifications and online status","Polish UI add image sharing and test on both platforms"]',ARRAY['React Native','Firebase','Expo'],ARRAY['https://rnfirebase.io/']),
('devops',1,'CI/CD Pipeline Project','Build a complete CI/CD pipeline for a web application','beginner','["Create a simple web app with tests to use as target","Write GitHub Actions workflow for lint test and build","Add deployment step to deploy to Railway or Vercel","Set up notifications and branch protection rules"]',ARRAY['GitHub Actions','Docker','Railway'],ARRAY['https://docs.github.com/en/actions']),
('devops',2,'Kubernetes Monitoring Stack','Deploy Prometheus and Grafana monitoring on Kubernetes','intermediate','["Set up a local Kubernetes cluster with Kind or Minikube","Deploy Prometheus with custom scrape configs","Install Grafana and import pre-built dashboards","Create custom alerts and test with a sample application"]',ARRAY['Kubernetes','Prometheus','Grafana','Helm'],ARRAY['https://prometheus.io/docs/','https://grafana.com/docs/']),
('sysdesign',1,'URL Shortener Service','Design and implement a URL shortener like bit.ly','beginner','["Design the system with load balancer cache and database","Implement the URL encoding and decoding algorithm","Build REST API with Node.js and store data in Redis and PostgreSQL","Add analytics tracking and handle redirects efficiently"]',ARRAY['Node.js','Redis','PostgreSQL'],ARRAY['https://github.com/donnemartin/system-design-primer']),
('sysdesign',2,'Distributed Cache','Implement a simple distributed caching system','intermediate','["Design consistent hashing for distributing cache nodes","Implement cache node with LRU eviction policy","Build coordinator that routes requests to correct node","Test with concurrent clients and measure performance"]',ARRAY['Node.js','Redis'],ARRAY['https://redis.io/docs/manual/'])
on conflict do nothing;
