'use client';
import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { subscriptionAPI } from '@/lib/api';
import useAuthStore from '@/store/authStore';
import RazorpayButton from '@/components/RazorpayButton';

const PLANS = [
  {
    id: 'free',
    name: 'Spectator',
    tagline: 'Just checking things out? Start here. No card needed.',
    price: '₹0',
    period: '30 days free',
    color: '#1D9E75',
    badge: null,
    features: [
      '✅ 30-day full access trial — no credit card',
      '✅ Pick 1 domain from 10 career paths',
      '✅ Full 30-day AI-powered daily roadmap',
      '✅ Daily coding challenge with AI code review',
      '✅ Daily test — 5 AI-generated questions',
      '✅ AI Chatbot — ask anything about your domain',
      '✅ AI Notes — auto-generated study notes',
      '✅ Project guide — build real projects step by step',
      '✅ Basic analytics — track your daily progress',
      '✅ 2AM Anxiety Chat — we are here when you panic',
      '❌ AI Mentor (5 expert modes)',
      '❌ Weekly and monthly tests',
      '❌ All 10 domains access',
      '❌ Leaderboard and rank tracking',
    ],
    cta: 'Start Free — No Card Needed →',
  },
  {
    id: 'basic',
    name: 'Player',
    tagline: 'You showed up. Time to grind. Unlock more domains and weekly tests.',
    price: '₹99',
    period: '/month',
    color: '#378ADD',
    badge: null,
    features: [
      '✅ Everything in Spectator plan',
      '✅ Access to 3 domains simultaneously',
      '✅ Daily + Weekly tests (10 questions every Monday)',
      '✅ AI Chatbot with conversation history',
      '✅ 2AM Anxiety Chat — unlimited sessions',
      '✅ AI Notes for every topic (4 types: theory, coding, full, revision)',
      '✅ Daily coding challenges with hints',
      '✅ Project guides for all 3 domains',
      '✅ Basic skill identity tracking',
      '✅ Activity streak tracker',
      '✅ Progress analytics — weekly report',
      '✅ College leaderboard — see your rank',
      '❌ AI Mentor (5 expert modes)',
      '❌ Monthly tests',
      '❌ All 10 domains',
      '❌ Global leaderboard rank',
      '❌ Resume AI review',
    ],
    cta: 'Go Player →',
  },
  {
    id: 'pro',
    name: 'Performer',
    tagline: 'Main character arc. Full access. AI mentor. Get placed.',
    price: '₹199',
    period: '/month',
    color: '#00f0ff',
    featured: true,
    badge: '🔥 Most Popular',
    features: [
      '✅ Everything in Player plan',
      '✅ All 10 domains — switch anytime',
      '✅ AI Mentor — 5 expert modes (explain, quiz, roast, career, mock interview)',
      '✅ Daily + Weekly + Monthly tests (20 mixed questions on 1st of month)',
      '✅ Full AI Notes — generate theory coding full and revision notes',
      '✅ Advanced skill identity — 6-axis skill radar chart',
      '✅ Full analytics — daily graph, score breakdown, weak vs strong topics',
      '✅ Global + College + Domain leaderboard',
      '✅ Public profile link — share with recruiters',
      '✅ Job Ready Badge when score crosses 70%',
      '✅ Hire-Ready rank visible to recruiters',
      '✅ Project AI feedback — get reviewed by Claude after submitting',
      '✅ Revision test — focuses only on your weak topics',
      '✅ 26 unique projects per domain — full year no repetition',
      '✅ Priority support',
    ],
    cta: 'Go Performer →',
  },
  {
    id: 'elite',
    name: 'Dominator',
    tagline: 'Built different. Placement mode. Everything unlocked.',
    price: '₹499',
    period: '/month',
    color: '#7b5cff',
    badge: '👑 Best Value',
    features: [
      '✅ Everything in Performer plan',
      '✅ AI Resume Reviewer — Claude gives line-by-line feedback on your resume',
      '✅ Mock Interview Coach — full AI mock interview with question and answer feedback',
      '✅ Job Readiness Certificate — downloadable PDF when you complete 30 days',
      '✅ Placement Strategy Session — AI-generated personalised placement roadmap',
      '✅ Company-specific prep — get prep material for TCS Infosys Wipro startups',
      '✅ Referral system — refer a friend get 1 month free',
      '✅ Early access to new features before everyone else',
      '✅ Private community access — top performers only',
      '✅ Direct mentor escalation — tough doubts get answered faster',
      '✅ All 26 projects with extended AI review and detailed feedback',
      '✅ Annual performance report — shareable PDF showing full year growth',
      '✅ LinkedIn recommendation template generated by AI based on your performance',
    ],
    cta: 'Go Dominator →',
  },
];

export default function SubscriptionPage() {
  const { user, updateUser } = useAuthStore();
  const [status, setStatus] = useState(null);
  const [loading, setLoading] = useState(true);
  const [upgradeModal, setUpgradeModal] = useState(null);

  useEffect(() => {
    subscriptionAPI.getStatus()
      .then(r => setStatus(r.data))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const refreshStatus = () => {
    subscriptionAPI.getStatus().then(r => setStatus(r.data)).catch(console.error);
  };

  const planPrice = (id) => id === 'elite' ? '₹499' : id === 'basic' ? '₹99' : '₹199';
  const planDesc = (id) => id === 'elite' ? 'Dominator — everything unlocked' : id === 'basic' ? 'Player — grind mode activated' : 'Performer — main character arc';

  if (loading) return (
    <div style={{ maxWidth: 1100, margin: '0 auto', fontFamily: 'Outfit,sans-serif' }}>
      <div style={{ height: 200, background: 'rgba(255,255,255,0.03)', borderRadius: 14, animation: 'pulse 1.5s infinite' }} />
    </div>
  );

  return (
    <div style={{ maxWidth: 1100, margin: '0 auto', fontFamily: 'Outfit,sans-serif' }}>
      <h1 style={{ fontFamily: 'Syne,sans-serif', fontSize: 26, fontWeight: 800, color: '#e8f4ff', marginBottom: 4 }}>Subscription</h1>
      <p style={{ color: '#5a7a9a', fontSize: 13, marginBottom: 24 }}>Pick your level. Cancel anytime.</p>

      {/* Current Status Card */}
      <div style={{ background: '#070f1f', border: '1px solid rgba(0,240,255,0.1)', borderRadius: 14, padding: '16px 24px', marginBottom: 32, display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12 }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
            <span style={{ padding: '3px 12px', borderRadius: 20, fontSize: 11, fontFamily: 'JetBrains Mono,monospace', background: 'rgba(0,240,255,0.1)', color: '#00f0ff', textTransform: 'uppercase' }}>{status?.plan || user?.plan || 'trial'}</span>
            {status?.isActive && <span style={{ padding: '3px 12px', borderRadius: 20, fontSize: 11, background: 'rgba(29,158,117,0.15)', color: '#1D9E75', fontFamily: 'JetBrains Mono,monospace' }}>ACTIVE</span>}
          </div>
          {(status?.plan === 'trial' || user?.plan === 'trial' || status?.plan === 'free' || user?.plan === 'free') && (
            <div>
              <div style={{ fontSize: 13, color: '#5a7a9a', marginBottom: 8 }}>{status?.daysLeft ?? 30} days remaining in free trial</div>
              <div style={{ height: 4, width: 200, background: 'rgba(255,255,255,0.06)', borderRadius: 4, overflow: 'hidden' }}>
                <div style={{ height: '100%', width: `${((status?.daysLeft ?? 30) / 30) * 100}%`, background: 'linear-gradient(90deg,#1D9E75,#00f0ff)', borderRadius: 4, transition: 'width 0.5s' }} />
              </div>
            </div>
          )}
          {['premium', 'basic', 'pro', 'elite'].includes(status?.plan || user?.plan) && (
            <div style={{ fontSize: 13, color: '#5a7a9a' }}>
              Premium member — full access unlocked
              {status?.endDate && <span style={{ marginLeft: 8, fontSize: 12, color: '#3a5a7a' }}>· renews {new Date(status.endDate).toLocaleDateString('en-IN')}</span>}
            </div>
          )}
        </div>
        {(!['premium', 'pro', 'elite'].includes(user?.plan)) && (
          <button onClick={() => setUpgradeModal('pro')} style={{ padding: '11px 24px', borderRadius: 10, border: 'none', cursor: 'pointer', background: 'linear-gradient(135deg,#00f0ff,#7b5cff)', color: '#020812', fontFamily: 'Syne,sans-serif', fontSize: 14, fontWeight: 700 }}>
            Upgrade to Performer →
          </button>
        )}
      </div>

      {/* Plan Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 16, marginBottom: 32 }}>
        {PLANS.map(p => (
          <div key={p.id} style={{
            background: '#070f1f',
            border: p.featured ? '2px solid rgba(0,240,255,0.5)' : '1px solid rgba(255,255,255,0.07)',
            borderRadius: 16,
            padding: '24px 24px 24px 24px',
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            boxShadow: p.featured ? '0 0 30px rgba(0,240,255,0.15)' : 'none',
            transition: 'transform 0.2s, box-shadow 0.2s',
          }}>
            {/* Top gradient line */}
            <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 2, background: `linear-gradient(90deg, transparent, ${p.color}, transparent)` }} />

            {/* Badge */}
            {p.badge && (
              <div style={{ alignSelf: 'flex-start', padding: '4px 12px', borderRadius: 20, fontSize: 11, fontWeight: 700, marginBottom: 12, background: p.featured ? 'rgba(0,240,255,0.15)' : 'rgba(123,92,255,0.15)', color: p.featured ? '#00f0ff' : '#7b5cff', border: `1px solid ${p.featured ? 'rgba(0,240,255,0.3)' : 'rgba(123,92,255,0.3)'}` }}>
                {p.badge}
              </div>
            )}
            {!p.badge && <div style={{ height: 4 }} />}

            {/* Plan name */}
            <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 20, fontWeight: 800, color: p.color, marginBottom: 4 }}>{p.name}</div>

            {/* Tagline */}
            <div style={{ fontSize: 12, color: '#5a7a9a', fontStyle: 'italic', marginBottom: 16, lineHeight: 1.5 }}>{p.tagline}</div>

            {/* Price */}
            <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 28, fontWeight: 800, color: '#e8f4ff', marginBottom: 2 }}>{p.price}</div>
            <div style={{ fontSize: 12, color: '#5a7a9a', marginBottom: 20, fontFamily: 'JetBrains Mono,monospace' }}>{p.period}</div>

            {/* Features */}
            <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 7, marginBottom: 20 }}>
              {p.features.map((f, fi) => {
                const isLocked = f.startsWith('❌');
                return (
                  <div key={fi} style={{
                    display: 'flex',
                    alignItems: 'flex-start',
                    gap: 10,
                    marginBottom: 8,
                  }}>
                    <span style={{
                      flexShrink: 0,
                      marginTop: 2,
                      fontSize: 13,
                    }}>{isLocked ? '❌' : '✓'}</span>
                    <span style={{
                      fontSize: 13,
                      color: isLocked ? '#3a4a5a' : '#c8d8e8',
                      lineHeight: 1.5,
                    }}>{f.startsWith('✅') || f.startsWith('❌') ? f.slice(2).trim() : f}</span>
                  </div>
                );
              })}
            </div>

            {/* CTA button */}
            {(p.id === 'free') ? (
              user?.plan === 'trial' || user?.plan === 'free' ? (
                <div style={{ textAlign: 'center', fontSize: 12, color: '#1D9E75', padding: '10px 0', fontWeight: 600 }}>✓ Your current plan</div>
              ) : (
                <div style={{ textAlign: 'center', fontSize: 12, color: '#5a7a9a', padding: '10px 0' }}>{p.cta}</div>
              )
            ) : user?.plan === p.id ? (
              <div style={{ textAlign: 'center', fontSize: 12, color: '#1D9E75', padding: '10px 0', fontWeight: 600 }}>✓ You have this plan</div>
            ) : (
              <button
                onClick={() => setUpgradeModal(p.id)}
                style={{
                  padding: '12px 20px',
                  borderRadius: 10,
                  border: p.featured ? 'none' : '1px solid rgba(255,255,255,0.1)',
                  cursor: 'pointer',
                  background: p.featured ? 'linear-gradient(135deg,#00f0ff,#7b5cff)' : 'rgba(255,255,255,0.04)',
                  color: p.featured ? '#020812' : '#c8d8e8',
                  fontFamily: 'Syne,sans-serif',
                  fontSize: 14,
                  fontWeight: 700,
                  width: '100%',
                  transition: 'opacity 0.2s',
                }}
              >
                {p.cta}
              </button>
            )}
          </div>
        ))}
      </div>

      {/* Trust badges */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 16, justifyContent: 'center', flexWrap: 'wrap', marginBottom: 32 }}>
        {['🔒 256-bit SSL', '🏦 RBI-regulated', '💳 UPI · Cards · Net Banking', '🔁 Cancel anytime'].map(b => (
          <span key={b} style={{ fontSize: 12, color: '#3a5a7a' }}>{b}</span>
        ))}
      </div>

      {/* Payment Modal */}
      {upgradeModal && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50, padding: 16 }}>
          <div style={{ background: '#070f1f', border: '1px solid rgba(0,240,255,0.2)', borderRadius: 20, maxWidth: 420, width: '100%', padding: 32, boxShadow: '0 20px 60px rgba(0,0,0,0.6)' }}>
            <div style={{ fontFamily: 'Syne,sans-serif', fontSize: 20, fontWeight: 800, color: '#e8f4ff', marginBottom: 6 }}>
              {PLANS.find(p => p.id === upgradeModal)?.name}
            </div>
            <div style={{ fontSize: 13, color: '#5a7a9a', fontStyle: 'italic', marginBottom: 20 }}>
              {PLANS.find(p => p.id === upgradeModal)?.tagline}
            </div>
            <div style={{ fontSize: 28, fontWeight: 800, fontFamily: 'Syne,sans-serif', color: '#e8f4ff', marginBottom: 4 }}>{planPrice(upgradeModal)}<span style={{ fontSize: 14, color: '#5a7a9a', fontWeight: 400 }}>/month</span></div>

            <div style={{ background: 'rgba(0,240,255,0.04)', border: '1px solid rgba(0,240,255,0.1)', borderRadius: 12, padding: 16, marginBottom: 24, marginTop: 16 }}>
              <div style={{ fontSize: 12, color: '#5a7a9a', marginBottom: 8, fontFamily: 'JetBrains Mono,monospace' }}>WHAT YOU GET:</div>
              {PLANS.find(p => p.id === upgradeModal)?.features.filter(f => f.startsWith('✅')).slice(0, 5).map((f, i) => (
                <div key={i} style={{ fontSize: 12, color: '#c8d8e8', padding: '4px 0', display: 'flex', gap: 6 }}>
                  <span>✅</span><span>{f.slice(3)}</span>
                </div>
              ))}
            </div>

            <RazorpayButton
              plan={upgradeModal}
              label={`Pay ${planPrice(upgradeModal)} securely with Razorpay`}
              className="btn-primary w-full justify-center mb-3"
              onSuccess={() => { setUpgradeModal(null); refreshStatus(); }}
            />

            <button
              onClick={() => setUpgradeModal(null)}
              style={{ width: '100%', padding: '11px', borderRadius: 10, border: '1px solid rgba(255,255,255,0.08)', background: 'transparent', color: '#5a7a9a', cursor: 'pointer', fontFamily: 'Syne,sans-serif', fontSize: 13, marginTop: 8 }}
            >
              Cancel
            </button>

            <div style={{ textAlign: 'center', fontSize: 11, color: '#3a5a7a', marginTop: 12 }}>
              🔒 Secured by Razorpay · UPI, cards, net banking accepted
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
