-- Add any missing columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS learning_speed TEXT DEFAULT 'normal';
ALTER TABLE users ADD COLUMN IF NOT EXISTS year INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bonus_days INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_reward_streak INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS weekly_badge TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_stars INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_repos INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_commits INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_languages JSONB DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_last_synced TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banned_until TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS badge_updated_at TIMESTAMPTZ;
